import { Router } from 'express';
import jwt from 'jsonwebtoken';
import { authenticateAdmin, type AuthRequest } from '../middleware/auth.js';
import { getCanonicalStore } from '../services/canonicalStore.js';
import { getCategoryTrends, getGeographicDensity, getMarketIntelData } from '../services/analyticsEngine.js';
import { getAllAIAgents, getAIAgentById, createAIAgent, updateAIAgent, deleteAIAgent, cloneAIAgent, executeAgentTask } from '../services/aiAgentService.js';
import { getAllCommissions, updateCommission } from '../services/commissionService.js';
import { getAllPricing, updatePlan, createPlan, deletePlan } from '../services/pricingService.js';
import { schedulePost } from '../services/socialScheduler.js';
import { queryGroq } from '../services/groqService.js';
import { issueUserToken, upsertProfile } from './authRoutes.js';
import { getConfiguredTestName, getConfiguredTestPhone, getDevelopmentTestAuthStatus } from '../services/devTestAuthService.js';
import { getProfile, updateProfile } from '../services/memoryProfile.js';
import { getPilotReadiness } from '../services/pilotReadiness.js';
import { getExternalIntegrationReadiness } from '../services/externalIntegrationReadiness.js';
import { createAdCampaign, getAdCampaigns, updateAdCampaign } from '../services/adManager.js';
import { testMistralConnection } from '../services/mistralService.js';
import { getNotificationQueueStats } from '../services/pushNotifications.js';
import { approveLearningArtifact, getContextArbitrationTelemetry, getCoordinatorTelemetry, listCoordinatorRuns, listLearningArtifacts } from '../services/coordinatorStore.js';
import { getPrivacyBridgeStatus } from '../services/privacyBridge.js';
import { getSmolLM2RuntimeStatus } from '../services/smolLm2Service.js';
import { listCountryExperiences } from '../services/countryExperience.js';
import { getTelegramLinkedDeviceStatus, startTelegramLinkedDevice, stopTelegramLinkedDevice } from '../services/telegramLinkedDeviceService.js';
import { getWhatsAppLinkedDeviceStatus } from '../services/whatsappLinkedDeviceService.js';
import { listTrustedDevices, revokeTrustedDevice } from '../services/progressiveTrustService.js';
import { listCurationCandidates, getCurationCandidate, reviewCurationCandidate, rewriteCurationCandidate, getCurationStats, getAcceptedCorpusGate, getCurationAudit } from '../services/curationService.js';
import { getEconomicCategory, getKnownSkills, getSkillFlow, getSkillRequirements } from '../services/skillFlows.js';

const router=Router();
const operatorPhone=()=>String(process.env.KURUKOO_OPERATOR_PHONE||process.env.ADMIN_OPERATOR_PHONE||'').trim();
const operatorName=()=>String(process.env.KURUKOO_OPERATOR_NAME||'Kurukoo Operator').trim();
function setUserCookie(res:any,token:string){const secure=process.env.NODE_ENV==='production'?'; Secure':'';res.setHeader('Set-Cookie',`kurukoo_auth=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000${secure}`);}
function jsonError(res:any,error:unknown,status=500){return res.status(status).json({success:false,error:error instanceof Error?error.message:String(error)});}

router.post('/auth',(req,res)=>{const{username,password}=req.body||{},adminUser=process.env.ADMIN_USERNAME||'admin',adminPass=process.env.ADMIN_PASSWORD,secret=process.env.JWT_SECRET;if(!adminPass||!secret||secret.length<32)return res.status(503).json({success:false,error:'Admin authentication is not configured'});if(username===adminUser&&password===adminPass)return res.json({success:true,token:jwt.sign({role:'admin'},secret,{expiresIn:'24h'})});return res.status(401).json({success:false,error:'Invalid credentials'});});
router.use(authenticateAdmin);

router.get('/test-chat',async(_req:AuthRequest,res)=>{const status=getDevelopmentTestAuthStatus();if(!status.active||!status.configured)return res.status(404).json({success:false,error:'Development test authentication is not enabled or configured'});const phone=getConfiguredTestPhone();await upsertProfile(phone,getConfiguredTestName(),'','buyer');const profile=await getProfile(phone,'admin_test_chat');if(profile&&profile.preferences?.onboarding_complete!==true)await updateProfile(phone,'admin_test_chat',{name:getConfiguredTestName(),preferences:{...(profile.preferences||{}),onboarding_complete:true,development_test_account:true}});setUserCookie(res,issueUserToken(phone));res.json({success:true,testMode:true,phone,name:getConfiguredTestName(),redirect:'/chat?test_mode=1'});});
router.post('/test-chat/reset',async(_req:AuthRequest,res)=>{const status=getDevelopmentTestAuthStatus();if(!status.active||!status.configured)return res.status(404).json({success:false,error:'Development test authentication is not enabled or configured'});const phone=getConfiguredTestPhone();try{const db=await getCanonicalStore();await db.transaction(async tx=>{for(const table of ['memory_profiles','messages','chat_message_meta','reminders','user_behavior_signals','phone_otps','agent_goals','agent_goal_events']){try{await tx.run(`DELETE FROM ${table} WHERE phone=?`,[phone]);}catch{}}});await upsertProfile(phone,getConfiguredTestName(),'','buyer');await updateProfile(phone,'admin_test_chat',{name:getConfiguredTestName(),preferences:{goal:'buyer',onboarding_complete:true,development_test_account:true,test_state_reset_at:new Date().toISOString()}});res.json({success:true,testMode:true,phone,preserved:['economic_requests','orders','escrow','payments','disputes']});}catch(error){return jsonError(res,error);}});

router.get('/operator/state',async(_req,res)=>{const phone=operatorPhone();if(!phone)return res.status(503).json({success:false,error:'KURUKOO_OPERATOR_PHONE is not configured'});const db=await getCanonicalStore();const profile=await db.one<any>('SELECT phone,name,location,subscription_tier,points_balance,is_available,is_contributor,provider_type FROM memory_profiles WHERE phone=?',[phone]);res.json({success:true,operator:{phone,name:operatorName()},actors:[{id:'operator',phone,name:operatorName(),role:'super_admin',exists:Boolean(profile),profile:profile||null}],testBoundary:'explicit_operator_session_claim'});});
router.get('/operator/chat',async(_req,res)=>{const phone=operatorPhone();if(!phone)return res.status(503).json({success:false,error:'KURUKOO_OPERATOR_PHONE is not configured'});if(process.env.NODE_ENV!=='production'&&process.env.KURUKOO_TEST_RESET_OPERATOR_ON_LAUNCH==='true'){const db=await getCanonicalStore();await db.run('DELETE FROM memory_profiles WHERE phone=?',[phone]);}await upsertProfile(phone,operatorName(),'','super_admin');const token=issueUserToken(phone,{operatorPhone:phone,operatorSession:true,actorRole:'super_admin',actorContextId:'operator'});setUserCookie(res,token);res.json({success:true,operator:{phone,name:operatorName()},redirect:'/chat?operator=1',session:{operator:true,phone,actorRole:'super_admin'}});});
router.get('/operator/actors',async(_req,res)=>{const phone=operatorPhone();res.json({success:true,actors:[{id:'operator',phone,name:operatorName(),role:'super_admin',testOnly:true,identityBoundary:'isolated_actor_context',configured:Boolean(phone)}]});});
router.post('/operator/actors/:actorId/chat',async(req,res)=>{if(req.params.actorId!=='operator')return res.status(404).json({success:false,error:'Unknown controlled actor'});const phone=operatorPhone();if(!phone)return res.status(503).json({success:false,error:'KURUKOO_OPERATOR_PHONE is not configured'});await upsertProfile(phone,operatorName(),'','super_admin');const token=issueUserToken(phone,{operatorPhone:phone,operatorSession:true,testActor:true,actorRole:'super_admin',actorContextId:'operator'});setUserCookie(res,token);res.json({success:true,actor:{id:'operator',phone,name:operatorName(),role:'super_admin'},testOnly:true,identityBoundary:'isolated_actor_context',resetEndpoint:'/api/admin/operator/actors/operator/reset',redirect:'/chat?test_actor=operator'});});
router.post('/operator/actors/:actorId/reset',async(req,res)=>{if(req.params.actorId!=='operator')return res.status(404).json({success:false,error:'Unknown controlled actor'});const phone=operatorPhone();if(!phone)return res.status(503).json({success:false,error:'KURUKOO_OPERATOR_PHONE is not configured'});const db=await getCanonicalStore();await db.run('DELETE FROM memory_profiles WHERE phone=?',[phone]);res.json({success:true,actor:{id:'operator',phone,name:operatorName()},reset:true,preserved:['operator_identity','other_actor_contexts','production_user_data']});});

router.get('/trust/readiness',async(_req,res)=>{try{const db=await getCanonicalStore();const count=async(sql:string,args:any[]=[])=>(await db.one<any>(sql,args))?.count??(await db.one<any>(sql,args))?.count_1??0;const channelRows=await db.all<any>('SELECT channel,status,COUNT(*) AS count FROM channel_evidence GROUP BY channel,status').catch(()=>[] as any[]);const channelEvidence:Record<string,Record<string,number>>={};for(const row of channelRows){channelEvidence[String(row.channel)] ||= {};channelEvidence[String(row.channel)][String(row.status)]=Number(row.count||0);}res.json({success:true,timestamp:new Date().toISOString(),featureFlags:{progressiveTrust:process.env.KURUKOO_PROGRESSIVE_TRUST_ENABLED==='true',pushApproval:process.env.KURUKOO_PUSH_APPROVAL_ENABLED==='true',channelEvidence:process.env.KURUKOO_CHANNEL_EVIDENCE_ENABLED==='true',emailOtp:process.env.KURUKOO_EMAIL_OTP_ENABLED==='true',privateNumberMasking:process.env.FF_PRIVATE_NUMBER_MASKING==='true'},trustedDevices:{active:await count("SELECT COUNT(*) AS count FROM trusted_devices WHERE status='active'"),revoked:await count("SELECT COUNT(*) AS count FROM trusted_devices WHERE status='revoked'")},trustChallenges:{pending:await count("SELECT COUNT(*) AS count FROM trust_challenges WHERE status='pending' AND expires_at > CURRENT_TIMESTAMP"),approved:await count("SELECT COUNT(*) AS count FROM trust_challenges WHERE status='approved'"),denied:await count("SELECT COUNT(*) AS count FROM trust_challenges WHERE status='denied'")},channelEvidence,connectors:{whatsappLinkedDevice:getWhatsAppLinkedDeviceStatus(),telegramLinkedDevice:getTelegramLinkedDeviceStatus()},privacyNumberMasking:getPrivacyBridgeStatus(),brain:{localModel:getSmolLM2RuntimeStatus(),firstClassPersonaCoordination:{eventType:'agent.persona.requested',capability:'first_class_agent_persona',policyReviewed:true,guestSafe:true,ownerCharging:'authenticated_only'},telemetry:await getCoordinatorTelemetry(),contextArbitration:await getContextArbitrationTelemetry()},deliveryClaims:'Internal readiness and persisted states only; no external delivery or provider ownership is claimed.'});}catch(error){return jsonError(res,error);}});
router.get('/connectors/telegram-linked-device/status',async(_req,res)=>res.json({success:true,status:getTelegramLinkedDeviceStatus(),activation:'Deployment flags and Telegram API credentials remain environment-managed.'}));
router.post('/connectors/telegram-linked-device/start',async(_req,res)=>{try{await startTelegramLinkedDevice();return res.status(202).json({success:true,status:getTelegramLinkedDeviceStatus()});}catch(error){return res.status(503).json({success:false,error:error instanceof Error?error.message:'Telegram linked-device start failed.',status:getTelegramLinkedDeviceStatus()});}});
router.post('/connectors/telegram-linked-device/stop',async(_req,res)=>{await stopTelegramLinkedDevice(false);res.json({success:true,status:getTelegramLinkedDeviceStatus()});});

router.get('/stats',async(_req,res)=>{try{const db=await getCanonicalStore();const[users,providers,requests,messages]=await Promise.all([db.one<any>('SELECT COUNT(*) AS count FROM memory_profiles'),db.one<any>('SELECT COUNT(*) AS count FROM memory_profiles WHERE verified_provider=1'),db.one<any>('SELECT COUNT(*) AS count FROM economic_requests'),db.one<any>('SELECT COUNT(*) AS count FROM messages')]);res.json({success:true,users:Number(users?.count||0),providers:Number(providers?.count||0),economicRequests:Number(requests?.count||0),messages:Number(messages?.count||0)});}catch(error){return jsonError(res,error);}});
router.get('/users',async(req,res)=>{try{const q=String(req.query.search||'').trim(),db=await getCanonicalStore();const rows=q?await db.all<any>(`SELECT phone,name,location,subscription_tier,verified_provider,provider_type,created_at FROM memory_profiles WHERE phone ILIKE ? OR name ILIKE ? ORDER BY created_at DESC LIMIT 200`,[`%${q}%`,`%${q}%`]):await db.all<any>('SELECT phone,name,location,subscription_tier,verified_provider,provider_type,created_at FROM memory_profiles ORDER BY created_at DESC LIMIT 200');res.json({success:true,users:rows});}catch(error){return jsonError(res,error);}});
router.get('/ai-agents',async(_req,res)=>{try{res.json({success:true,agents:await getAllAIAgents()});}catch(error){return jsonError(res,error);}});
router.get('/ai-agents/:id',async(req,res)=>{try{const agent=await getAIAgentById(String(req.params.id));return agent?res.json({success:true,agent}):res.status(404).json({success:false,error:'Agent not found'});}catch(error){return jsonError(res,error);}});
router.post('/ai-agents',async(req,res)=>{try{res.status(201).json({success:true,agent:await createAIAgent(req.body||{})});}catch(error){return jsonError(res,error,422);}});
router.put('/ai-agents/:id',async(req,res)=>{try{res.json({success:true,agent:await updateAIAgent(String(req.params.id),req.body||{})});}catch(error){return jsonError(res,error,422);}});
router.delete('/ai-agents/:id',async(req,res)=>{try{res.json({success:true,deleted:await deleteAIAgent(String(req.params.id))});}catch(error){return jsonError(res,error);}});
router.post('/ai-agents/:id/clone',async(req,res)=>{try{res.status(201).json({success:true,agent:await cloneAIAgent(String(req.params.id))});}catch(error){return jsonError(res,error,422);}});
router.post('/ai-agents/:id/execute',async(req,res)=>{try{res.json({success:true,result:await executeAgentTask(String(req.params.id),req.body?.task,req.body?.context)});}catch(error){return jsonError(res,error,422);}});

router.get('/pricing',async(_req,res)=>{try{res.json({success:true,pricing:await getAllPricing()});}catch(error){return jsonError(res,error);}});
router.put('/pricing/:id',async(req,res)=>{try{res.json({success:true,plan:await updatePlan(String(req.params.id),req.body||{})});}catch(error){return jsonError(res,error,422);}});
router.post('/pricing',async(req,res)=>{try{res.status(201).json({success:true,plan:await createPlan(req.body||{})});}catch(error){return jsonError(res,error,422);}});
router.delete('/pricing/:id',async(req,res)=>{try{res.json({success:true,deleted:await deletePlan(String(req.params.id))});}catch(error){return jsonError(res,error);}});
router.get('/revenue',async(_req,res)=>{try{res.json({success:true,commissions:await getAllCommissions()});}catch(error){return jsonError(res,error);}});
router.put('/revenue/:id',async(req,res)=>{try{res.json({success:true,commission:await updateCommission(String(req.params.id),req.body||{})});}catch(error){return jsonError(res,error,422);}});
router.get('/analytics',async(req,res)=>{try{res.json({success:true,categoryTrends:await getCategoryTrends(),geographicDensity:await getGeographicDensity(),marketIntel:await getMarketIntelData(),range:req.query.range||'30d'});}catch(error){return jsonError(res,error);}});
router.get('/pilot-readiness',async(_req,res)=>{try{res.json({success:true,readiness:await getPilotReadiness()});}catch(error){return jsonError(res,error);}});
router.get('/external-integrations',async(_req,res)=>{try{res.json({success:true,readiness:await getExternalIntegrationReadiness()});}catch(error){return jsonError(res,error);}});
router.get('/ads',async(_req,res)=>{try{res.json({success:true,campaigns:await getAdCampaigns()});}catch(error){return jsonError(res,error);}});
router.post('/ads',async(req,res)=>{try{res.status(201).json({success:true,campaign:await createAdCampaign(req.body||{})});}catch(error){return jsonError(res,error,422);}});
router.put('/ads/:id',async(req,res)=>{try{res.json({success:true,campaign:await updateAdCampaign(String(req.params.id),req.body||{})});}catch(error){return jsonError(res,error,422);}});
router.get('/country-experiences',async(_req,res)=>{try{res.json({success:true,experiences:await listCountryExperiences()});}catch(error){return jsonError(res,error);}});
router.get('/notification-queue',async(_req,res)=>{try{res.json({success:true,stats:await getNotificationQueueStats()});}catch(error){return jsonError(res,error);}});
router.get('/smol-lm2',async(_req,res)=>res.json({success:true,status:getSmolLM2RuntimeStatus()}));
router.post('/mistral/test',async(_req,res)=>{try{res.json({success:true,status:await testMistralConnection()});}catch(error){return jsonError(res,error);}});
router.get('/privacy',async(_req,res)=>res.json({success:true,status:getPrivacyBridgeStatus()}));

router.get('/celebrity',async(_req,res)=>{try{const db=await getCanonicalStore();res.json({success:true,demand:await db.all<any>('SELECT * FROM celebrity_demand ORDER BY interested_users DESC').catch(()=>[])});}catch(error){return jsonError(res,error);}});
router.get('/future_plans',async(_req,res)=>{try{const db=await getCanonicalStore();res.json({success:true,plans:await db.all<any>('SELECT * FROM future_plans ORDER BY id DESC').catch(()=>[])});}catch(error){return jsonError(res,error);}});
router.get('/social_posts',async(_req,res)=>{try{const db=await getCanonicalStore();res.json({success:true,posts:await db.all<any>('SELECT * FROM social_posts ORDER BY created_at DESC LIMIT 200').catch(()=>[])});}catch(error){return jsonError(res,error);}});
router.post('/social_posts',async(req,res)=>{try{res.status(201).json({success:true,result:await schedulePost(req.body||{})});}catch(error){return jsonError(res,error,422);}});
router.get('/partnerships',async(_req,res)=>{const db=await getCanonicalStore();res.json({success:true,partnerships:await db.all<any>('SELECT * FROM partnerships ORDER BY created_at DESC').catch(()=>[])});});
router.get('/scam_reports',async(_req,res)=>{const db=await getCanonicalStore();res.json({success:true,reports:await db.all<any>('SELECT * FROM scam_reports ORDER BY created_at DESC').catch(()=>[])});});

router.get('/operator/learning',async(_req,res)=>res.json({success:true,artifacts:await listLearningArtifacts(),runs:await listCoordinatorRuns()}));
router.post('/operator/learning/:id/approve',async(req,res)=>{if(process.env.KURUKOO_COORDINATOR_PROMOTION_ENABLED!=='true')return res.status(503).json({success:false,error:'Learning-artifact promotion is disabled for this deployment.'});const operatorId=String(req.user?.phone||`admin:${process.env.ADMIN_USERNAME||'admin'}`);const result=await approveLearningArtifact({id:String(req.params.id||''),operatorId,evaluationScore:req.body?.evaluationScore===undefined?undefined:Number(req.body.evaluationScore),policyVersion:req.body?.policyVersion?String(req.body.policyVersion):undefined});const status=result.ok?200:result.status==='missing'?404:result.status==='conflict'?409:400;return res.status(status).json({success:result.ok,...result,runtimeActivation:'separate_feature_flag_and_canary_required'});});
router.get('/curation/candidates',async(req,res)=>res.json({success:true,candidates:await listCurationCandidates(String(req.query.status||'pending'),Number(req.query.limit||50))}));
router.get('/curation/stats',async(_req,res)=>res.json({success:true,stats:await getCurationStats()}));
router.get('/curation/gate',async(_req,res)=>res.json({success:true,gate:await getAcceptedCorpusGate()}));
router.get('/curation/audit',async(_req,res)=>res.json({success:true,audit:await getCurationAudit()}));
router.get('/curation/candidates/:exampleId',async(req,res)=>res.json({success:true,candidate:await getCurationCandidate(String(req.params.exampleId||''))}));
router.post('/curation/candidates/:exampleId/review',async(req,res)=>res.json({success:true,result:await reviewCurationCandidate(String(req.params.exampleId||''),req.body||{})}));
router.post('/curation/candidates/:exampleId/rewrite',async(req,res)=>res.json({success:true,result:await rewriteCurationCandidate(String(req.params.exampleId||''),req.body||{})}));

router.get('/skill-flows',async(_req,res)=>{const skills=getKnownSkills();res.json({success:true,flows:await Promise.all(skills.map(async skill=>await getSkillFlow(skill))),count:skills.length});});
router.get('/skill-flows/:skill',async(req,res)=>{const flow=await getSkillFlow(String(req.params.skill||''));return flow?res.json({success:true,flow,requirements:getSkillRequirements(String(req.params.skill||'')),category:getEconomicCategory(String(req.params.skill||''))}):res.status(404).json({success:false,error:'Skill flow not found'});});

export default router;
