/* Copyright (c) 2026 temeaco-max. All rights reserved. Proprietary and confidential. */
import express from 'express';
import path from 'node:path';
import { optionalAuthenticateUser, type AuthRequest } from '../middleware/auth.js';
import { getExternalIntegrationReadiness } from '../services/externalIntegrationReadiness.js';
import { getPilotReadiness } from '../services/pilotReadiness.js';
import { getClientSurfaces } from '../services/clientSurfaceRegistry.js';
import { getCanonicalDiscoverablePlatformFeatures } from '../services/canonicalPlatformFeatureRegistry.js';
import { getPageContentContract } from '../services/pageContentContracts.js';
import { getProfile } from '../services/memoryProfile.js';
import economicDispatchRoutes from './economicDispatchRoutes.js';

const router = express.Router();
const surfaceMap = new Map([
  ['desk', { title: 'Home', eyebrow: 'What matters now', description: 'See what needs your attention, pick up where you left off, and start something new with Kurukoo.', cta: '/chat', ctaLabel: 'Talk to Kurukoo' }],
  ['discover', { title: 'Explore', eyebrow: 'Find something useful', description: 'Find people, places, services, products, Topics and opportunities, then bring what matters into a conversation.', cta: '/chat', ctaLabel: 'Ask Kurukoo' }],
  ['topics', { title: 'Topics', eyebrow: 'Community context', description: 'Browse and share moderated community questions, reports and experiences while keeping community discussion separate from fulfilment claims.', cta: '/chat', ctaLabel: 'Discuss in Chat' }],
  ['requests', { title: 'Activity', eyebrow: 'Work in motion', description: 'See what is happening, what needs you, and what has finished. Open any item to continue the work in context.', cta: '/chat?prompt=Show%20me%20what%20needs%20my%20attention', ctaLabel: 'Ask what is next' }],
  ['reminders', { title: 'Reminders', eyebrow: 'Keep life on track', description: 'Create and review scheduled help while keeping the original conversation and context close.', cta: '/chat?prompt=Show%20me%20my%20reminders', ctaLabel: 'Manage in Chat' }],
  ['saved', { title: 'Saved', eyebrow: 'Keep useful context close', description: 'Keep useful discoveries, offers and conversations close so you can return to them when you are ready.', cta: '/chat?prompt=Show%20me%20my%20saved%20items', ctaLabel: 'Ask about Saved' }],
  ['cart', { title: 'Cart', eyebrow: 'Prepare an economic action', description: 'Review sourced items and options before you ask Kurukoo to continue into a request or verified checkout.', cta: '/cart', ctaLabel: 'Review Cart' }],
  ['tasks', { title: 'Work', eyebrow: 'Things that need doing', description: 'See work you have accepted, work available to you, and the evidence needed to finish it.', cta: '/chat?prompt=Show%20me%20my%20work', ctaLabel: 'Ask about Work' }],
  ['connect', { title: 'Connect', eyebrow: 'Bring your tools together', description: 'Manage the tools, channels, devices and sources Kurukoo is allowed to use on your behalf.', cta: '/connect', ctaLabel: 'Manage connections' }],
  ['agents', { title: 'Agents', eyebrow: 'Work Kurukoo can continue for you', description: 'Review bounded agents and their active objectives. Use Chat to start, guide or stop work.', cta: '/chat', ctaLabel: 'Talk to Kurukoo' }],
  ['capabilities', { title: 'Capabilities', eyebrow: 'How you participate', description: 'Manage the capabilities available under your identity, including provider, contributor, seller, buyer and delivery roles.', cta: '/chat', ctaLabel: 'Ask about capabilities' }],
  ['opportunities', { title: 'Opportunities', eyebrow: 'Ways to participate', description: 'Review relevant ways to participate in the Kurukoo network and continue any opportunity in context.', cta: '/chat', ctaLabel: 'Ask about opportunities' }],
  ['wallet', { title: 'Wallet', eyebrow: 'Money', description: 'See your cash balance and economic activity. Payment providers are only treated as successful when their evidence confirms it.', cta: '/wallet', ctaLabel: 'Open Wallet' }],
  ['points', { title: 'Points', eyebrow: 'Network value', description: 'See your closed-loop Kurukoo Points balance and activity separately from cash payment rails.', cta: '/points', ctaLabel: 'Open Points' }],
  ['top-up', { title: 'Top Up', eyebrow: 'Add funds', description: 'Choose an amount and continue through the configured payment path. Kurukoo never turns an attempted charge into claimed success.', cta: '/top-up', ctaLabel: 'Top up' }],
  ['subscriptions', { title: 'Plans', eyebrow: 'Plans and entitlements', description: 'Compare plans and manage entitlements without implying a successful charge until payment evidence is available.', cta: '/subscriptions', ctaLabel: 'View Plans' }],
  ['checkout', { title: 'Checkout', eyebrow: 'Review before you confirm', description: 'Check the request, offer, price and payment state before an irreversible economic action.', cta: '/activity', ctaLabel: 'Back to Activity' }],
  ['confirmations', { title: 'Outcome', eyebrow: 'Know what happened', description: 'Understand the confirmed result, evidence and next step for work you asked Kurukoo to handle.', cta: '/activity', ctaLabel: 'Back to Activity' }],
  ['memory', { title: 'Memory', eyebrow: 'What Kurukoo keeps for you', description: 'Review owner-scoped memory, its source and privacy boundary, and remove anything you no longer want kept.', cta: '/chat', ctaLabel: 'Ask about Memory' }],
  ['artifacts', { title: 'Files', eyebrow: 'Your files and recordings', description: 'Browse owner-scoped files, recordings and transcripts and continue from their originating context.', cta: '/chat', ctaLabel: 'Ask about Files' }],
  ['prayer', { title: 'Prayer', eyebrow: 'A first-class Kurukoo companion', description: 'Start a prayer, keep continuity, set a reminder or use supported voice without creating a separate identity.', cta: '/chat?prompt=I%20would%20like%20a%20prayer', ctaLabel: 'Start in Chat' }],
  ['call', { title: 'Call', eyebrow: 'Talk with Kurukoo or another person', description: 'See realtime communication readiness and continue within the same identity and conversation relationship.', cta: '/call', ctaLabel: 'Open Call' }],
  ['notifications', { title: 'Notifications', eyebrow: 'What needs your attention', description: 'See actionable updates and return directly to the request, reminder, conversation or other thing that needs you.', cta: '/notifications', ctaLabel: 'Open Notifications' }],
  ['safety', { title: 'Safety', eyebrow: 'Check-ins and trusted support', description: 'Manage consent-bound check-ins and trusted contacts without implying emergency-service fulfilment.', cta: '/safety', ctaLabel: 'Open Safety' }],
  ['settings', { title: 'Settings', eyebrow: 'Your Kurukoo account', description: 'Manage account, privacy, notifications, connections, accessibility and product preferences in one place.', cta: '/settings', ctaLabel: 'Open Settings' }],
]);
const cleanCanonicalSections: Record<string, string> = { '/chat': 'chat', '/home': 'desk', '/desk': 'desk', '/explore': 'discover', '/discover': 'discover', '/activity': 'requests', '/requests': 'requests', '/reminders': 'reminders', '/saved': 'saved', '/cart': 'cart', '/tasks': 'tasks', '/connect': 'connect', '/agents': 'agents', '/capabilities': 'capabilities', '/opportunities': 'opportunities', '/wallet': 'wallet', '/points': 'points', '/top-up': 'top-up', '/subscriptions': 'subscriptions', '/checkout': 'checkout', '/confirmations': 'confirmations', '/memory': 'memory', '/artifacts': 'artifacts', '/prayer': 'prayer', '/call': 'call', '/notifications': 'notifications', '/safety': 'safety', '/settings': 'settings' };
const canonicalPathBySection: Record<string, string> = { chat: '/chat', desk: '/home', discover: '/explore', requests: '/activity', tasks: '/tasks', connect: '/connect', reminders: '/reminders', saved: '/saved', cart: '/cart', agents: '/agents', capabilities: '/capabilities', opportunities: '/opportunities', wallet: '/wallet', points: '/points', 'top-up': '/top-up', subscriptions: '/subscriptions', checkout: '/checkout', confirmations: '/activity', memory: '/memory', artifacts: '/artifacts', prayer: '/prayer', call: '/call', notifications: '/notifications', safety: '/safety', settings: '/settings' };
const sharedPublicAuthenticated = new Set(['/explore', '/discover', '/topics']);
function selectedFor(section: string) { return surfaceMap.get(section) ?? surfaceMap.get('desk')!; }
function appLocals(req: express.Request, section: string, resourceId?: string) { const authReq = req as AuthRequest; const integrations = getExternalIntegrationReadiness(); return { selected: selectedFor(section), section, canonicalPath: canonicalPathBySection[section] || req.path, displayName: authReq.user?.name || authReq.user?.phone || '', phone: authReq.user?.phone || '', surfaces: getClientSurfaces('web'), readiness: getPilotReadiness(), integrations, enabledIntegrations: integrations.filter((item: any) => item.implementation?.state === 'IMPLEMENTED' || item.implementation?.implemented === true).length, integrationCount: integrations.length, visualFeatures: getCanonicalDiscoverablePlatformFeatures().filter(feature => !feature.audience.includes('admin')), resourceId, contentContract: getPageContentContract(section) }; }
function renderApp(req: express.Request, res: express.Response, section = 'desk') { const authReq = req as AuthRequest; if (!authReq.user?.phone) return res.redirect(302, `/login?return=${encodeURIComponent(req.originalUrl || req.path)}`); return res.render('app', appLocals(req, section)); }
router.get('/api/memory/profile', optionalAuthenticateUser, async (req: express.Request, res: express.Response) => { const phone = (req as AuthRequest).user?.phone ? String((req as AuthRequest).user?.phone) : null; if (!phone) return res.status(401).json({ success: false, error: 'Authentication required' }); try { const profile = await getProfile(phone, 'memory_surface'); const preferences = profile?.preferences && typeof profile.preferences === 'object' ? profile.preferences as Record<string, unknown> : {}; const proactiveBrief = preferences.proactive_brief && typeof preferences.proactive_brief === 'object' ? preferences.proactive_brief : {}; return res.json({ success: true, profile: { name: profile?.name || '', location: profile?.location || '', country: profile?.country || '' }, proactiveBrief }); } catch { return res.status(500).json({ success: false, error: 'Unable to read canonical Memory Profile' }); } });
router.get('/api/platform/feature-visuals', (_req, res) => res.json({ success: true, features: getCanonicalDiscoverablePlatformFeatures().filter(feature => !feature.audience.includes('admin')) }));
router.use('/api', economicDispatchRoutes);
router.get('/features', (_req, res) => res.render('features'));
router.get('/developers', (_req, res) => res.render('developers'));
router.get('/developers/api', (_req, res) => res.render('developers'));
router.get('/chat/:conversationId', (req, res) => { res.setHeader('X-Kurukoo-Conversation-Id', String(req.params.conversationId)); return res.sendFile(path.join(process.cwd(), 'public', 'chat', 'index.html')); });
router.get('/share/:shareId', (req, res) => { res.setHeader('X-Kurukoo-Share-Id', String(req.params.shareId)); return res.sendFile(path.join(process.cwd(), 'public', 'chat', 'index.html')); });
for (const [pathname, section] of Object.entries(cleanCanonicalSections)) { if (pathname === '/chat') continue; router.get(pathname, optionalAuthenticateUser, (req, res, next) => { const authReq = req as AuthRequest; if (!authReq.user?.phone && sharedPublicAuthenticated.has(pathname)) return next(); return renderApp(req, res, section); }); }
for (const resource of ['requests','tasks','reminders','saved','opportunities','agents','connections','memory','artifacts']) { router.get(`/${resource}/:id`, optionalAuthenticateUser, (req, res) => { const authReq = req as AuthRequest; if (!authReq.user?.phone) return res.redirect(302, `/login?return=${encodeURIComponent(req.originalUrl)}`); const section = resource === 'connections' ? 'connect' : resource; const locals = appLocals(req, section, String(req.params.id)); locals.selected = { ...locals.selected, description: `${locals.selected.description} You are viewing this item in context.` }; return res.render('app', locals); }); }
export default router;
