import { Router } from 'express';
import { authenticateUser, type AuthRequest } from '../middleware/auth.js';
import { broadcastDispatch, acceptDispatchLead, markDispatchArrived, completeDispatch } from '../services/economicDispatchCoordinator.js';
import { createServiceReview } from '../services/serviceReviewService.js';
import { getProviderCommunicationStatus } from '../services/providerCommunicationService.js';
import { getRideVehicleOptions, normalizeRideVehicle, validateRideDispatchFields } from '../services/rideDispatchContract.js';

const router=Router();
const phone=(req:AuthRequest)=>String(req.user?.phone||'').trim();
router.get('/rides/options',authenticateUser,(_req,res)=>res.json({success:true,vehicles:getRideVehicleOptions(),dispatchModel:'broadcast_then_provider_accept',leadCharge:'on_provider_accept',communication:'request_scoped_webrtc',locationModel:'interval_gps_plus_trickbridge'}));
router.post('/economic-requests/:id/dispatch/broadcast',authenticateUser,async(req:AuthRequest,res)=>{try{const owner=phone(req);const vehicleType=normalizeRideVehicle(req.body?.vehicleType);const validation=validateRideDispatchFields({vehicleType,pickup:req.body?.pickup,destination:req.body?.destination,pickupAt:req.body?.pickupAt,passengers:req.body?.passengers,note:req.body?.note});if(!validation.valid)return res.status(400).json({success:false,error:validation.error});const pickupLabel=req.body?.pickup?.label?String(req.body.pickup.label):undefined;const result=await broadcastDispatch({requestId:String(req.params.id),ownerPhone:owner,skill:'ride_request',vehicleType,location:pickupLabel||req.body?.location?String(pickupLabel||req.body.location):undefined,latitude:req.body?.pickup?.latitude!==undefined?Number(req.body.pickup.latitude):(req.body?.latitude!==undefined?Number(req.body.latitude):undefined),longitude:req.body?.pickup?.longitude!==undefined?Number(req.body.pickup.longitude):(req.body?.longitude!==undefined?Number(req.body.longitude):undefined),maxProviders:req.body?.maxProviders!==undefined?Number(req.body.maxProviders):undefined});res.json({success:true,vehicleType,...result});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to broadcast dispatch request.'});}});
router.post('/dispatch-leads/:id/accept',authenticateUser,async(req:AuthRequest,res)=>{try{const result=await acceptDispatchLead({leadId:String(req.params.id),providerPhone:phone(req)});res.json({success:true,lead:result,leadChargeStatus:'charged_at_acceptance'});}catch(error){res.status(409).json({success:false,error:error instanceof Error?error.message:'Unable to accept dispatch lead.'});}});
router.post('/dispatch-leads/:id/arrived',authenticateUser,async(req:AuthRequest,res)=>{try{const result=await markDispatchArrived({leadId:String(req.params.id),providerPhone:phone(req)});const communication=getProviderCommunicationStatus();res.json({success:true,lead:result,callReady:Boolean(communication.webrtc.available&&result.communicationSessionId),communication:{webrtc:communication.webrtc,masking:communication.maskedCall}});}catch(error){res.status(409).json({success:false,error:error instanceof Error?error.message:'Unable to mark arrival.'});}});
router.post('/dispatch-leads/:id/completed',authenticateUser,async(req:AuthRequest,res)=>{try{const result=await completeDispatch({leadId:String(req.params.id),providerPhone:phone(req),evidence:typeof req.body?.evidence==='object'&&!Array.isArray(req.body.evidence)?req.body.evidence:undefined});res.json({success:true,lead:result,reviewAvailable:true,providerAvailableAgain:true,leadChargeStatus:'accepted_and_recorded'});}catch(error){res.status(409).json({success:false,error:error instanceof Error?error.message:'Unable to complete dispatch.'});}});
router.post('/economic-requests/:id/review',authenticateUser,async(req:AuthRequest,res)=>{try{const requestId=String(req.params.id);const result=await createServiceReview({requestId,reviewerPhone:phone(req),providerPhone:String(req.body?.providerPhone||''),rating:Number(req.body?.rating),feedback:req.body?.feedback?String(req.body.feedback):undefined});res.status(201).json({success:true,review:result,completionConfirmed:true,leadChargeConfirmed:true});}catch(error){res.status(422).json({success:false,error:error instanceof Error?error.message:'Unable to submit review.'});}});

export default router;