/**
 * Order / delivery routes — JWT identity only.
 */
import { Router } from 'express';
import { authenticateUser, AuthRequest } from '../middleware/auth.js';
import { getCanonicalStore } from '../services/canonicalStore.js';
import { getCanonicalPersistenceMode } from '../services/canonicalPersistence.js';
import { DeliveryAuthorizationError, DeliveryStateError, updateDeliveryStatus } from '../services/deliveryService.js';
import { finalizeOrder } from '../services/orderFinalizer.js';

const router=Router();
function sessionPhone(req:AuthRequest):string|null{return req.user?.phone?String(req.user.phone):null;}
async function ensureOrderSchema(){const s=await getCanonicalStore();if(getCanonicalPersistenceMode()==='postgres')await s.run(`CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,phone TEXT,order_type TEXT,provider_phone TEXT,amount BIGINT,status TEXT,idempotency_key TEXT UNIQUE,created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,message TEXT,updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP)`);else await s.run(`CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,phone TEXT,order_type TEXT,provider_phone TEXT,amount INTEGER,status TEXT,idempotency_key TEXT UNIQUE,created_at TEXT DEFAULT CURRENT_TIMESTAMP,message TEXT,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`);return s;}
router.get('/orders',authenticateUser,async(req:AuthRequest,res)=>{const phone=sessionPhone(req);if(!phone)return res.status(401).json({error:'Authentication required'});try{const s=await ensureOrderSchema();res.json(await s.all(`SELECT * FROM orders WHERE phone=? ORDER BY created_at DESC`,[phone]));}catch(error){console.error('[OrderRoutes] Error retrieving orders:',error);res.status(500).json({error:'Internal server error'});}});
router.get('/orders/:id',authenticateUser,async(req:AuthRequest,res)=>{const phone=sessionPhone(req);if(!phone)return res.status(401).json({error:'Authentication required'});try{const s=await ensureOrderSchema();const order=await s.one(`SELECT * FROM orders WHERE id=? AND phone=?`,[req.params.id,phone]);if(!order)return res.status(404).json({error:'Order not found'});res.json(order);}catch(error){console.error('[OrderRoutes] Error fetching order:',error);res.status(500).json({error:'Internal server error'});}});
router.post('/orders',authenticateUser,async(req:AuthRequest,res)=>{const phone=sessionPhone(req);if(!phone)return res.status(401).json({error:'Authentication required'});const {orderType,skill,details}=req.body||{};if(!orderType||!skill)return res.status(400).json({error:'orderType and skill are required'});try{res.status(201).json(await finalizeOrder(phone,orderType,{skill,...(details||{})}));}catch(error:any){console.error('[OrderRoutes] Error creating order:',error);res.status(500).json({error:error?.message||'Failed to create order'});}});
router.post('/orders/:id/delivery-status',authenticateUser,async(req:AuthRequest,res)=>{const phone=sessionPhone(req);if(!phone)return res.status(401).json({error:'Authentication required'});const {status,message}=req.body||{};if(!status)return res.status(400).json({error:'Status is required'});try{await updateDeliveryStatus(req.params.id,String(status),phone,message?String(message):undefined);res.json({success:true,message:`Order ${req.params.id} updated to ${status}.`});}catch(error){if(error instanceof DeliveryAuthorizationError)return res.status(403).json({error:error.message});if(error instanceof DeliveryStateError)return res.status(error.statusCode).json({error:error.message});console.error('[OrderRoutes] Error updating delivery status:',error);res.status(500).json({error:'Failed to update delivery status'});}});
router.get('/delivery/status',authenticateUser,async(req:AuthRequest,res)=>{const phone=sessionPhone(req);if(!phone)return res.status(401).json({error:'Authentication required'});const orderId=typeof req.query.order_id==='string'?req.query.order_id:undefined;if(!orderId)return res.status(400).json({error:'order_id is required'});try{const s=await ensureOrderSchema();const order:any=await s.one(`SELECT id,status,message,updated_at FROM orders WHERE id=? AND phone=?`,[orderId,phone]);if(!order)return res.status(404).json({error:'Order not found'});res.json({status:order.status,message:order.message||null,updatedAt:order.updated_at});}catch(error){console.error('[OrderRoutes] Error fetching delivery status:',error);res.status(500).json({error:'Internal server error'});}});
export default router;
export { router as orderRoutes };
