import { Router } from 'express';
import { authenticateUser, authenticateAdmin, type AuthRequest } from '../middleware/auth.js';
import { getCanonicalStore } from '../services/canonicalStore.js';
import { createDispute, getDisputeStatus, resolveDispute, escalateDispute } from '../services/disputeResolution.js';
import { ensureEscrowSchema, releaseEscrow, refundEscrow } from '../services/escrow.js';
import { getTrustScoreBreakdown, listTrustScoreLedger } from '../services/trustScore.js';

const router = Router();
const sessionPhone = (req: AuthRequest): string | null => req.user?.phone ? String(req.user.phone) : null;

async function ensureTrustRoutesSchema() {
  const store = await getCanonicalStore();
  const pg = process.env.KURUKOO_DATABASE_MODE === 'postgres';
  await store.run(pg
    ? `CREATE TABLE IF NOT EXISTS scam_reports(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,reporter_phone TEXT NOT NULL,reported_phone TEXT NOT NULL,description TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP)`
    : `CREATE TABLE IF NOT EXISTS scam_reports(id INTEGER PRIMARY KEY AUTOINCREMENT,reporter_phone TEXT NOT NULL,reported_phone TEXT NOT NULL,description TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
  await store.run('CREATE INDEX IF NOT EXISTS idx_scam_reports_reporter ON scam_reports(reporter_phone,created_at DESC)');
  return store;
}

async function getDisputeOwner(disputeId: number): Promise<string | null> {
  const row = await (await getCanonicalStore()).one<any>('SELECT phone FROM disputes WHERE id=?', [disputeId]);
  return row?.phone ? String(row.phone) : null;
}

async function getEscrowParties(escrowId: number): Promise<{ buyer: string; provider: string } | null> {
  await ensureEscrowSchema();
  const row = await (await getCanonicalStore()).one<any>('SELECT buyer_phone,provider_phone FROM escrow WHERE id=?', [escrowId]);
  if (!row?.buyer_phone || !row?.provider_phone) return null;
  return { buyer: String(row.buyer_phone), provider: String(row.provider_phone) };
}

async function listBuyerEscrow(phone: string) {
  await ensureEscrowSchema();
  return (await getCanonicalStore()).all(`SELECT id,order_id,amount_minor,description,status,created_at,cooling_off_until FROM escrow WHERE buyer_phone=? ORDER BY created_at DESC,id DESC`, [phone]);
}

function disputeFailureStatus(error: unknown): number {
  const message = error instanceof Error ? error.message : '';
  if (message === 'Order not found') return 404;
  if (message.includes('Only the order buyer') || message.includes('ownership mismatch')) return 403;
  if (message.includes('No held escrow') || message.includes('Invalid economic request transition')) return 409;
  return 500;
}

async function openBuyerDispute(req: AuthRequest, res: any) {
  const phone = sessionPhone(req);
  if (!phone) return res.status(401).json({ error: 'Authentication required' });
  const orderId = req.body?.order_id || req.body?.orderId;
  const reason = req.body?.reason;
  if (!orderId || !reason) return res.status(400).json({ error: 'Missing order_id or reason' });
  try {
    const opened = await createDispute(phone, String(orderId), String(reason));
    res.json({ success: true, disputeId: opened.disputeId, escrowFrozen: opened.escrowFrozen, economicRequestId: opened.economicRequestId, message: 'Dispute submitted and held escrow frozen.' });
  } catch (error) { res.status(disputeFailureStatus(error)).json({ error: error instanceof Error ? error.message : 'Failed to create dispute' }); }
}

router.get('/trust/score', authenticateUser, async (req: AuthRequest, res) => { const phone=sessionPhone(req); if(!phone)return res.status(401).json({error:'Authentication required'}); const breakdown=await getTrustScoreBreakdown(phone); if(!breakdown)return res.status(404).json({error:'Trust Score is unavailable for this profile.'}); res.json({score:breakdown.score,breakdown:{avgRating:breakdown.avgRating,completedJobs:breakdown.completedJobs,verifiedProvider:breakdown.verifiedProvider,disputesLost:breakdown.disputesLost,accountAgeDays:Number(breakdown.accountAgeDays.toFixed(2))}}); });
router.get('/trust/ledger', authenticateUser, async (req: AuthRequest, res) => { const phone=sessionPhone(req); if(!phone)return res.status(401).json({error:'Authentication required'}); res.json({entries:await listTrustScoreLedger(phone,Number(req.query.limit||25))}); });
router.post('/dispute/create', authenticateUser, openBuyerDispute); router.post('/disputes', authenticateUser, openBuyerDispute);
router.get('/escrow', authenticateUser, async (req:AuthRequest,res)=>{const phone=sessionPhone(req);if(!phone)return res.status(401).json({error:'Authentication required'});if(req.query.phone&&String(req.query.phone)!==phone)return res.status(403).json({error:'You can only view your own escrow records'});try{res.json(await listBuyerEscrow(phone));}catch{res.status(500).json({error:'Failed to load escrow records'});}});
router.post('/scam_reports', authenticateUser, async (req:AuthRequest,res)=>{const reporter=sessionPhone(req);if(!reporter)return res.status(401).json({error:'Authentication required'});const reported=String(req.body?.reported_phone||'').trim(),description=String(req.body?.description||'').trim();if(!reported||!description)return res.status(400).json({error:'Missing reported_phone or description'});try{await (await ensureTrustRoutesSchema()).run(`INSERT INTO scam_reports(reporter_phone,reported_phone,description,status) VALUES(?,?,?,'pending')`,[reporter,reported,description]);res.json({success:true,message:'Scam report submitted successfully.'});}catch(error){console.error('[TrustRoutes] scam report failed',error);res.status(500).json({error:'Failed to submit scam report'});}});
router.get('/dispute/:id', authenticateUser, async (req:AuthRequest,res)=>{const phone=sessionPhone(req);if(!phone)return res.status(401).json({error:'Authentication required'});const disputeId=Number.parseInt(req.params.id,10);if(!Number.isInteger(disputeId))return res.status(400).json({error:'Invalid dispute ID'});try{const owner=await getDisputeOwner(disputeId);if(!owner)return res.status(404).json({error:'Dispute not found'});if(owner!==phone)return res.status(403).json({error:'Forbidden: not dispute owner'});res.json({success:true,disputeId,status:await getDisputeStatus(disputeId)});}catch{res.status(500).json({error:'Failed to fetch dispute status'});}});
router.post('/dispute/:id/resolve', authenticateAdmin, async (req:AuthRequest,res)=>{const disputeId=Number.parseInt(req.params.id,10),resolution=req.body?.resolution;if(!Number.isInteger(disputeId)||!resolution)return res.status(400).json({error:'Missing disputeId or resolution'});try{await resolveDispute(disputeId,String(resolution));res.json({success:true,message:'Dispute resolved successfully.'});}catch{res.status(500).json({error:'Failed to resolve dispute'});}});
router.post('/dispute/:id/escalate', authenticateUser, async (req:AuthRequest,res)=>{const phone=sessionPhone(req);if(!phone)return res.status(401).json({error:'Authentication required'});const disputeId=Number.parseInt(req.params.id,10);if(!Number.isInteger(disputeId))return res.status(400).json({error:'Invalid dispute ID'});try{const owner=await getDisputeOwner(disputeId);if(!owner)return res.status(404).json({error:'Dispute not found'});if(owner!==phone)return res.status(403).json({error:'Forbidden: not dispute owner'});await escalateDispute(disputeId);res.json({success:true,message:'Dispute escalated to admin review.'});}catch{res.status(500).json({error:'Failed to escalate dispute'});}});
router.post('/escrow/create',authenticateUser,async(_req,res)=>res.status(409).json({error:'Direct escrow creation is disabled; use the verified Economic Request payment flow.',payment_required:true}));
router.post('/escrow/release',authenticateUser,async(req:AuthRequest,res)=>{const phone=sessionPhone(req);if(!phone)return res.status(401).json({error:'Authentication required'});const id=Number.parseInt(String(req.body?.escrow_id||''),10);if(!Number.isInteger(id))return res.status(400).json({error:'escrow_id is required'});try{const parties=await getEscrowParties(id);if(!parties)return res.status(404).json({error:'Escrow not found'});if(parties.buyer!==phone)return res.status(403).json({error:'Forbidden: only the buyer can release escrow'});const success=await releaseEscrow(id);res.json({success,message:success?'Escrow released to provider.':'Escrow is not eligible for release.'});}catch{res.status(500).json({error:'Failed to release escrow'});}});
router.post('/escrow/refund',authenticateUser,async(req:AuthRequest,res)=>{const phone=sessionPhone(req);if(!phone)return res.status(401).json({error:'Authentication required'});const id=Number.parseInt(String(req.body?.escrow_id||''),10);if(!Number.isInteger(id))return res.status(400).json({error:'escrow_id is required'});try{const parties=await getEscrowParties(id);if(!parties)return res.status(404).json({error:'Escrow not found'});if(parties.buyer!==phone&&parties.provider!==phone)return res.status(403).json({error:'Forbidden: escrow party required'});const success=await refundEscrow(id);res.json({success,message:success?'Escrow refunded to buyer.':'Escrow is not eligible for refund.'});}catch{res.status(500).json({error:'Failed to refund escrow'});}});
export default router;
