import { getCanonicalStore } from './canonicalStore.js';

const limits=()=>({perGoalTokens:Math.max(100,Number(process.env.KURUKOO_AGENT_PER_GOAL_TOKEN_BUDGET||2_000)),perCycleTokens:Math.max(100,Number(process.env.KURUKOO_AGENT_PER_CYCLE_TOKEN_BUDGET||800)),maxHostedEscalations:Math.max(0,Number(process.env.KURUKOO_AGENT_MAX_HOSTED_ESCALATIONS_PER_DAY||3)),cooldownSeconds:Math.max(30,Number(process.env.KURUKOO_AGENT_BUDGET_COOLDOWN_SECONDS||900))});
const day=()=>new Date().toISOString().slice(0,10),cycle=()=>new Date().toISOString().slice(0,16);
async function ensureSchema(){const db=await getCanonicalStore(),pg=db.mode==='postgres';await db.run(`CREATE TABLE IF NOT EXISTS agent_inference_budget_usage(agent_id TEXT NOT NULL,goal_id TEXT NOT NULL,day TEXT NOT NULL,cycle_bucket TEXT NOT NULL,goal_tokens INTEGER NOT NULL DEFAULT 0,cycle_tokens INTEGER NOT NULL DEFAULT 0,hosted_escalations INTEGER NOT NULL DEFAULT 0,cooldown_until ${pg?'TIMESTAMPTZ':'TEXT'},updated_at ${pg?'TIMESTAMPTZ':'TEXT'} DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(agent_id,goal_id,day,cycle_bucket))`);await db.run('CREATE INDEX IF NOT EXISTS idx_agent_inference_budget_cooldown ON agent_inference_budget_usage(agent_id,cooldown_until)');return db;}
export interface AgentInferenceBudgetDecision{allowed:boolean;forceLocal:boolean;reason?:string;limits:ReturnType<typeof limits>;}
export async function checkAgentInferenceBudget(input:{agentId:string;goalId?:string;estimatedTokens:number}):Promise<AgentInferenceBudgetDecision>{const db=await ensureSchema(),config=limits(),goalId=input.goalId||'ad_hoc',row=await db.one<any>(`SELECT SUM(goal_tokens) AS goal_tokens,SUM(CASE WHEN cycle_bucket=? THEN cycle_tokens ELSE 0 END) AS cycle_tokens,SUM(hosted_escalations) AS hosted_escalations,MAX(cooldown_until) AS cooldown_until FROM agent_inference_budget_usage WHERE agent_id=? AND goal_id=? AND day=?`,[cycle(),input.agentId,goalId,day()]);const goalTokens=Number(row?.goal_tokens||0),cycleTokens=Number(row?.cycle_tokens||0),hostedEscalations=Number(row?.hosted_escalations||0),cooldownUntil=row?.cooldown_until?Date.parse(String(row.cooldown_until)):0;if(cooldownUntil>Date.now())return{allowed:false,forceLocal:true,reason:'Agent inference budget is cooling down after exhaustion.',limits:config};if(goalTokens+input.estimatedTokens>config.perGoalTokens)return{allowed:false,forceLocal:true,reason:'Per-goal inference budget reached; the goal will wait for its cooldown.',limits:config};if(cycleTokens+input.estimatedTokens>config.perCycleTokens)return{allowed:false,forceLocal:true,reason:'Per-cycle inference budget reached; the agent will retry after cooldown.',limits:config};return{allowed:true,forceLocal:hostedEscalations>=config.maxHostedEscalations,reason:hostedEscalations>=config.maxHostedEscalations?'Hosted escalation limit reached; using bounded local inference.':undefined,limits:config};}
export async function recordAgentInferenceBudget(input:{agentId:string;goalId?:string;tokens:number;usedHosted:boolean;exhaust?:boolean}):Promise<void>{const db=await ensureSchema(),goalId=input.goalId||'ad_hoc',config=limits(),cooldown=input.exhaust?new Date(Date.now()+config.cooldownSeconds*1000).toISOString():null;await db.run(`INSERT INTO agent_inference_budget_usage(agent_id,goal_id,day,cycle_bucket,goal_tokens,cycle_tokens,hosted_escalations,cooldown_until) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(agent_id,goal_id,day,cycle_bucket) DO UPDATE SET goal_tokens=goal_tokens+excluded.goal_tokens,cycle_tokens=cycle_tokens+excluded.cycle_tokens,hosted_escalations=hosted_escalations+excluded.hosted_escalations,cooldown_until=COALESCE(excluded.cooldown_until,cooldown_until),updated_at=CURRENT_TIMESTAMP`,[input.agentId,goalId,day(),cycle(),Math.max(0,Math.floor(input.tokens)),Math.max(0,Math.floor(input.tokens)),input.usedHosted?1:0,cooldown]);}
export async function getAgentInferenceBudgetStatus(agentId:string,goalId?:string){const db=await ensureSchema();const rows=await db.all<any>(`SELECT goal_id,SUM(goal_tokens) AS goal_tokens,SUM(hosted_escalations) AS hosted_escalations,MAX(cooldown_until) AS cooldown_until FROM agent_inference_budget_usage WHERE agent_id=? AND day()=? ${goalId?'AND goal_id=?':''} GROUP BY goal_id`,goalId?[agentId,day(),goalId]:[agentId,day()]);return{limits:limits(),day:day(),goals:rows.map((row:any)=>({goalId:row.goal_id,tokensUsed:Number(row.goal_tokens||0),hostedEscalations:Number(row.hosted_escalations||0),cooldownUntil:row.cooldown_until||null}))};}
