/** Hard AI quotas — durable shared state owned by kurukoo-persistence. */
import { getCanonicalStore } from './canonicalStore.js';
import { getCanonicalPersistenceMode } from './canonicalPersistence.js';
export type QuotaKind='simple'|'complex'|'embedding';
const DEFAULTS={maxSimpleRequests:Number(process.env.AI_QUOTA_SIMPLE_PER_DAY||80),maxComplexRequests:Number(process.env.AI_QUOTA_COMPLEX_PER_DAY||25),maxTokensPerDay:Number(process.env.AI_QUOTA_TOKENS_PER_DAY||80000),globalComplexPerMinute:Number(process.env.AI_QUOTA_GLOBAL_COMPLEX_PER_MIN||120),hardBlockWhenExceeded:process.env.AI_QUOTA_HARD_BLOCK!=='false'};
async function ensureQuotaTables(){const s=await getCanonicalStore();await s.run(`CREATE TABLE IF NOT EXISTS ai_usage_daily(phone TEXT NOT NULL,day TEXT NOT NULL,simple_requests INTEGER DEFAULT 0,complex_requests INTEGER DEFAULT 0,tokens_est INTEGER DEFAULT 0,PRIMARY KEY(phone,day))`);await s.run(`CREATE TABLE IF NOT EXISTS ai_usage_minute(bucket TEXT PRIMARY KEY,complex_count INTEGER DEFAULT 0)`);return s;}
function utcDay(){return new Date().toISOString().slice(0,10);}function minuteBucket(){return new Date().toISOString().slice(0,16);}
export interface QuotaDecision{allowed:boolean;reason?:string;remaining:{simple:number;complex:number;tokens:number};downgradeToTemplate?:boolean;}
export async function checkAiQuota(phone:string|undefined,kind:QuotaKind,estimatedTokens=500):Promise<QuotaDecision>{if(!phone)return{allowed:true,remaining:{simple:DEFAULTS.maxSimpleRequests,complex:DEFAULTS.maxComplexRequests,tokens:DEFAULTS.maxTokensPerDay}};const s=await ensureQuotaTables();const row=await s.one<any>('SELECT simple_requests,complex_requests,tokens_est FROM ai_usage_daily WHERE phone=? AND day=?',[phone,utcDay()]);const simple=Number(row?.simple_requests||0),complex=Number(row?.complex_requests||0),tokens=Number(row?.tokens_est||0);const remaining={simple:Math.max(0,DEFAULTS.maxSimpleRequests-simple),complex:Math.max(0,DEFAULTS.maxComplexRequests-complex),tokens:Math.max(0,DEFAULTS.maxTokensPerDay-tokens)};if(tokens+estimatedTokens>DEFAULTS.maxTokensPerDay)return{allowed:!DEFAULTS.hardBlockWhenExceeded,reason:'Daily AI token budget reached',remaining,downgradeToTemplate:true};if(kind==='simple'&&simple>=DEFAULTS.maxSimpleRequests)return{allowed:!DEFAULTS.hardBlockWhenExceeded,reason:'Daily simple AI request quota reached',remaining,downgradeToTemplate:true};if(kind==='complex'&&complex>=DEFAULTS.maxComplexRequests)return{allowed:!DEFAULTS.hardBlockWhenExceeded,reason:'Daily complex AI request quota reached',remaining,downgradeToTemplate:true};if(kind==='complex'){const global=await s.one<any>('SELECT complex_count FROM ai_usage_minute WHERE bucket=?',[minuteBucket()]);if(Number(global?.complex_count||0)>=DEFAULTS.globalComplexPerMinute)return{allowed:false,reason:'Platform AI rate limit — try again shortly',remaining,downgradeToTemplate:true};}return{allowed:true,remaining};}
export async function recordAiUsage(phone:string|undefined,kind:QuotaKind,estimatedTokens=500){if(!phone)return;const s=await ensureQuotaTables();const d=utcDay(),simple=kind==='simple'?1:0,complex=kind==='complex'?1:0,tokens=Math.max(0,Math.round(estimatedTokens));await s.run(`INSERT INTO ai_usage_daily(phone,day,simple_requests,complex_requests,tokens_est) VALUES(?,?,?,?,?) ON CONFLICT(phone,day) DO UPDATE SET simple_requests=ai_usage_daily.simple_requests+excluded.simple_requests,complex_requests=ai_usage_daily.complex_requests+excluded.complex_requests,tokens_est=ai_usage_daily.tokens_est+excluded.tokens_est`,[phone,d,simple,complex,tokens]);if(kind==='complex')await s.run(`INSERT INTO ai_usage_minute(bucket,complex_count) VALUES(?,1) ON CONFLICT(bucket) DO UPDATE SET complex_count=ai_usage_minute.complex_count+1`,[minuteBucket()]);}
export async function getAiQuotaStatus(phone:string){const decision=await checkAiQuota(phone,'simple',0);return{...decision.remaining,day:utcDay()};}
