import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { getCanonicalStore } from './canonicalStore.js';

function attachmentDir(){const configured=String(process.env.CHAT_UPLOAD_DIR||'').trim();const fallback=path.join(process.cwd(),'storage','chat');if(!configured)return fallback;const resolved=path.resolve(configured),publicRoot=path.resolve(process.cwd(),'public');return resolved===publicRoot||resolved.startsWith(`${publicRoot}${path.sep}`)?fallback:resolved;}
const safeName=(name:string)=>(name.replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,160)||'attachment');
async function ensureSchema(){const db=await getCanonicalStore();await db.run(`CREATE TABLE IF NOT EXISTS chat_attachments(id TEXT PRIMARY KEY,phone TEXT NOT NULL,stored_path TEXT NOT NULL,original_name TEXT NOT NULL,mime_type TEXT NOT NULL,size_bytes INTEGER NOT NULL,sha256 TEXT NOT NULL,message_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP,expires_at TEXT NOT NULL)`);await db.run('CREATE INDEX IF NOT EXISTS idx_chat_attachments_owner_expiry ON chat_attachments(phone,expires_at)');return db;}
async function cleanupExpired(db:any){const rows=await db.all('SELECT id,stored_path FROM chat_attachments WHERE expires_at <= ?',[new Date().toISOString()]);for(const row of rows){await fs.unlink(String(row.stored_path)).catch(()=>undefined);await db.run('DELETE FROM chat_attachments WHERE id=?',[String(row.id)]);}}
export async function createChatAttachment(input:{phone:string;name:string;type:string;data:Buffer}){const phone=String(input.phone||'').trim();if(!phone)throw new Error('Authenticated phone is required');const allowed=new Set(['image/jpeg','image/png','image/webp','image/gif','application/pdf','text/plain','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','video/mp4','video/webm']);if(!allowed.has(input.type))throw new Error('Unsupported attachment type');const limit=input.type.startsWith('video/')?25*1024*1024:10*1024*1024;if(!input.data.length||input.data.length>limit)throw new Error(`Attachment exceeds ${Math.floor(limit/1024/1024)}MB limit`);const db=await ensureSchema();await cleanupExpired(db);const id=crypto.randomUUID(),name=safeName(input.name),ext=path.extname(name).toLowerCase().replace(/[^a-z0-9.]/g,'').slice(0,8)||'.bin',dir=attachmentDir(),storedPath=path.join(dir,`${id}${ext}`),sha256=crypto.createHash('sha256').update(input.data).digest('hex');await fs.mkdir(dir,{recursive:true});await fs.writeFile(storedPath,input.data,{flag:'wx'});await db.run(`INSERT INTO chat_attachments(id,phone,stored_path,original_name,mime_type,size_bytes,sha256,expires_at) VALUES(?,?,?,?,?,?,?,?)`,[id,phone,storedPath,name,input.type,input.data.byteLength,sha256,new Date(Date.now()+30*86400000).toISOString()]);return{id,name,type:input.type,size:input.data.byteLength};}
export async function getChatAttachment(phone:string,id:string){const db=await ensureSchema();await cleanupExpired(db);return db.one<any>('SELECT stored_path,original_name,mime_type,size_bytes FROM chat_attachments WHERE id=? AND phone=? AND expires_at>? LIMIT 1',[id,phone,new Date().toISOString()]);}
export async function deleteChatAttachment(phone:string,id:string){const db=await ensureSchema(),row=await db.one<any>('SELECT stored_path FROM chat_attachments WHERE id=? AND phone=? LIMIT 1',[id,phone]);if(!row)return false;await fs.unlink(String(row.stored_path)).catch(()=>undefined);await db.run('DELETE FROM chat_attachments WHERE id=? AND phone=?',[id,phone]);return true;}
export function resolveChatAttachmentPath(value:string){const resolved=path.resolve(value),root=path.resolve(attachmentDir());return resolved.startsWith(root+path.sep)?resolved:null;}
