import { getCanonicalPersistenceMode } from './canonicalPersistence.js';
import { getCanonicalStore } from './canonicalStore.js';

export class CommissionConfigurationError extends Error{constructor(type:string){super(`No active commission configuration exists for ${type}.`);this.name='CommissionConfigurationError';}}

export async function ensureCommissionSchema(){
  const store=await getCanonicalStore();
  await store.run(getCanonicalPersistenceMode()==='postgres'
    ? `CREATE TABLE IF NOT EXISTS commission_config(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,type TEXT NOT NULL UNIQUE,rate_minor BIGINT NOT NULL DEFAULT 0,description TEXT NOT NULL DEFAULT '',active BOOLEAN NOT NULL DEFAULT TRUE,updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP)`
    : `CREATE TABLE IF NOT EXISTS commission_config(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT NOT NULL UNIQUE,rate_minor INTEGER NOT NULL DEFAULT 0,description TEXT NOT NULL DEFAULT '',active INTEGER NOT NULL DEFAULT 1,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
  await store.run('CREATE INDEX IF NOT EXISTS idx_commission_config_type_active ON commission_config(type,active)');
  return store;
}

function isActive(value:unknown):boolean{return value===true||value===1||value==='1'||value==='t'||value==='true';}
export async function getAllCommissions(){return(await ensureCommissionSchema()).all('SELECT id,type,rate_minor,description,active FROM commission_config');}
export async function getCommission(type:string){const row=await(await ensureCommissionSchema()).one<any>('SELECT rate_minor,active FROM commission_config WHERE type=?',[type]);if(!row||!isActive(row.active))throw new CommissionConfigurationError(type);const rate=Number(row.rate_minor);if(!Number.isFinite(rate)||rate<0)throw new CommissionConfigurationError(type);return rate;}
export async function calculateCommission(type:string,amount=0){const rate=await getCommission(type);return type==='agent_topup'&&rate<=100&&amount>0?Math.round(amount*(rate/100)):rate;}
export async function updateCommission(id:number,rate_minor:number,active:number=1){const activeValue=getCanonicalPersistenceMode()==='postgres'?Boolean(active):active?1:0;await(await ensureCommissionSchema()).run('UPDATE commission_config SET rate_minor=?,active=? WHERE id=?',[rate_minor,activeValue,id]);return true;}
