import crypto from 'node:crypto';
import { getCanonicalStore } from './canonicalStore.js';
import { getCanonicalPersistenceMode } from './canonicalPersistence.js';
import { sendMqttCommand } from './iotBridge.js';

export type ConnectedResourceKind = 'phone' | 'tv' | 'cctv' | 'camera' | 'laptop' | 'desktop' | 'tablet' | 'vehicle' | 'iot' | 'other';
export type ConnectedResourceProtocol = 'mqtt' | 'stream' | 'webrtc' | 'http' | 'custom';
export interface ConnectedResource { id:string; phone:string; kind:ConnectedResourceKind; label:string; vendor?:string; protocol:ConnectedResourceProtocol; capabilities:string[]; metadata:Record<string, unknown>; viewUrl?:string; streamUrl?:string; status:'active'|'pending'|'revoked'; createdAt:string; lastSeenAt:string; }
export interface ConnectedResourceChallenge { id:string; resourceId:string; code:string; expiresAt:string; }

async function ensureSchema():Promise<Awaited<ReturnType<typeof getCanonicalStore>>>{
  const store=await getCanonicalStore();
  const pg=getCanonicalPersistenceMode()==='postgres';
  await store.run(`CREATE TABLE IF NOT EXISTS connected_resources(id TEXT PRIMARY KEY,phone TEXT NOT NULL,kind TEXT NOT NULL,label TEXT NOT NULL,vendor TEXT,protocol TEXT NOT NULL,capabilities_json TEXT NOT NULL DEFAULT '[]',metadata_json TEXT NOT NULL DEFAULT '{}',view_url TEXT,stream_url TEXT,status TEXT NOT NULL DEFAULT 'pending',created_at ${pg?'TIMESTAMPTZ':'TEXT'} DEFAULT CURRENT_TIMESTAMP,last_seen_at ${pg?'TIMESTAMPTZ':'TEXT'} DEFAULT CURRENT_TIMESTAMP,revoked_at ${pg?'TIMESTAMPTZ':'TEXT'})`);
  await store.run(`CREATE INDEX IF NOT EXISTS idx_connected_resources_phone_status ON connected_resources(phone,status,last_seen_at)`);
  await store.run(`CREATE INDEX IF NOT EXISTS idx_connected_resources_phone_label ON connected_resources(phone,label,status)`);
  await store.run(`CREATE TABLE IF NOT EXISTS connected_resource_challenges(id TEXT PRIMARY KEY,resource_id TEXT NOT NULL,phone TEXT NOT NULL,code_hash TEXT NOT NULL,expires_at ${pg?'TIMESTAMPTZ':'TEXT'} NOT NULL,consumed_at ${pg?'TIMESTAMPTZ':'TEXT'},created_at ${pg?'TIMESTAMPTZ':'TEXT'} DEFAULT CURRENT_TIMESTAMP)`);
  await store.run(`CREATE INDEX IF NOT EXISTS idx_connected_resource_challenges_resource ON connected_resource_challenges(resource_id,phone,consumed_at,expires_at)`);
  await store.run(`CREATE TABLE IF NOT EXISTS connected_resource_commands(id TEXT PRIMARY KEY,resource_id TEXT NOT NULL,phone TEXT NOT NULL,idempotency_key TEXT NOT NULL,command TEXT NOT NULL,payload TEXT,topic TEXT,state TEXT NOT NULL,accepted INTEGER NOT NULL DEFAULT 0,reason TEXT,created_at ${pg?'TIMESTAMPTZ':'TEXT'} DEFAULT CURRENT_TIMESTAMP,updated_at ${pg?'TIMESTAMPTZ':'TEXT'} DEFAULT CURRENT_TIMESTAMP,UNIQUE(phone,resource_id,idempotency_key))`);
  await store.run(`CREATE INDEX IF NOT EXISTS idx_connected_resource_commands_resource ON connected_resource_commands(phone,resource_id,created_at)`);
  return store;
}
function safeJson(value:unknown,fallback:unknown):unknown{try{return typeof value==='string'?JSON.parse(value):value??fallback;}catch{return fallback;}}
function rowToResource(row:any):ConnectedResource{const parsedCapabilities=safeJson(row.capabilities_json,[]),parsedMetadata=safeJson(row.metadata_json,{});return{id:String(row.id),phone:String(row.phone),kind:String(row.kind) as ConnectedResourceKind,label:String(row.label),vendor:row.vendor?String(row.vendor):undefined,protocol:String(row.protocol) as ConnectedResourceProtocol,capabilities:Array.isArray(parsedCapabilities)?parsedCapabilities.map(String):[],metadata:parsedMetadata&&typeof parsedMetadata==='object'?parsedMetadata as Record<string,unknown>:{},viewUrl:row.view_url?String(row.view_url):undefined,streamUrl:row.stream_url?String(row.stream_url):undefined,status:String(row.status||'pending') as ConnectedResource['status'],createdAt:String(row.created_at||''),lastSeenAt:String(row.last_seen_at||'')};}
function hashChallenge(code:string):string{return crypto.createHash('sha256').update(code).digest('hex');}
function makePairingCode():string{return String(crypto.randomInt(100000,999999));}

export async function registerConnectedResource(input:{phone:string;kind:ConnectedResourceKind;label:string;vendor?:string;protocol?:ConnectedResourceProtocol;capabilities?:string[];metadata?:Record<string,unknown>;viewUrl?:string;streamUrl?:string;}):Promise<{resource:ConnectedResource;challenge:ConnectedResourceChallenge}>{const store=await ensureSchema(),phone=String(input.phone||'').trim(),id=`conn_${crypto.randomUUID()}`,capabilities=[...new Set((input.capabilities||[]).map(item=>String(item).trim()).filter(Boolean))].slice(0,64),metadata=input.metadata||{};await store.transaction(async tx=>{await tx.run(`INSERT INTO connected_resources(id,phone,kind,label,vendor,protocol,capabilities_json,metadata_json,view_url,stream_url,status) VALUES(?,?,?,?,?,?,?,?,?,?, 'pending')`,[id,phone,input.kind,String(input.label||'').slice(0,160),String(input.vendor||'').slice(0,120)||null,input.protocol||'custom',JSON.stringify(capabilities),JSON.stringify(metadata),String(input.viewUrl||'').slice(0,2048)||null,String(input.streamUrl||'').slice(0,2048)||null]);});const challenge=await issueConnectedResourceChallenge(phone,id),resource=await getConnectedResource(phone,id);if(!resource)throw new Error('Connected resource could not be persisted.');return{resource,challenge};}
export async function issueConnectedResourceChallenge(phone:string,resourceId:string,ttlSeconds=600):Promise<ConnectedResourceChallenge>{const store=await ensureSchema(),resource=await getConnectedResource(phone,resourceId);if(!resource||resource.status==='revoked')throw new Error('Connected resource not found.');const id=`crch_${crypto.randomUUID()}`,code=makePairingCode(),expiresAt=new Date(Date.now()+Math.max(60,Math.min(ttlSeconds,1800))*1000).toISOString();await store.transaction(async tx=>{await tx.run('UPDATE connected_resource_challenges SET consumed_at=CURRENT_TIMESTAMP WHERE resource_id=? AND phone=? AND consumed_at IS NULL',[resourceId,String(phone||'').trim()]);await tx.run('INSERT INTO connected_resource_challenges(id,resource_id,phone,code_hash,expires_at) VALUES(?,?,?,?,?)',[id,resourceId,String(phone||'').trim(),hashChallenge(code),expiresAt]);});return{id,resourceId,code,expiresAt};}
export async function activateConnectedResource(phone:string,resourceId:string,code:string):Promise<ConnectedResource|null>{const store=await ensureSchema(),normalizedPhone=String(phone||'').trim(),normalizedCode=String(code||'').trim(),resource=await getConnectedResource(normalizedPhone,resourceId);if(!resource||resource.status==='revoked')return null;const codeHash=hashChallenge(normalizedCode);if(resource.status==='active'){const replay=await store.one<any>(`SELECT id FROM connected_resource_challenges WHERE resource_id=? AND phone=? AND code_hash=? AND consumed_at IS NOT NULL ORDER BY created_at DESC LIMIT 1`,[resourceId,normalizedPhone,codeHash]);return replay?resource:null;}const row=await store.one<any>(`SELECT id,expires_at FROM connected_resource_challenges WHERE resource_id=? AND phone=? AND code_hash=? AND consumed_at IS NULL ORDER BY created_at DESC LIMIT 1`,[resourceId,normalizedPhone,codeHash]);if(!row||new Date(String(row.expires_at)).getTime()<=Date.now())return null;await store.transaction(async tx=>{await tx.run('UPDATE connected_resource_challenges SET consumed_at=CURRENT_TIMESTAMP WHERE id=?',[String(row.id)]);await tx.run(`UPDATE connected_resources SET status='active',last_seen_at=CURRENT_TIMESTAMP WHERE id=? AND phone=? AND status='pending'`,[resourceId,normalizedPhone]);});return getConnectedResource(normalizedPhone,resourceId);}
export async function listConnectedResources(phone:string):Promise<ConnectedResource[]>{const store=await ensureSchema(),rows=await store.all<any>(`SELECT id,phone,kind,label,vendor,protocol,capabilities_json,metadata_json,view_url,stream_url,status,created_at,last_seen_at FROM connected_resources WHERE phone=? AND status!='revoked' ORDER BY last_seen_at DESC`,[String(phone||'').trim()]);return rows.map(rowToResource);}
export async function getConnectedResource(phone:string,id:string):Promise<ConnectedResource|null>{const store=await ensureSchema(),row=await store.one<any>(`SELECT id,phone,kind,label,vendor,protocol,capabilities_json,metadata_json,view_url,stream_url,status,created_at,last_seen_at FROM connected_resources WHERE id=? AND phone=? LIMIT 1`,[id,String(phone||'').trim()]);return row?rowToResource(row):null;}
export async function resolveConnectedResource(input:{phone:string;id?:string;label?:string;kind?:ConnectedResourceKind}):Promise<{resource:ConnectedResource}|{ambiguous:ConnectedResource[]}|null>{await ensureSchema();if(input.id){const resource=await getConnectedResource(input.phone,input.id);return resource?.status==='active'?{resource}:null;}const label=String(input.label||'').trim().toLowerCase();if(!label)return null;const resources=(await listConnectedResources(input.phone)).filter(resource=>resource.status==='active'),exact=resources.filter(resource=>resource.label.toLowerCase()===label&&(!input.kind||resource.kind===input.kind));if(exact.length===1)return{resource:exact[0]};if(exact.length>1)return{ambiguous:exact};const partial=resources.filter(resource=>resource.label.toLowerCase().includes(label)&&(!input.kind||resource.kind===input.kind));if(partial.length===1)return{resource:partial[0]};if(partial.length>1)return{ambiguous:partial.slice(0,5)};return null;}
export async function buildConnectedResourceContext(phone?:string):Promise<string>{if(!phone||phone.startsWith('anon_'))return '';const resources=(await listConnectedResources(phone)).filter(resource=>resource.status==='active');if(!resources.length)return '';return resources.slice(0,24).map(resource=>{const caps=resource.capabilities.length?resource.capabilities.join(', '):'no controls declared';const views=resource.viewUrl||resource.streamUrl?'live/view media available':'no view media exposed';const state=resource.metadata.lastState!==undefined?`; last device state at ${String(resource.metadata.lastStateAt||resource.lastSeenAt)}: ${typeof resource.metadata.lastState==='string'?resource.metadata.lastState:JSON.stringify(resource.metadata.lastState)}`:'';return `- ${resource.label} (${resource.kind}${resource.vendor?`, ${resource.vendor}`:''}, internal_id=${resource.id}): ${caps}; ${views}${state}`;}).join('\n');}
export async function markConnectedResourceSeen(phone:string,id:string):Promise<void>{const store=await ensureSchema();await store.run(`UPDATE connected_resources SET last_seen_at=CURRENT_TIMESTAMP WHERE id=? AND phone=? AND status='active'`,[id,String(phone||'').trim()]);}
export async function revokeConnectedResource(phone:string,id:string):Promise<boolean>{const store=await ensureSchema();const changed=(await store.run(`UPDATE connected_resources SET status='revoked',revoked_at=CURRENT_TIMESTAMP WHERE id=? AND phone=? AND status!='revoked'`,[id,String(phone||'').trim()])).rowCount>0;return changed;}
export async function viewConnectedResource(phone:string,id:string):Promise<{resource:ConnectedResource;media:Array<{kind:'image'|'video'|'stream';url:string}>}|null>{const resource=await getConnectedResource(phone,id);if(!resource||resource.status!=='active')return null;await markConnectedResourceSeen(phone,id);const media:Array<{kind:'image'|'video'|'stream';url:string}>=[];if(resource.viewUrl)media.push({kind:'image',url:resource.viewUrl});if(resource.streamUrl)media.push({kind:'stream',url:resource.streamUrl});return{resource,media};}
export function connectedResourceSupports(resource:ConnectedResource,action:string):boolean{const normalized=String(action||'').trim().toLowerCase();if(!normalized)return false;if(['view','inspect','show'].includes(normalized))return Boolean(resource.viewUrl||resource.streamUrl||resource.capabilities.includes('view')||resource.capabilities.includes('observe'));if(['control','execute'].includes(normalized))return resource.capabilities.includes('control')||resource.capabilities.includes('execute');return resource.capabilities.includes(normalized);}
export async function controlConnectedResource(input:{phone:string;id:string;command:string;payload?:string;idempotencyKey?:string}):Promise<{resource:ConnectedResource;accepted:boolean;state:string;reason?:string;commandId?:string}>{const store=await ensureSchema(),resource=await getConnectedResource(input.phone,input.id);if(!resource)throw new Error('Connected resource not found for this user.');const normalizedPhone=String(input.phone||'').trim(),normalizedCommand=String(input.command||'').trim().toLowerCase(),normalizedKey=String(input.idempotencyKey||`control:${input.id}:${normalizedCommand}:${crypto.createHash('sha256').update(String(input.payload??'')).digest('hex').slice(0,16)}`).slice(0,180),prior=await store.one<any>('SELECT id,accepted,state,reason FROM connected_resource_commands WHERE phone=? AND resource_id=? AND idempotency_key=? LIMIT 1',[normalizedPhone,input.id,normalizedKey]);if(prior)return{resource,accepted:Boolean(Number(prior.accepted)),state:String(prior.state),reason:prior.reason?String(prior.reason):undefined,commandId:String(prior.id)};let state='activation_required',accepted=false,reason:string|undefined;if(resource.status!=='active')reason='This connected resource is not activated for control yet.';else if(!connectedResourceSupports(resource,normalizedCommand)){state='blocked';reason='This connected resource has not exposed that capability.';}else if(resource.protocol!=='mqtt')reason=`The ${resource.protocol} control adapter is not activated in this deployment.`;else{const baseTopic=String(resource.metadata.baseTopic||'').trim();if(!baseTopic){state='not_configured';reason='This resource has no authorized MQTT base topic.';}else{const result=sendMqttCommand(`${baseTopic.replace(/\/$/,'')}/${normalizedCommand}`,String(input.payload??''));accepted=result.accepted;state=result.state;reason=result.reason;}}const commandId=`cmd_${crypto.randomUUID()}`;await store.transaction(async tx=>{const replay=await tx.one<any>('SELECT id,accepted,state,reason FROM connected_resource_commands WHERE phone=? AND resource_id=? AND idempotency_key=? LIMIT 1',[normalizedPhone,input.id,normalizedKey]);if(replay)return;await tx.run('INSERT INTO connected_resource_commands(id,resource_id,phone,idempotency_key,command,payload,topic,state,accepted,reason) VALUES(?,?,?,?,?,?,?,?,?,?)',[commandId,input.id,normalizedPhone,normalizedKey,normalizedCommand,String(input.payload??''),String(resource.metadata.baseTopic||'').trim(),state,accepted?1:0,reason||null]);});if(accepted)await markConnectedResourceSeen(normalizedPhone,input.id);return{resource,accepted,state,reason,commandId};}
