import fs from 'fs';
import path from 'path';
import { getCanonicalPersistenceMode } from './canonicalPersistence.js';
import { getCanonicalStore } from './canonicalStore.js';
export interface ContentItem{slug:string;title:string;body:string;type:'blog'|'help'|'legal'|'page'|'resource';author:string;category?:string;excerpt?:string;createdAt?:string;updatedAt?:string;}
export interface BlogArticle{slug:string;title:string;date:string;author:string;category:string;content:string;}
export interface BlogMetadata{slug:string;title:string;date:string;author:string;category:string;}
export interface ResourceMetadata{slug:string;title:string;category:string;excerpt:string;updated_at?:string;}
const RESOURCE_SEEDS:ReadonlyArray<Omit<ContentItem,'createdAt'|'updatedAt'>>=[
{slug:'how-kurukoo-works',title:'How Kurukoo works',category:'For everyone',excerpt:'Understand the conversation-first path from what you need to a coordinated outcome.',body:'# How Kurukoo works\n\nKurukoo starts with the need, not a category. Tell Kurukoo what you need, and it works through the relevant memory, capability, request, provider or authorised integration.\n\n## What Kurukoo can establish\n\nKurukoo can only claim an action, provider state, payment, fulfilment or outcome when its canonical services or authorised external evidence establish it.\n\n## Continue in Chat\n\nMost operational journeys continue in the same conversation so interruptions, authentication, reminders and follow-up do not create a second relationship.',type:'resource',author:'Kurukoo'},
{slug:'reminders-and-routines',title:'Reminders and routines',category:'For everyone',excerpt:'Use Kurukoo to remember, schedule and continue everyday intentions.',body:'# Reminders and routines\n\nAsk Kurukoo to remind you once, on a schedule, or after a relevant event. Reminder state belongs to the same identity and conversation context.',type:'resource',author:'Kurukoo'},
{slug:'provider-and-capability-guides',title:'Provider and capability guides',category:'For providers',excerpt:'Understand capability, presence, trust and how a provider participates without creating a second identity.',body:'# Provider and capability guides\n\nA Kurukoo user can hold several capabilities at once: provider, contributor, buyer, seller, delivery worker and more.',type:'resource',author:'Kurukoo'},
{slug:'staying-safe-and-resolving-disputes',title:'Staying safe and resolving disputes',category:'Trust & safety',excerpt:'Learn how verification, evidence, cancellation, recovery and reporting work.',body:'# Staying safe and resolving disputes\n\nSafety, disputes and sensitive actions use explicit policy and evidence boundaries.',type:'resource',author:'Kurukoo'},
{slug:'memory-and-connected-context',title:'Memory and connected context',category:'For everyone',excerpt:'Learn what Kurukoo can remember, where connected data lives, and how to manage it.',body:'# Memory and connected context\n\nMemory Profile is the canonical owner-scoped memory authority.',type:'resource',author:'Kurukoo'},
{slug:'contributors-and-tasks',title:'Contributors and tasks',category:'For contributors',excerpt:'Learn how tasks, evidence and contribution activity connect to the same identity and agent runtime.',body:'# Contributors and tasks\n\nContributor work appears through the canonical capability and task systems.',type:'resource',author:'Kurukoo'},
{slug:'channels-and-connected-doors',title:'Channels and connected doors',category:'Channels',excerpt:'Web, PWA, WhatsApp, Telegram, notifications and other channels are doors into one Kurukoo relationship.',body:'# Channels and connected doors\n\nKurukoo treats channels as doors into one relationship rather than separate products.',type:'resource',author:'Kurukoo'},
{slug:'points-plans-and-payments',title:'Points, plans and payments',category:'Economy',excerpt:'Understand the distinction between Points, plans, top-up and external payment evidence.',body:'# Points, plans and payments\n\nPoints are not cash. Subscriptions and top-up use their own payment and entitlement boundaries.',type:'resource',author:'Kurukoo'}
];
const toContent=(row:any):ContentItem=>({slug:String(row.slug),title:String(row.title),body:String(row.body||''),type:row.type,author:String(row.author||''),createdAt:row.created_at?String(row.created_at):undefined,updatedAt:row.updated_at?String(row.updated_at):undefined});
export async function ensureContentSchema(){const db=await getCanonicalStore();await db.run(getCanonicalPersistenceMode()==='postgres'?`CREATE TABLE IF NOT EXISTS content(slug TEXT PRIMARY KEY,title TEXT NOT NULL,body TEXT NOT NULL,type TEXT NOT NULL,author TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP)`,`CREATE TABLE IF NOT EXISTS content(slug TEXT PRIMARY KEY,title TEXT NOT NULL,body TEXT NOT NULL,type TEXT NOT NULL,author TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`);await db.run('CREATE INDEX IF NOT EXISTS idx_content_type_updated ON content(type,updated_at DESC)');return db;}
export async function ensureResourceSeeded(){const db=await ensureContentSchema();const count=await db.one<any>(`SELECT COUNT(*) AS count FROM content WHERE type='resource'`);if(Number(count?.count||0)>0)return;for(const resource of RESOURCE_SEEDS)await db.run(`INSERT INTO content(slug,title,body,type,author) VALUES(?,?,?,'resource',?) ON CONFLICT(slug) DO NOTHING`,[resource.slug,resource.title,resource.body,resource.author]);}
export function convertMarkdownToHtml(markdown:string){const lines=markdown.split('\n');let html='',inList=false;for(let line of lines){line=line.trim();if(!line){if(inList){html+='</ul>\n';inList=false;}continue;}if(line.startsWith('# ')){if(inList){html+='</ul>\n';inList=false;}html+=`<h1>${line.slice(2)}</h1>\n`;}else if(line.startsWith('## ')){if(inList){html+='</ul>\n';inList=false;}html+=`<h2>${line.slice(3)}</h2>\n`;}else if(line.startsWith('### ')){if(inList){html+='</ul>\n';inList=false;}html+=`<h3>${line.slice(4)}</h3>\n`;}else if(line.startsWith('- ')){if(!inList){html+='<ul>\n';inList=true;}html+=`  <li>${line.slice(2).replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>')}</li>\n`;}else{if(inList){html+='</ul>\n';inList=false;}html+=`<p>${line.replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>')}</p>\n`;}}if(inList)html+='</ul>\n';return html;}
export async function getAllContent(type?:string){const db=await ensureContentSchema(),params:any[]=[];let query='SELECT slug,title,body,type,author,created_at,updated_at FROM content';if(type){query+=' WHERE type=?';params.push(type);}return(await db.all<any>(query,params)).map(toContent);}
export async function getContentBySlug(slug:string){const db=await ensureContentSchema();const row=await db.one<any>('SELECT slug,title,body,type,author,created_at,updated_at FROM content WHERE slug=?',[slug]);return row?toContent(row):null;}
export async function getAllResourceMetadata(page=1,pageSize=20){await ensureResourceSeeded();const db=await ensureContentSchema(),safePage=Math.max(1,Math.floor(page)),safeSize=Math.min(20,Math.max(1,Math.floor(pageSize))),offset=(safePage-1)*safeSize,rows=await db.all<any>(`SELECT slug,title,body,updated_at FROM content WHERE type='resource' ORDER BY updated_at DESC,title ASC LIMIT ? OFFSET ?`,[safeSize,offset]);return rows.map(values=>({slug:String(values.slug),title:String(values.title),category:'Guide',excerpt:String(values.body||'').split('\n').filter(Boolean).find((line:string)=>!line.startsWith('#'))?.replace(/^[-*]\s*/,'').slice(0,220)||'',updated_at:values.updated_at?String(values.updated_at):undefined}));}
export async function getResourceBySlug(slug:string){await ensureResourceSeeded();const item=await getContentBySlug(slug);return item&&item.type==='resource'?item as ContentItem&{type:'resource'}:null;}
export async function saveContent(item:ContentItem){const db=await ensureContentSchema();await db.run(`INSERT INTO content(slug,title,body,type,author) VALUES(?,?,?,?,?) ON CONFLICT(slug) DO UPDATE SET title=excluded.title,body=excluded.body,type=excluded.type,author=excluded.author,updated_at=CURRENT_TIMESTAMP`,[item.slug,item.title,item.body,item.type,item.author]);}
export async function deleteContentBySlug(slug:string){const db=await ensureContentSchema();await db.run('DELETE FROM content WHERE slug=?',[slug]);}
export async function migrateBlogFilesToDb(){const db=await ensureContentSchema(),blogDir=path.join(process.cwd(),'content','blog');if(!fs.existsSync(blogDir))return;for(const file of fs.readdirSync(blogDir)){if(!file.endsWith('.md'))continue;const slug=file.replace('.md',''),existing=await db.one<any>('SELECT COUNT(*) AS count FROM content WHERE slug=?',[slug]);if(Number(existing?.count||0)>0)continue;try{const rawContent=fs.readFileSync(path.join(blogDir,file),'utf8'),match=rawContent.match(/^---\r?\n([\s\S]*?)\r?\n---/),frontmatter:Record<string,string>={};let bodyContent=rawContent;if(match){bodyContent=rawContent.slice(match[0].length);for(const line of match[1].split('\n')){const colonIdx=line.indexOf(':');if(colonIdx!==-1)frontmatter[line.slice(0,colonIdx).trim().toLowerCase()]=line.slice(colonIdx+1).trim();}}await db.run(`INSERT INTO content(slug,title,body,type,author) VALUES(?,?,?,'blog',?)`,[slug,frontmatter.title||'Untitled Post',bodyContent.trim(),frontmatter.author||'Kurukoo Team']);}catch(err){console.error(`Error migrating blog file ${file}:`,err);}}}
export async function getAllBlogArticles():Promise<BlogMetadata[]>{const items=await getAllContent('blog');return items.map(item=>({slug:item.slug,title:item.title,date:item.createdAt?item.createdAt.split(/[ T]/)[0]:'2026-07-28',author:item.author,category:'Blog'}));}
export async function getBlogArticleBySlug(slug:string):Promise<BlogArticle|null>{const item=await getContentBySlug(slug);if(!item||item.type!=='blog')return null;return{slug:item.slug,title:item.title,date:item.createdAt?item.createdAt.split(/[ T]/)[0]:'2026-07-28',author:item.author,category:'Blog',content:convertMarkdownToHtml(item.body)};}
