import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { getCanonicalStore } from './canonicalStore.js';
import { getCanonicalPersistenceMode } from './canonicalPersistence.js';

export type ReviewStatus = 'pending' | 'accepted' | 'rejected' | 'needs_rewrite' | 'needs_second_review';
export type ReviewDecision = 'accept' | 'reject' | 'rewrite' | 'second_review';
const STATUSES = new Set<ReviewStatus>(['pending', 'accepted', 'rejected', 'needs_rewrite', 'needs_second_review']);
const DATASET_PATH = path.join(process.cwd(), 'ml', 'datasets', 'kurukoo-teacher-candidates.jsonl');
const json=(value:unknown)=>JSON.stringify(value??null);
const parse=(value:unknown):any=>{try{return value?JSON.parse(String(value)):null;}catch{return null;}};
const hash=(value:unknown)=>crypto.createHash('sha256').update(typeof value==='string'?value:json(value)).digest('hex');

export async function ensureCurationSchema():Promise<void>{
  const db=await getCanonicalStore();
  const pg=getCanonicalPersistenceMode()==='postgres';
  await db.run(`CREATE TABLE IF NOT EXISTS training_curation_candidates (
    example_id TEXT PRIMARY KEY,
    trajectory_json TEXT NOT NULL,
    skill TEXT,
    family TEXT,
    actor TEXT,
    market TEXT,
    locale TEXT,
    channel TEXT,
    lifecycle TEXT,
    scenario_variant TEXT,
    teacher_provider TEXT,
    teacher_model TEXT,
    candidate_score REAL,
    review_scores_json TEXT,
    failure_dimensions_json TEXT,
    provenance_json TEXT,
    review_status TEXT NOT NULL DEFAULT 'pending',
    reviewed INTEGER NOT NULL DEFAULT 0,
    accepted INTEGER NOT NULL DEFAULT 0,
    reviewer_id TEXT,
    reviewer_notes TEXT,
    rejection_reason TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    scenario_id TEXT,
    original_id TEXT,
    rewrite_of TEXT,
    content_hash TEXT NOT NULL,
    created_at ${pg?'TIMESTAMPTZ':'TEXT'} NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at ${pg?'TIMESTAMPTZ':'TEXT'} NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`);
  await db.run(`CREATE TABLE IF NOT EXISTS training_curation_audit (
    id ${pg?'BIGINT GENERATED BY DEFAULT AS IDENTITY':'INTEGER PRIMARY KEY AUTOINCREMENT'},
    example_id TEXT NOT NULL,
    reviewer_id TEXT NOT NULL,
    decision TEXT NOT NULL,
    reason TEXT,
    notes TEXT,
    candidate_version INTEGER NOT NULL,
    dataset_version TEXT,
    created_at ${pg?'TIMESTAMPTZ':'TEXT'} NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`);
  await db.run('CREATE INDEX IF NOT EXISTS idx_curation_status_priority ON training_curation_candidates(review_status,candidate_score,updated_at)');
  await db.run('CREATE INDEX IF NOT EXISTS idx_curation_rewrite_of ON training_curation_candidates(rewrite_of)');
}

function rowToCandidate(row:any){return{exampleId:String(row.example_id),trajectory:parse(row.trajectory_json),skill:row.skill,family:row.family,actor:row.actor,market:row.market,locale:row.locale,channel:row.channel,lifecycle:row.lifecycle,scenarioId:row.scenario_id,scenarioVariant:row.scenario_variant,teacher:{provider:row.teacher_provider,model:row.teacher_model},candidateScore:row.candidate_score==null?null:Number(row.candidate_score),reviewScores:parse(row.review_scores_json)||null,failureDimensions:parse(row.failure_dimensions_json)||[],provenance:parse(row.provenance_json)||{},reviewStatus:row.review_status,reviewed:Boolean(row.reviewed),accepted:Boolean(row.accepted),reviewerId:row.reviewer_id,reviewerNotes:row.reviewer_notes,rejectionReason:row.rejection_reason,version:Number(row.version),originalId:row.original_id,rewriteOf:row.rewrite_of,contentHash:row.content_hash,createdAt:row.created_at,updatedAt:row.updated_at};}
function candidateFromSource(source:any){const metadata=source.metadata||source.context||{},quality=source.quality||{},provenance=source.provenance||source.source||{},trajectory=source.trajectory||source,exampleId=String(source.exampleId||source.example_id||hash(trajectory).slice(0,24));return{exampleId,trajectory,scenarioId:source.scenarioId||source.scenario_id||metadata.scenarioId||null,skill:source.skill||source.labels?.skill||metadata.skill||trajectory?.labels?.skill||null,family:source.family||source.labels?.family||metadata.family||trajectory?.labels?.family||null,actor:source.actor||source.labels?.actor||metadata.actor||trajectory?.labels?.actor||null,market:source.market||source.labels?.market||metadata.market||trajectory?.labels?.market||null,locale:source.locale||source.labels?.locale||metadata.locale||trajectory?.labels?.locale||null,channel:source.channel||source.labels?.channel||metadata.channel||trajectory?.labels?.channel||null,lifecycle:source.lifecycle||source.labels?.lifecycle||metadata.lifecycle||trajectory?.labels?.lifecycle||null,scenarioVariant:source.scenarioVariant||source.lifecycleVariant||source.labels?.variant||metadata.scenarioVariant||null,teacherProvider:source.teacherProvider||provenance.teacherProvider||provenance.provider||source.teacher?.provider||null,teacherModel:source.teacherModel||provenance.teacherModel||provenance.model||source.teacher?.model||null,candidateScore:Number.isFinite(Number(source.candidateScore??source.score??quality.score))?Number(source.candidateScore??source.score??quality.score):null,failureDimensions:source.failureDimensions||quality.failureDimensions||quality.failures||[],provenance};}

export async function importTeacherCandidates():Promise<{imported:number;source:string}>{await ensureCurationSchema();if(!fs.existsSync(DATASET_PATH))return{imported:0,source:DATASET_PATH};const db=await getCanonicalStore();let imported=0;for(const line of fs.readFileSync(DATASET_PATH,'utf8').split(/\r?\n/)){if(!line.trim())continue;try{const c=candidateFromSource(JSON.parse(line));await db.run(`INSERT INTO training_curation_candidates(example_id,trajectory_json,skill,family,actor,market,locale,channel,lifecycle,scenario_variant,teacher_provider,teacher_model,candidate_score,failure_dimensions_json,provenance_json,content_hash,scenario_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(example_id) DO NOTHING`,[c.exampleId,json(c.trajectory),c.skill,c.family,c.actor,c.market,c.locale,c.channel,c.lifecycle,c.scenarioVariant,c.teacherProvider,c.teacherModel,c.candidateScore,json(c.failureDimensions),json(c.provenance),hash(c.trajectory),c.scenarioId||null]);await db.run(`UPDATE training_curation_candidates SET skill=COALESCE(skill,?),family=COALESCE(family,?),actor=COALESCE(actor,?),market=COALESCE(market,?),locale=COALESCE(locale,?),channel=COALESCE(channel,?),lifecycle=COALESCE(lifecycle,?),scenario_variant=COALESCE(scenario_variant,?),teacher_provider=COALESCE(teacher_provider,?),teacher_model=COALESCE(teacher_model,?),scenario_id=COALESCE(scenario_id,?) WHERE example_id=? AND review_status='pending'`,[c.skill,c.family,c.actor,c.market,c.locale,c.channel,c.lifecycle,c.scenarioVariant,c.teacherProvider,c.teacherModel,c.scenarioId||null,c.exampleId]);imported++;}catch{}}return{imported,source:DATASET_PATH};}

const priority=(row:any)=>{const failures=parse(row.failure_dimensions_json)||[];const missing=['skill','family','actor','market','locale','channel'].filter(k=>!row[k]).length*3;return failures.length*20+(100-Number(row.candidate_score||0))+missing;};
export async function listCurationCandidates(options:{status?:string;limit?:number;offset?:number;import?:boolean}={}):Promise<any>{if(options.import!==false)await importTeacherCandidates();await ensureCurationSchema();const db=await getCanonicalStore(),limit=Math.min(Math.max(Number(options.limit||50),1),200),offset=Math.max(Number(options.offset||0),0),status=options.status&&STATUSES.has(options.status as ReviewStatus)?options.status:null;const rows=await db.all<any>(`SELECT * FROM training_curation_candidates ${status?'WHERE review_status=?':''} ORDER BY candidate_score IS NULL ASC,candidate_score ASC,updated_at ASC LIMIT ? OFFSET ?`,status?[status,limit,offset]:[limit,offset]);const countRow=await db.one<any>(`SELECT COUNT(*) AS count FROM training_curation_candidates ${status?'WHERE review_status=?':''}`,status?[status]:[]);return{candidates:rows.map(rowToCandidate).sort((a:any,b:any)=>priority(b)-priority(a)),count:Number(countRow?.count||0),limit,offset,statuses:await getCurationStats()};}
export async function getCurationCandidate(exampleId:string){await ensureCurationSchema();const row=await(await getCanonicalStore()).one<any>('SELECT * FROM training_curation_candidates WHERE example_id=? LIMIT 1',[exampleId]);return row?rowToCandidate(row):null;}
export async function reviewCurationCandidate(input:{exampleId:string;decision:ReviewDecision;reviewerId:string;notes?:string;reason?:string;datasetVersion?:string;reviewScores?:Record<string,number>}):Promise<any>{await ensureCurationSchema();const current=await getCurationCandidate(input.exampleId);if(!current)return{ok:false,status:'missing'};const map:Record<ReviewDecision,ReviewStatus>={accept:'accepted',reject:'rejected',rewrite:'needs_rewrite',second_review:'needs_second_review'},next=map[input.decision];if(!next)return{ok:false,status:'invalid_decision'};const db=await getCanonicalStore();await db.transaction(async tx=>{await tx.run('UPDATE training_curation_candidates SET review_status=?,reviewed=1,accepted=?,reviewer_id=?,reviewer_notes=?,rejection_reason=?,review_scores_json=?,updated_at=CURRENT_TIMESTAMP WHERE example_id=?',[next,next==='accepted'?1:0,input.reviewerId,input.notes||null,input.reason||null,input.reviewScores?json(input.reviewScores):null,input.exampleId]);await tx.run('INSERT INTO training_curation_audit(example_id,reviewer_id,decision,reason,notes,candidate_version,dataset_version) VALUES(?,?,?,?,?,?,?)',[input.exampleId,input.reviewerId,input.decision,input.reason||null,input.notes||null,current.version,input.datasetVersion||null]);});return{ok:true,candidate:await getCurationCandidate(input.exampleId)};}
export async function rewriteCurationCandidate(input:{exampleId:string;trajectory:unknown;reviewerId:string;notes?:string;reason?:string}):Promise<any>{await ensureCurationSchema();const original=await getCurationCandidate(input.exampleId);if(!original)return{ok:false,status:'missing'};const rewriteId=`${original.exampleId}:rewrite:${original.version+1}:${hash(input.trajectory).slice(0,12)}`,db=await getCanonicalStore();await db.transaction(async tx=>{await tx.run(`INSERT INTO training_curation_candidates(example_id,trajectory_json,skill,family,actor,market,locale,channel,lifecycle,scenario_variant,teacher_provider,teacher_model,candidate_score,review_scores_json,failure_dimensions_json,provenance_json,review_status,reviewed,accepted,reviewer_id,reviewer_notes,rejection_reason,version,scenario_id,original_id,rewrite_of,content_hash) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(example_id) DO NOTHING`,[rewriteId,json(input.trajectory),original.skill,original.family,original.actor,original.market,original.locale,original.channel,original.lifecycle,original.scenarioVariant,original.teacher.provider,original.teacher.model,null,null,json([]),json({...original.provenance,rewrittenFrom:original.exampleId}),'pending',0,0,null,null,input.reason||null,original.version+1,original.scenarioId||null,original.originalId||original.exampleId,original.exampleId,hash(input.trajectory)]);await tx.run(`UPDATE training_curation_candidates SET review_status='needs_rewrite',reviewed=1,reviewer_id=?,reviewer_notes=?,rejection_reason=?,updated_at=CURRENT_TIMESTAMP WHERE example_id=?`,[input.reviewerId,input.notes||null,input.reason||null,input.exampleId]);await tx.run('INSERT INTO training_curation_audit(example_id,reviewer_id,decision,reason,notes,candidate_version) VALUES(?,?,?,?,?,?)',[input.exampleId,input.reviewerId,'rewrite',input.reason||null,input.notes||null,original.version]);});return{ok:true,originalId:original.exampleId,rewriteId,candidate:await getCurationCandidate(rewriteId)};}
export async function getCurationStats():Promise<any>{await ensureCurationSchema();const db=await getCanonicalStore(),rows=await db.all<any>('SELECT review_status,COUNT(*) AS count FROM training_curation_candidates GROUP BY review_status'),counts:Record<string,number>={};for(const row of rows)counts[String(row.review_status)]=Number(row.count||0);const coverage:Record<string,Record<string,number>>={};for(const dimension of ['skill','family','actor','market','locale','channel','lifecycle']){coverage[dimension]={};for(const row of await db.all<any>(`SELECT COALESCE(${dimension},'unknown') AS value,COUNT(*) AS count FROM training_curation_candidates WHERE accepted=1 GROUP BY ${dimension}`))coverage[dimension][String(row.value)]=Number(row.count||0);}return{counts,total:Object.values(counts).reduce((a,b)=>a+b,0),acceptedCoverage:coverage};}
export async function getAcceptedCorpusGate(requirements:Record<string,number>={}):Promise<any>{const stats=await getCurationStats(),accepted=stats.counts.accepted||0,failures:Record<string,{required:number;actual:number}>={};for(const[dimension,required]of Object.entries(requirements)){const actual=Object.keys(stats.acceptedCoverage[dimension]||{}).filter(k=>k!=='unknown').length;if(actual<Number(required))failures[dimension]={required:Number(required),actual};}return{permitted:accepted>0&&Object.keys(failures).length===0,accepted,failures,coverage:stats.acceptedCoverage};}
export async function getCurationAudit(exampleId?:string):Promise<any[]>{await ensureCurationSchema();const db=await getCanonicalStore(),rows=await db.all<any>(`SELECT * FROM training_curation_audit ${exampleId?'WHERE example_id=?':''} ORDER BY created_at DESC`,exampleId?[exampleId]:[]);return rows;}
export function acceptedCorpusHash(candidates:any[]):string{return hash(candidates.map(c=>({exampleId:c.exampleId,trajectory:c.trajectory,version:c.version})).sort((a,b)=>a.exampleId.localeCompare(b.exampleId)));}
export const CURATION_DATASET_PATH=DATASET_PATH;
