import { getCanonicalStore } from './canonicalStore.js';
import { ensureDisputeSchema } from './canonicalDomainSchemas.js';
import { freezeEscrowForOrder, refundEscrow, releaseEscrow } from './escrow.js';
import { getAllowedEconomicTransitions, getEconomicRequest, transitionEconomicRequest } from './skillFlows.js';
export interface DisputeOpenResult{disputeId:number;escrowFrozen:boolean;economicRequestId:string|null;}
export interface DisputeResolutionResult{disputeId:number;resolution:'release'|'refund';escrowUpdated:boolean;economicRequestId:string|null;orderStatus:string|null;}
async function findLinkedEconomicRequestId(orderId:string){const s=await getCanonicalStore();const row=await s.one('SELECT id FROM economic_requests WHERE fulfillment_json LIKE ? ORDER BY updated_at DESC LIMIT 1',[`%${orderId}%`]);return row?String((row as any).id):null;}
async function getDispute(disputeId:number){await ensureDisputeSchema();const row=await(await getCanonicalStore()).one('SELECT id,phone,order_id,status,resolution FROM disputes WHERE id=? LIMIT 1',[disputeId]);if(!row)return null;return{id:Number((row as any).id),phone:String((row as any).phone||''),orderId:(row as any).order_id==null?null:String((row as any).order_id),status:String((row as any).status||''),resolution:(row as any).resolution==null?null:String((row as any).resolution)};}
export async function createDispute(phone:string,orderId:string,reason:string){const cleanPhone=String(phone||'').trim(),cleanOrderId=String(orderId||'').trim(),cleanReason=String(reason||'').trim();if(!cleanPhone||!cleanOrderId||!cleanReason)throw new Error('Dispute buyer, order, and reason are required');await ensureDisputeSchema();const s=await getCanonicalStore();const order=await s.one('SELECT phone FROM orders WHERE id=? LIMIT 1',[cleanOrderId]);if(!order)throw new Error('Order not found');if(String((order as any).phone||'')!==cleanPhone)throw new Error('Only the order buyer can open a dispute');const existing=await s.one(`SELECT id FROM disputes WHERE phone=? AND order_id=? AND status IN ('open','escalated') ORDER BY id DESC LIMIT 1`,[cleanPhone,cleanOrderId]);if(existing)return{disputeId:Number((existing as any).id),escrowFrozen:true,economicRequestId:await findLinkedEconomicRequestId(cleanOrderId)};const linkedRequestId=await findLinkedEconomicRequestId(cleanOrderId);let linkedRequest:any=null;if(linkedRequestId){linkedRequest=await getEconomicRequest(linkedRequestId);if(!linkedRequest||linkedRequest.phone!==cleanPhone)throw new Error('Linked economic request ownership mismatch');if(linkedRequest.status!=='disputed'&&!getAllowedEconomicTransitions(linkedRequest.status).includes('disputed'))throw new Error(`Invalid economic request transition: ${linkedRequest.status} -> disputed`);}const escrowFrozen=await freezeEscrowForOrder(cleanOrderId,cleanReason);if(!escrowFrozen)throw new Error('No held escrow is available to freeze for this order');if(linkedRequestId&&linkedRequest&&linkedRequest.status!=='disputed')await transitionEconomicRequest(linkedRequestId,'disputed',{fulfillment:{...(linkedRequest.fulfillment||{}),dispute_requested_at:new Date().toISOString(),dispute_reason:cleanReason}});const inserted=await s.insert(`INSERT INTO disputes(phone,order_id,reason,status,type) VALUES(?,?,?,'open','dispute') RETURNING id`,[cleanPhone,cleanOrderId,cleanReason]);return{disputeId:Number((inserted as any)?.id||0),escrowFrozen,economicRequestId:linkedRequestId};}
export async function resolveDispute(disputeId:number,resolution:string){await ensureDisputeSchema();await(await getCanonicalStore()).run(`UPDATE disputes SET status='resolved',resolution=? WHERE id=?`,[resolution,disputeId]);}
export async function resolveDisputeWithEconomicLifecycle(disputeId:number,resolution:'release'|'refund'){const dispute=await getDispute(disputeId);if(!dispute)throw new Error('Dispute not found');if(!['open','escalated'].includes(dispute.status)&&dispute.status!=='resolved')throw new Error(`Dispute cannot be resolved from status ${dispute.status}`);const orderId=dispute.orderId,linkedEconomicRequestId=orderId?await findLinkedEconomicRequestId(orderId):null;const s=await getCanonicalStore();let escrowUpdated=false,orderStatus:string|null=null;if(orderId){const escrow=await s.one(`SELECT id FROM escrow WHERE order_id=? AND status IN ('held','disputed') ORDER BY id DESC LIMIT 1`,[orderId]);if(escrow){escrowUpdated=resolution==='release'?await releaseEscrow(Number((escrow as any).id),{force:true}):await refundEscrow(Number((escrow as any).id));if(!escrowUpdated)throw new Error('Escrow could not be updated for this dispute');}orderStatus=resolution==='release'?'completed':'refunded';await s.run('UPDATE orders SET status=? WHERE id=?',[orderStatus,orderId]);}if(linkedEconomicRequestId){const linkedRequest=await getEconomicRequest(linkedEconomicRequestId);if(linkedRequest&&linkedRequest.status==='disputed'){const target=resolution==='release'?'completed':'cancelled';if(getAllowedEconomicTransitions(linkedRequest.status).includes(target))await transitionEconomicRequest(linkedEconomicRequestId,target,{fulfillment:{...(linkedRequest.fulfillment||{}),dispute_resolved_at:new Date().toISOString(),dispute_resolution:resolution}});}}await s.run(`UPDATE disputes SET status='resolved',resolution=? WHERE id=?`,[resolution==='release'?'Admin resolution: escrow released.':'Admin resolution: escrow refunded.',disputeId]);return{disputeId,resolution,escrowUpdated,economicRequestId:linkedEconomicRequestId,orderStatus};}
export async function escalateDispute(disputeId:number){await ensureDisputeSchema();await(await getCanonicalStore()).run(`UPDATE disputes SET status='escalated' WHERE id=?`,[disputeId]);}
export async function getDisputeStatus(disputeId:number){await ensureDisputeSchema();const row=await(await getCanonicalStore()).one('SELECT status FROM disputes WHERE id=?',[disputeId]);return row?String((row as any).status):null;}
