import { getCanonicalStore } from './canonicalStore.js';
import { ensureEscrowSchemaCanonical, ensureOrderSchema } from './canonicalDomainSchemas.js';
import { resolveFinancialBeneficiary } from './agentRepresentationService.js';
const DEFAULT_COOLING_OFF_HOURS=24;export interface VerifiedPaymentEvidence{verified:true;paymentReference:string;}
const iso=(h:number)=>new Date(Date.now()+h*3600000).toISOString();
export async function ensureEscrowSchema(){return ensureEscrowSchemaCanonical();}
export async function createEscrow(orderId:string,buyerPhone:string,providerPhone:string,amountMinor:number,description:string,payment:VerifiedPaymentEvidence,coolingOffHours=DEFAULT_COOLING_OFF_HOURS){if(!orderId||!buyerPhone||!providerPhone)throw new Error('Escrow parties and order are required');if(!Number.isInteger(amountMinor)||amountMinor<=0)throw new Error('Escrow amount must be a positive integer');if(payment?.verified!==true||!String(payment.paymentReference||'').trim())throw new Error('Verified payment evidence is required before an escrow ledger can be created');const s=await ensureEscrowSchemaCanonical();const existing=await s.one<any>(`SELECT id FROM escrow WHERE order_id=? AND status IN ('held','disputed') LIMIT 1`,[orderId]);if(existing)return Number(existing.id);const beneficiary=await resolveFinancialBeneficiary(providerPhone);await s.run(`INSERT INTO escrow(order_id,buyer_phone,provider_phone,beneficiary_phone,provider_identity,delegated_provider,amount_minor,description,status,cooling_off_until) VALUES(?,?,?,?,?,?,?,?,'held',?)`,[orderId,buyerPhone,beneficiary.beneficiaryPhone,beneficiary.beneficiaryPhone,beneficiary.providerIdentity,beneficiary.delegated?1:0,amountMinor,`${description} [payment:${payment.paymentReference.trim()}]`,iso(Math.max(0,coolingOffHours))]);const row=await s.one<any>('SELECT id FROM escrow WHERE order_id=? AND status=\'held\' ORDER BY id DESC LIMIT 1',[orderId]);return Number(row?.id||0);}
export async function releaseEscrow(escrowId:number,options:{force?:boolean}={}){const s=await ensureEscrowSchemaCanonical();const row=await s.one<any>('SELECT e.status,e.cooling_off_until,o.status order_status FROM escrow e LEFT JOIN orders o ON o.id=e.order_id WHERE e.id=?',[escrowId]);if(!row||row.status!=='held')return false;if(!options.force&&!['delivered','completed'].includes(String(row.order_status)))return false;if(!options.force&&row.cooling_off_until&&new Date(String(row.cooling_off_until)).getTime()>Date.now())return false;return (await s.run(`UPDATE escrow SET status='released',completed_at=CURRENT_TIMESTAMP WHERE id=? AND status='held'`,[escrowId])).rowCount>0;}
export async function refundEscrow(escrowId:number){const s=await ensureEscrowSchemaCanonical();const r=await s.run(`UPDATE escrow SET status='refunded',completed_at=CURRENT_TIMESTAMP WHERE id=? AND status IN ('held','disputed')`,[escrowId]);return r.rowCount>0;}
export async function freezeEscrowForOrder(orderId:string,reason?:string){const s=await ensureEscrowSchemaCanonical();const row=await s.one<any>(`SELECT id FROM escrow WHERE order_id=? AND status='held' LIMIT 1`,[orderId]);if(!row)return false;const a=await s.run(`UPDATE escrow SET status='disputed',dispute_reason=COALESCE(?,dispute_reason) WHERE id=? AND status='held'`,[reason||'Dispute opened',Number(row.id)]);if(a.rowCount)await s.run(`UPDATE orders SET status='disputed',updated_at=CURRENT_TIMESTAMP WHERE id=? AND status IN ('escrow_held','paid','in_fulfillment','delivered','completed')`,[orderId]);return a.rowCount>0;}
