import crypto from 'node:crypto';
import { getCanonicalStore } from './canonicalStore.js';
import { ensurePointsSchema } from './canonicalDomainSchemas.js';
import { deductCredits } from './pointsEngine.js';
export interface ActivePulseProvider{phone:string;skill:string;lat:number;lng:number;name:string;location?:string;subscription_tier?:string;source:'mobile'|'stationary'};export interface PublicPulseProvider extends Omit<ActivePulseProvider,'lat'|'lng'|'phone'>{id:string;lat:number;lng:number;location_radius_m:number;verified:true;live_now:true};
async function schema(){const s=await getCanonicalStore();await s.run(`CREATE TABLE IF NOT EXISTS pulse_sessions(id BIGINT PRIMARY KEY,phone TEXT,skill TEXT,lat REAL,lng REAL,expires_at TIMESTAMPTZ,active BOOLEAN DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP)`);return s;}
export async function canActivatePulse(phone:string){const rows=await(await getCanonicalStore()).all<any>('SELECT operation_mode FROM skills WHERE phone=?',[phone]);return rows.some(r=>String(r.operation_mode)==='mobile');}
export interface PulseReadiness{radarDefaultOn:boolean;active:boolean;eligibleToBroadcast:boolean;role:'provider'|'user';nudge?:string;}
export async function getPulseReadiness(phone:string){const s=await getCanonicalStore();const p=await s.one<any>('SELECT verified_provider,is_available FROM memory_profiles WHERE phone=? LIMIT 1',[phone]);const verified=Number(p?.verified_provider||0)===1,available=Number(p?.is_available||0)===1,eligible=verified&&available&&await canActivatePulse(phone),active=(await getActivePulseProviders()).some(x=>x.phone===phone);return{radarDefaultOn:true,active,eligibleToBroadcast:eligible,role:verified?'provider':'user',nudge:active?'You are live on Nearby Pulse. Kurukoo keeps your public location fuzzed and shows only confirmed availability.':eligible?'Nearby Radar is ready. Go Live only when you want nearby people to discover your available service.':'Nearby Radar is ready for local discovery. Tell Kurukoo what you need nearby, or complete provider verification before broadcasting yourself.'};}
export async function activatePulse(phone:string,skill:string,lat:number,lng:number){if(!await canActivatePulse(phone))return{success:false,message:'Cannot Go Live. Your skills are not registered as mobile operation mode.'};const latitude=Number(lat),longitude=Number(lng);if(!Number.isFinite(latitude)||!Number.isFinite(longitude)||latitude<-90||latitude>90||longitude<-180||longitude>180)return{success:false,message:'Nearby Pulse needs an explicit valid location before it can be activated. No location was inferred.'};const normalized=String(skill||'').trim().slice(0,120);if(!normalized)return{success:false,message:'A service skill is required before going live.'};const s=await schema(),p=await s.one<any>('SELECT subscription_tier,verified_provider,is_available FROM memory_profiles WHERE phone=?',[phone]);const tier=String(p?.subscription_tier||'Base');if(Number(p?.verified_provider||0)!==1||Number(p?.is_available||0)!==1)return{success:false,message:'Nearby Pulse requires an approved provider profile that is currently available.'};if(tier==='Base'){const since=new Date(Date.now()-30*86400000).toISOString();const r=await s.one<any>('SELECT COUNT(*) cnt FROM pulse_sessions WHERE phone=? AND created_at>=?',[phone,since]);if(Number(r?.cnt||0)>=10)return{success:false,message:'Nearby Pulse monthly limit reached. Base tier is limited to 5 hours (10 sessions) per month. Upgrade to Plus or Business for unlimited access.'};}await ensurePointsSchema();if(!await deductCredits(phone,5,'Nearby Pulse "Go Live" (30 min)'))return{success:false,message:'Insufficient credits for Nearby Pulse (requires 5 credits).'};await s.run('UPDATE pulse_sessions SET active=FALSE WHERE phone=?',[phone]);await s.run('INSERT INTO pulse_sessions(id,phone,skill,lat,lng,expires_at,active) VALUES(?,?,?,?,?,?,TRUE)',[Date.now(),phone,normalized,latitude,longitude,new Date(Date.now()+30*60000).toISOString()]);return{success:true,message:'Nearby Pulse presence is active for 30 minutes using the location and skill you explicitly supplied. Public discovery is fuzzed; matching and any external contact remain separate, evidence-backed steps.'};}
export async function endPulseSession(phone:string){await(await schema()).run('UPDATE pulse_sessions SET active=FALSE WHERE phone=? AND active=TRUE',[phone]);}
export async function getActivePulseProviders(){const s=await schema(),rows=await s.all<any>(`SELECT p.phone,p.skill,p.lat,p.lng,m.name,m.location,m.subscription_tier,'mobile' source FROM pulse_sessions p JOIN memory_profiles m ON p.phone=m.phone WHERE p.active=TRUE AND p.expires_at>CURRENT_TIMESTAMP AND m.verified_provider=1 AND m.is_available=1 UNION ALL SELECT pr.phone,s.skill,pr.last_lat lat,pr.last_lng lng,m.name,m.location,m.subscription_tier,'stationary' source FROM provider_presence pr JOIN memory_profiles m ON pr.phone=m.phone JOIN skills s ON pr.phone=s.phone WHERE pr.is_live=1 AND pr.operation_mode='stationary' AND m.verified_provider=1 AND m.is_available=1`),out:ActivePulseProvider[]=[];for(const r of rows){const lat=Number(r.lat),lng=Number(r.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng))continue;out.push({phone:String(r.phone),skill:String(r.skill),lat,lng,name:String(r.name||'Verified provider'),location:r.location?String(r.location):undefined,subscription_tier:r.subscription_tier?String(r.subscription_tier):undefined,source:r.source==='stationary'?'stationary':'mobile'});}return out;}
function fuzzCoordinate(value:number,salt:string,metres:number){const hash=crypto.createHash('sha256').update(salt).digest();return Math.round((value+(hash.readInt32BE(0)/0x7fffffff)*metres/111320)*1000)/1000;}
export function toPublicPulseProviders(providers:ActivePulseProvider[]):PublicPulseProvider[]{return providers.map(p=>{const radius=100,salt=`${p.phone}:${p.skill}:${p.source}`;return{id:crypto.createHash('sha256').update(`${p.phone}:${p.skill}`).digest('hex').slice(0,16),skill:p.skill,name:p.name,location:p.location,subscription_tier:p.subscription_tier,source:p.source,lat:fuzzCoordinate(p.lat,`${salt}:lat`,radius),lng:fuzzCoordinate(p.lng,`${salt}:lng`,radius),location_radius_m:radius,verified:true,live_now:true};});}
