import { getCanonicalStore } from './canonicalStore.js';
import { getCommission } from './commissionService.js';
import { processDirectPayment } from './directWallet.js';
import { createEconomicRequest, getEconomicCategory } from './skillFlows.js';
import { chargeProviderLead } from './agentNetworkCommerce.js';
import { buildSkillExecutionContract } from './skillExecutionContract.js';
import { broadcastDispatch } from './economicDispatchCoordinator.js';

export async function getLeadCharge(orderType:string):Promise<number>{const ot=orderType.toLowerCase();if(ot.includes('okada')||ot.includes('keke')||ot.includes('car')||ot.includes('taxi')||ot.includes('ride'))return getCommission('provider_lead_ride');if(ot.includes('bicycle')||ot.includes('delivery'))return getCommission('provider_lead_delivery');if(ot.includes('hawker')||ot.includes('food'))return getCommission('provider_lead_food');if(ot.includes('barrow')||ot.includes('truck'))return getCommission('provider_lead_truck');return getCommission('provider_lead_professional');}

async function audit(db:any,action:string,details:Record<string,unknown>){await db.run('INSERT INTO audit_logs(action,details) VALUES(?,?)',[action,JSON.stringify(details)]);}

export async function finalizeOrder(buyerPhone:string,arg2:string='',arg3:Record<string,unknown>={},arg4?:any):Promise<{success:boolean;message:string;orderId?:string}>{
  let providerPhone='';let orderType='';let details:Record<string,unknown>={};const db=await getCanonicalStore();const creditEconomyEnabled=process.env.CREDIT_ECONOMY_ENABLED!=='false';
  if(arg4!==undefined){providerPhone=arg2;orderType=arg3 as unknown as string;details=arg4||{};}else{details=arg3||{};orderType=String(details.skill||arg2||'general_service');
    if(orderType==='universal_vendor_order'){const idempotencyKey=String(details.idempotencyKey||`vendor:${buyerPhone}:${Date.now()}`),existing=await db.one<any>('SELECT id,status FROM orders WHERE idempotency_key=? LIMIT 1',[idempotencyKey]);if(existing)return{success:true,message:`Vendor order is already awaiting confirmation. Status: ${existing.status}`,orderId:String(existing.id)};const orderId=`ord_${Date.now()}_${Math.floor(Math.random()*10000)}`;await db.run(`INSERT INTO orders(id,phone,order_type,provider_phone,amount,status,idempotency_key) VALUES(?,?,?,?,?,?,?) ON CONFLICT(idempotency_key) DO NOTHING`,[orderId,buyerPhone,orderType,null,0,'awaiting_confirmation',idempotencyKey]);await audit(db,'vendor_order_started',{orderId,buyerPhone,next:'confirm_item_quantity_location'});return{success:true,message:'Vendor order started. Confirm the item, quantity and delivery location before escrow is locked.',orderId};}
    const economicCategory=getEconomicCategory(orderType);if(!economicCategory)return{success:true,message:''};const interaction=buildSkillExecutionContract(orderType).interaction;const hasExplicitExecution=Boolean(details.bookingMode)||(typeof details.amount==='number'&&Number.isFinite(details.amount)&&Number(details.amount)>0)||arg4!==undefined;
    if(!hasExplicitExecution){const idempotencyKey=String(details.idempotencyKey||`request:${buyerPhone}:${orderType}`),existing=await db.one<any>('SELECT id,status FROM orders WHERE idempotency_key=? LIMIT 1',[idempotencyKey]);if(existing)return{success:true,message:`Your ${orderType.replace(/_/g,' ')} request is already awaiting confirmation.`,orderId:String(existing.id)};const orderId=`req_${Date.now()}_${Math.floor(Math.random()*10000)}`;await db.run(`INSERT INTO orders(id,phone,order_type,provider_phone,amount,status,idempotency_key) VALUES(?,?,?,?,?,?,?) ON CONFLICT(idempotency_key) DO NOTHING`,[orderId,buyerPhone,orderType,null,0,'awaiting_confirmation',idempotencyKey]);await createEconomicRequest({id:orderId,phone:buyerPhone,skill:orderType,requirements:details});await audit(db,'economic_request_started',{orderId,buyerPhone,orderType,category:economicCategory,next:'capture_requirements_and_confirm'});return{success:true,message:'Request started. I’ll collect the missing details and show you the provider, price and terms before anything is committed.',orderId};}
    if(interaction.pattern==='dispatch'){const idempotencyKey=details.idempotencyKey?String(details.idempotencyKey):null;if(idempotencyKey){const existing=await db.one<any>('SELECT id,status FROM orders WHERE idempotency_key=? LIMIT 1',[idempotencyKey]);if(existing)return{success:true,message:`Dispatch request already exists. Status: ${existing.status}`,orderId:String(existing.id)};}const orderId=`ord_${Date.now()}_${Math.floor(Math.random()*10000)}`;await createEconomicRequest({id:orderId,phone:buyerPhone,skill:orderType,requirements:details});await db.run(`INSERT INTO orders(id,phone,order_type,provider_phone,amount,status,idempotency_key) VALUES(?,?,?,?,?,?,?) ON CONFLICT(idempotency_key) DO NOTHING`,[orderId,buyerPhone,orderType,null,Number(details.amount||0),'awaiting_match',idempotencyKey]);const vehicleType=details.vehicleType?String(details.vehicleType):details.vehicle_type?String(details.vehicle_type):details.vehicle?String(details.vehicle):undefined;const origin=details.origin?String(details.origin):details.location?String(details.location):undefined;const broadcast=await broadcastDispatch({requestId:orderId,ownerPhone:buyerPhone,skill:orderType,vehicleType,location:origin,latitude:details.latitude!==undefined?Number(details.latitude):undefined,longitude:details.longitude!==undefined?Number(details.longitude):undefined,maxProviders:details.maxProviders!==undefined?Number(details.maxProviders):undefined});await audit(db,'dispatch_broadcast_started',{orderId,buyerPhone,orderType,vehicleType,offerCount:broadcast.offers.length});return{success:true,message:broadcast.offers.length?`Request broadcast to ${broadcast.offers.length} eligible provider${broadcast.offers.length===1?'':'s'}. The lead is charged only when a provider accepts.`:'No eligible provider is currently available; the request remains available for re-matching.',orderId};}
    const idempotencyKey=details.idempotencyKey?String(details.idempotencyKey):null;if(idempotencyKey){const existing=await db.one<any>('SELECT id,status FROM orders WHERE idempotency_key=? LIMIT 1',[idempotencyKey]);if(existing)return{success:true,message:`Order is already in progress. Status: ${existing.status}`,orderId:String(existing.id)};}
    const providerRows=await db.all<any>(`SELECT s.phone,ps.status,ps.leads_this_month,ps.tier FROM skills s JOIN memory_profiles m ON s.phone=m.phone LEFT JOIN provider_subscriptions ps ON s.phone=ps.phone WHERE s.skill=? AND s.is_available=1 AND ps.status='active' LIMIT 1`,[orderType]);if(providerRows.length){const row=providerRows[0],limit=row.tier==='Plus'?100:row.tier==='Business'?1000:30;if(Number(row.leads_this_month)<limit)providerPhone=String(row.phone);}if(!providerPhone){const fallback=await db.one<any>(`SELECT s.phone FROM skills s LEFT JOIN provider_subscriptions ps ON s.phone=ps.phone WHERE s.is_available=1 AND ps.status='active' LIMIT 1`);if(fallback)providerPhone=String(fallback.phone);}
  }
  const idempotencyKey=details.idempotencyKey?String(details.idempotencyKey):null;if(idempotencyKey){const existing=await db.one<any>('SELECT id,status FROM orders WHERE idempotency_key=? LIMIT 1',[idempotencyKey]);if(existing)return{success:true,message:`Order retrieved from cache (idempotent). Status: ${existing.status}`,orderId:String(existing.id)};}
  const clientProfile=await db.one<any>('SELECT subscription_tier FROM memory_profiles WHERE phone=? LIMIT 1',[buyerPhone]);const clientTier=String(clientProfile?.subscription_tier||'Base');if(!providerPhone)return{success:false,message:'No verified provider is currently available. Your request can remain deferred for re-matching.'};
  if(arg4!==undefined){const provSub=await db.one<any>('SELECT tier,status,leads_this_month FROM provider_subscriptions WHERE phone=? LIMIT 1',[providerPhone]);if(!provSub)return{success:false,message:'Provider subscription inactive.'};const limit=provSub.tier==='Plus'?100:provSub.tier==='Business'?1000:30;if(provSub.status!=='active'||Number(provSub.leads_this_month)>=limit)return{success:false,message:'Provider subscription inactive or leads exhausted.'};}
  const isInstant=details.bookingMode==='instant'||!details.bookingMode;const orderId=`ord_${Math.floor(Math.random()*1000000)}`;const jobAmount=Number(details.amount||0);const leadCharge=await chargeProviderLead({providerPhone,category:getEconomicCategory(orderType)||undefined,skill:orderType,requestId:orderId});if(!leadCharge.success)return{success:false,message:`Provider lead requires ${await getLeadCharge(orderType)} Points before this lead can be accepted.`};await db.run('UPDATE provider_subscriptions SET leads_this_month=leads_this_month+1 WHERE phone=?',[providerPhone]);
  if(!creditEconomyEnabled){if(jobAmount>0){const paid=await processDirectPayment(buyerPhone,providerPhone,jobAmount);if(!paid){await db.run('UPDATE provider_subscriptions SET leads_this_month=GREATEST(COALESCE(leads_this_month,0)-1,0) WHERE phone=?',[providerPhone]);return{success:false,message:'Fulfillment failed due to direct payment error.'};}}}else if(!isInstant&&jobAmount>0){const escrowDeducted=await processDirectPayment(buyerPhone,'ESCROW',jobAmount);await db.run('UPDATE provider_subscriptions SET leads_this_month=GREATEST(COALESCE(leads_this_month,0)-1,0) WHERE phone=?',[providerPhone]);if(!escrowDeducted)return{success:false,message:`Verified payment is required before escrow can be created. Required: ₦${jobAmount}.`};return{success:false,message:'Payment reference verification must complete through the Economic Request flow before escrow can be created.'};}
  await db.run(`INSERT INTO orders(id,phone,order_type,provider_phone,amount,status,idempotency_key) VALUES(?,?,?,?,?,?,?) ON CONFLICT(idempotency_key) DO NOTHING`,[orderId,buyerPhone,orderType,providerPhone,jobAmount,isInstant?'completed':'escrow_held',idempotencyKey]);await audit(db,'order_finalized',{orderId,buyerPhone,providerPhone,orderType,isInstant,clientTier,leadCharge});return{success:true,message:`Matched successfully with verified provider.${isInstant?' Match complete.':' Escrow payment secured.'}`,orderId};
}
