import { getCanonicalStore } from './canonicalStore.js';
import { ensurePointsSchema } from './canonicalDomainSchemas.js';
export const POINTS_AWARDS={DAILY_ENGAGEMENT:1,REFERRAL:200,JOB_COMPLETION_MIN:1,JOB_COMPLETION_MAX:5,STAR_BONUS:1} as const;
export const POINTS_COSTS={RIDE_REQUEST:1,EXTRA_RIDE:2,PULSE_GO_LIVE_BLOCK:5,BOOST_LISTING:10,LIVECAST_SIGNAL:1} as const;
export const LEAD_CHARGES:Record<string,number>={okada:50,keke:50,car:50,taxi:50,bicycle_delivery:30,hawker:20,street_food:20,wheelbarrow:20,truck_pusher:20,professional:50};
async function enabled(s:any,phone:string){if(process.env.CREDIT_ECONOMY_ENABLED==='false')return false;const r=await s.one<any>('SELECT country FROM memory_profiles WHERE phone=?',[phone]);return !['gb','uk'].includes(String(r?.country||'ng').toLowerCase());}
export async function addPoints(phone:string,amount:number,description:string){if(!Number.isInteger(amount)||amount<=0)throw new Error('Points amount must be a positive integer');const s=await ensurePointsSchema();if(!(await enabled(s,phone)))return;await s.transaction(async tx=>{await tx.run('UPDATE memory_profiles SET points_balance=COALESCE(points_balance,0)+?,updated_at=CURRENT_TIMESTAMP WHERE phone=?',[amount,phone]);await tx.run(`INSERT INTO credit_transactions(phone,amount,type,description) VALUES(?,?,'credit',?)`,[phone,amount,description]);return undefined;});}
export async function deductPoints(phone:string,amount:number,description:string,allowGrace=false){if(!Number.isInteger(amount)||amount<=0)return{success:false};const s=await ensurePointsSchema();if(!(await enabled(s,phone)))return{success:true,remainingPoints:0};return s.transaction(async tx=>{const row=await tx.one<any>('SELECT COALESCE(points_balance,0) points,COALESCE(grace_leads,0) grace_leads FROM memory_profiles WHERE phone=?',[phone]);if(!row)return{success:false};const current=Number(row.points||0),grace=Number(row.grace_leads||0);if(current<amount){if(!allowGrace||grace>=3)return{success:false,remainingPoints:current};await tx.run('UPDATE memory_profiles SET points_balance=points_balance-?,grace_leads=grace_leads+1,updated_at=CURRENT_TIMESTAMP WHERE phone=?',[amount,phone]);await tx.run(`INSERT INTO credit_transactions(phone,amount,type,description) VALUES(?,?,'debit_grace',?)`,[phone,-amount,description]);return{success:true,isGrace:true,remainingPoints:current-amount};}await tx.run('UPDATE memory_profiles SET points_balance=points_balance-?,updated_at=CURRENT_TIMESTAMP WHERE phone=?',[amount,phone]);await tx.run(`INSERT INTO credit_transactions(phone,amount,type,description) VALUES(?,?,'debit',?)`,[phone,-amount,description]);return{success:true,remainingPoints:current-amount};});}
export async function getPointsBalance(phone:string){const s=await getCanonicalStore();if(!(await enabled(s,phone)))return 0;const r=await s.one<any>('SELECT COALESCE(points_balance,0) points FROM memory_profiles WHERE phone=?',[phone]);return Number(r?.points||0);}
export async function getPointsHistory(phone:string,limit=50){const s=await ensurePointsSchema();if(!(await enabled(s,phone)))return[];return s.all('SELECT * FROM credit_transactions WHERE phone=? ORDER BY id DESC LIMIT ?',[phone,Math.max(1,Math.min(200,Math.floor(limit)))]);}
export async function spendPoints(phone:string,amount:number,feature:string){const r=await deductPoints(phone,amount,`Spend: ${feature}`,false);return{success:r.success,remainingPoints:r.remainingPoints};}
export async function awardDailyEngagement(phone:string){await addPoints(phone,1,'Daily engagement bonus');}export async function awardReferral(phone:string){await addPoints(phone,200,'Referral reward (new subscriber)');}
export async function awardJobCompletion(phone:string,rating=5,eventMarker?:string){const n=Math.max(1,Math.min(5,Math.round(rating)));await addPoints(phone,n,`Job completion bonus (${n})${eventMarker?` [${eventMarker}]`:''}`);}export async function awardStarBonus(phone:string){await addPoints(phone,1,'5-star rating bonus');}
export async function getPointsLeaderboard(limit=10){const s=await getCanonicalStore();return s.all('SELECT phone,name,COALESCE(points_balance,0) points,subscription_tier FROM memory_profiles ORDER BY points_balance DESC LIMIT ?',[Math.max(1,Math.min(100,Math.floor(limit)))]);}
export const addCredits=addPoints;export const deductCredits=async(phone:string,amount:number,description:string)=>(await deductPoints(phone,amount,description)).success;
