import crypto from 'node:crypto';
import { ensureProgressiveTrustSchema } from './canonicalDomainSchemas.js';
import { getCanonicalStore } from './canonicalStore.js';
import { persistCoordinatorEvent } from './coordinatorStore.js';
import type { CoordinatorEventType } from './coordinatorTypes.js';
export type DeviceCredentialType='web'|'pwa'|'mobile'|'passkey'|'push';
export type TrustChallengeStatus='pending'|'approved'|'denied'|'expired';
export type ChannelEvidenceType='whatsapp'|'telegram'|'sms'|'email'|'social'|'ivr'|'ussd';
const CHALLENGE_TTL_MS=5*60*1000;
export function isProgressiveTrustEnabled():boolean{return process.env.KURUKOO_PROGRESSIVE_TRUST_ENABLED==='true'||(process.env.NODE_ENV!=='production'&&!process.env.KURUKOO_PROGRESSIVE_TRUST_ENABLED);}
export function isPushApprovalEnabled():boolean{return process.env.KURUKOO_PUSH_APPROVAL_ENABLED==='true'||(process.env.NODE_ENV!=='production'&&!process.env.KURUKOO_PUSH_APPROVAL_ENABLED);}
export function isLocationConsentEnabled():boolean{return process.env.KURUKOO_LOCATION_CONSENT_ENABLED==='true'||(process.env.NODE_ENV!=='production'&&!process.env.KURUKOO_LOCATION_CONSENT_ENABLED);}
export function isChannelEvidenceEnabled():boolean{return process.env.KURUKOO_CHANNEL_EVIDENCE_ENABLED==='true'||(process.env.NODE_ENV!=='production'&&!process.env.KURUKOO_CHANNEL_EVIDENCE_ENABLED);}
function secret():string{const configured=String(process.env.JWT_SECRET||'').trim();if(!configured&&process.env.NODE_ENV==='production')throw new Error('JWT_SECRET is required for trust records.');return configured||'development-only-trust-secret';}
function digest(value:string):string{return crypto.createHmac('sha256',secret()).update(String(value||'').trim()).digest('hex');}
function normalizeDeviceId(value:unknown):string{return String(value||'').trim().slice(0,256);}
export async function emitProgressiveTrustEvent(type:CoordinatorEventType,phone:string,payload:Record<string,unknown>,sourceId:string):Promise<void>{const ownerPhone=String(phone||'').trim();if(!ownerPhone)return;await persistCoordinatorEvent({id:`trust:${type}:${crypto.randomUUID()}`,type,occurredAt:new Date().toISOString(),producer:'progressiveTrustService',correlationId:`trust:${digest(ownerPhone).slice(0,20)}`,ownerPhone,payload,sensitivity:'personal',provenance:{source:'canonical_service',sourceId:String(sourceId||'').slice(0,160),evidenceLevel:'persisted_state'},policy:{autonomousAllowed:false,confirmationRequired:'none'},schemaVersion:1});}
async function ensureTrustSchema():Promise<void>{await ensureProgressiveTrustSchema();}
async function expireChallenges(db:Awaited<ReturnType<typeof getCanonicalStore>>):Promise<void>{await db.run(`UPDATE trust_challenges SET status='expired' WHERE status='pending' AND expires_at<=CURRENT_TIMESTAMP`);}
export async function registerTrustedDevice(input:{phone:string;deviceId:string;credentialType?:DeviceCredentialType;label?:string;pushCapable?:boolean}):Promise<{deviceId:string;credentialType:DeviceCredentialType;status:'active';trustedAt:string}>{if(!isProgressiveTrustEnabled())throw new Error('Progressive trust is not enabled in this deployment.');await ensureTrustSchema();const phone=String(input.phone||'').trim(),deviceId=normalizeDeviceId(input.deviceId);if(!phone||!deviceId)throw new Error('Phone and device identifier are required.');const deviceHash=digest(deviceId),credentialType=input.credentialType||'web',db=await getCanonicalStore();await db.run(`INSERT INTO trusted_devices(phone,device_hash,credential_type,label,push_capable,status,last_seen_at) VALUES(?,?,?,?,?,'active',CURRENT_TIMESTAMP) ON CONFLICT(phone,device_hash) DO UPDATE SET credential_type=excluded.credential_type,label=excluded.label,push_capable=excluded.push_capable,status='active',revoked_at=NULL,last_seen_at=CURRENT_TIMESTAMP`,[phone,deviceHash,credentialType,String(input.label||'').trim().slice(0,120)||null,input.pushCapable?1:0]);await emitProgressiveTrustEvent('trust.device.registered',phone,{credentialType,pushCapable:Boolean(input.pushCapable),status:'active'},`device:${deviceHash.slice(0,20)}`);return{deviceId,credentialType,status:'active',trustedAt:new Date().toISOString()};}
export async function getTrustedDeviceStatus(phone:string,deviceId:string):Promise<{trusted:boolean;pushCapable:boolean;credentialType?:string}>{await ensureTrustSchema();const db=await getCanonicalStore(),hash=digest(normalizeDeviceId(deviceId)),row=await db.one<any>(`SELECT credential_type,push_capable FROM trusted_devices WHERE phone=? AND device_hash=? AND status='active' LIMIT 1`,[phone,hash]);if(!row)return{trusted:false,pushCapable:false};await db.run(`UPDATE trusted_devices SET last_seen_at=CURRENT_TIMESTAMP WHERE phone=? AND device_hash=? AND status='active'`,[phone,hash]);return{trusted:true,pushCapable:Number(row.push_capable||0)===1,credentialType:String(row.credential_type||'web')};}
export async function createTrustChallenge(input:{phone:string;targetDeviceId:string;purpose?:string}):Promise<{id:string;status:'pending';expiresAt:string;alreadyTrusted:boolean}>{if(!isPushApprovalEnabled())throw new Error('Push approval is not enabled in this deployment.');await ensureTrustSchema();const phone=String(input.phone||'').trim(),targetDeviceId=normalizeDeviceId(input.targetDeviceId);if(!phone||!targetDeviceId)throw new Error('Phone and target device identifier are required.');const db=await getCanonicalStore();await expireChallenges(db);const targetHash=digest(targetDeviceId),existing=await db.one<any>(`SELECT id FROM trusted_devices WHERE phone=? AND device_hash=? AND status='active' LIMIT 1`,[phone,targetHash]);if(existing)return{id:'',status:'pending',expiresAt:new Date(Date.now()+CHALLENGE_TTL_MS).toISOString(),alreadyTrusted:true};const id=crypto.randomUUID(),expiresAt=new Date(Date.now()+CHALLENGE_TTL_MS).toISOString();await db.run(`INSERT INTO trust_challenges(id,phone,target_device_hash,purpose,expires_at) VALUES(?,?,?,?,?)`,[id,phone,targetHash,String(input.purpose||'device_sign_in').slice(0,80),expiresAt]);await emitProgressiveTrustEvent('trust.challenge.created',phone,{challengeId:id,purpose:String(input.purpose||'device_sign_in').slice(0,80),expiresAt},`challenge:${id}`);return{id,status:'pending',expiresAt,alreadyTrusted:false};}
export async function approveTrustChallenge(input:{phone:string;challengeId:string;approverDeviceId:string}):Promise<{approved:boolean;targetDeviceIdHash?:string;reason?:string}>{await ensureTrustSchema();const phone=String(input.phone||'').trim(),approverHash=digest(normalizeDeviceId(input.approverDeviceId)),db=await getCanonicalStore();await expireChallenges(db);const challenge=await db.one<any>(`SELECT target_device_hash,status FROM trust_challenges WHERE id=? AND phone=? LIMIT 1`,[input.challengeId,phone]);if(!challenge)return{approved:false,reason:'challenge_not_found'};if(String(challenge.status)!=='pending')return{approved:false,reason:`challenge_${String(challenge.status)}`};const approver=await db.one<any>(`SELECT id FROM trusted_devices WHERE phone=? AND device_hash=? AND status='active' LIMIT 1`,[phone,approverHash]);if(!approver)return{approved:false,reason:'approver_device_not_trusted'};await db.transaction(async tx=>{await tx.run(`UPDATE trust_challenges SET status='approved',approved_by_device_hash=?,approved_at=CURRENT_TIMESTAMP WHERE id=? AND phone=? AND status='pending'`,[approverHash,input.challengeId,phone]);await tx.run(`INSERT INTO trusted_devices(phone,device_hash,credential_type,label,push_capable,status) VALUES(?,?,'push','Push-approved device',1,'active') ON CONFLICT(phone,device_hash) DO UPDATE SET status='active',revoked_at=NULL,last_seen_at=CURRENT_TIMESTAMP`,[phone,String(challenge.target_device_hash)]);return undefined;});await emitProgressiveTrustEvent('trust.challenge.approved',phone,{challengeId:input.challengeId,status:'approved'},`challenge:${input.challengeId}`);return{approved:true,targetDeviceIdHash:String(challenge.target_device_hash)};}
export async function recordChannelEvidence(input:{phone:string;channel:ChannelEvidenceType;evidenceType:string;externalSubject?:string;sourceRef?:string;consented?:boolean}):Promise<void>{if(!isChannelEvidenceEnabled())return;await ensureTrustSchema();const db=await getCanonicalStore();await db.run(`INSERT INTO channel_evidence(phone,channel,evidence_type,external_subject,source_ref,consented,status) VALUES(?,?,?,?,?,?,'observed') ON CONFLICT(phone,channel,evidence_type,external_subject) DO UPDATE SET source_ref=excluded.source_ref,consented=excluded.consented,status='observed',revoked_at=NULL,observed_at=CURRENT_TIMESTAMP`,[String(input.phone||'').trim(),input.channel,String(input.evidenceType||'').slice(0,80),String(input.externalSubject||'').slice(0,256)||null,String(input.sourceRef||'').slice(0,256)||null,input.consented?1:0]);await emitProgressiveTrustEvent('channel.evidence.observed',String(input.phone||'').trim(),{channel:input.channel,evidenceType:String(input.evidenceType||'').slice(0,80),consented:Boolean(input.consented)},`channel:${input.channel}:${String(input.evidenceType||'').slice(0,80)}`);}
export async function recordLocationConsent(input:{phone:string;purpose:string;precision?:'coarse'|'precise';latitude?:number;longitude?:number;area?:string;expiresAt?:string}):Promise<void>{if(!isLocationConsentEnabled())throw new Error('Location consent is not enabled in this deployment.');await ensureTrustSchema();const db=await getCanonicalStore();await db.run(`INSERT INTO location_consents(phone,purpose,precision,latitude,longitude,area,expires_at,status) VALUES(?,?,?,?,?,?,?,'granted')`,[String(input.phone||'').trim(),String(input.purpose||'').slice(0,120),input.precision||'coarse',Number.isFinite(input.latitude)?Number(input.latitude):null,Number.isFinite(input.longitude)?Number(input.longitude):null,String(input.area||'').slice(0,120)||null,input.expiresAt||null]);}
export async function getActiveLocationConsent(phone:string,purposes:string[]=['nearby','network_discovery','fulfilment']):Promise<{purpose:string;precision:'coarse'|'precise';latitude:number;longitude:number;area?:string;expiresAt?:string}|null>{if(!isLocationConsentEnabled())return null;await ensureTrustSchema();const ownerPhone=String(phone||'').trim();if(!ownerPhone)return null;const normalizedPurposes=purposes.map(p=>String(p||'').trim().toLowerCase()).filter(Boolean).slice(0,8);if(!normalizedPurposes.length)return null;const placeholders=normalizedPurposes.map(()=>'?').join(','),db=await getCanonicalStore(),row=await db.one<any>(`SELECT purpose,precision,latitude,longitude,area,expires_at FROM location_consents WHERE phone=? AND status='granted' AND revoked_at IS NULL AND latitude IS NOT NULL AND longitude IS NOT NULL AND (expires_at IS NULL OR expires_at>CURRENT_TIMESTAMP) AND lower(purpose) IN (${placeholders}) ORDER BY created_at DESC,id DESC LIMIT 1`,[ownerPhone,...normalizedPurposes]);if(!row)return null;const latitude=Number(row.latitude),longitude=Number(row.longitude);if(!Number.isFinite(latitude)||!Number.isFinite(longitude))return null;return{purpose:String(row.purpose),precision:String(row.precision)==='precise'?'precise':'coarse',latitude,longitude,area:row.area?String(row.area):undefined,expiresAt:row.expires_at?String(row.expires_at):undefined};}
export async function getProgressiveTrust(phone:string):Promise<{trustedDevices:number;channelEvidence:Array<{channel:string;evidenceType:string;status:string;observedAt:string}>;activeLocationConsents:number}>{await ensureTrustSchema();const db=await getCanonicalStore(),device=await db.one<any>(`SELECT COUNT(*) count FROM trusted_devices WHERE phone=? AND status='active'`,[phone]),evidenceRows=await db.all<any>(`SELECT channel,evidence_type,status,observed_at FROM channel_evidence WHERE phone=? AND status='observed' ORDER BY observed_at DESC`,[phone]),location=await db.one<any>(`SELECT COUNT(*) count FROM location_consents WHERE phone=? AND status='granted' AND (expires_at IS NULL OR expires_at>CURRENT_TIMESTAMP)`,[phone]);return{trustedDevices:Number(device?.count||0),channelEvidence:evidenceRows.map((row:any)=>({channel:String(row.channel),evidenceType:String(row.evidence_type),status:String(row.status),observedAt:String(row.observed_at)})),activeLocationConsents:Number(location?.count||0)};}
export async function getPendingTrustChallenges(phone:string):Promise<Array<{id:string;purpose:string;expiresAt:string;createdAt:string}>>{if(!isPushApprovalEnabled())return[];await ensureTrustSchema();const db=await getCanonicalStore();await expireChallenges(db);const rows=await db.all<any>(`SELECT id,purpose,expires_at,created_at FROM trust_challenges WHERE phone=? AND status='pending' ORDER BY created_at DESC LIMIT 10`,[phone]);return rows.map((row:any)=>({id:String(row.id),purpose:String(row.purpose),expiresAt:String(row.expires_at),createdAt:String(row.created_at)}));}
export async function denyTrustChallenge(input:{phone:string;challengeId:string;approverDeviceId:string}):Promise<{denied:boolean;reason?:string}>{if(!isPushApprovalEnabled())return{denied:false,reason:'push_approval_disabled'};await ensureTrustSchema();const db=await getCanonicalStore();await expireChallenges(db);const approverHash=digest(normalizeDeviceId(input.approverDeviceId)),approver=await db.one<any>(`SELECT id FROM trusted_devices WHERE phone=? AND device_hash=? AND status='active' LIMIT 1`,[input.phone,approverHash]);if(!approver)return{denied:false,reason:'approver_device_not_trusted'};const result=await db.one<any>(`SELECT id FROM trust_challenges WHERE id=? AND phone=? AND status='pending' LIMIT 1`,[input.challengeId,input.phone]);if(!result)return{denied:false,reason:'challenge_not_found_or_expired'};await db.run(`UPDATE trust_challenges SET status='denied',approved_by_device_hash=?,approved_at=CURRENT_TIMESTAMP WHERE id=? AND phone=? AND status='pending'`,[approverHash,input.challengeId,input.phone]);await emitProgressiveTrustEvent('trust.challenge.denied',input.phone,{challengeId:input.challengeId,status:'denied'},`challenge:${input.challengeId}`);return{denied:true};}
export async function listTrustedDevices(phone:string):Promise<Array<{id:number;credentialType:string;label:string;pushCapable:boolean;status:string;createdAt:string;lastSeenAt:string}>>{await ensureTrustSchema();const rows=await(await getCanonicalStore()).all<any>(`SELECT id,credential_type,label,push_capable,status,created_at,last_seen_at FROM trusted_devices WHERE phone=? ORDER BY last_seen_at DESC`,[phone]);return rows.map((row:any)=>({id:Number(row.id),credentialType:String(row.credential_type||'web'),label:String(row.label||'Kurukoo device'),pushCapable:Number(row.push_capable||0)===1,status:String(row.status||'active'),createdAt:String(row.created_at||''),lastSeenAt:String(row.last_seen_at||'')}));}
export async function revokeTrustedDevice(input:{phone:string;deviceRecordId:number;currentDeviceId?:string}):Promise<{revoked:boolean;reason?:string}>{await ensureTrustSchema();const db=await getCanonicalStore(),record=await db.one<any>(`SELECT device_hash FROM trusted_devices WHERE id=? AND phone=? AND status='active' LIMIT 1`,[input.deviceRecordId,input.phone]);if(!record)return{revoked:false,reason:'device_not_found'};if(input.currentDeviceId&&String(record.device_hash)===digest(normalizeDeviceId(input.currentDeviceId)))return{revoked:false,reason:'current_device_requires_reauthentication'};await db.run(`UPDATE trusted_devices SET status='revoked',revoked_at=CURRENT_TIMESTAMP WHERE id=? AND phone=? AND status='active'`,[input.deviceRecordId,input.phone]);await emitProgressiveTrustEvent('trust.device.revoked',input.phone,{deviceRecordId:input.deviceRecordId,status:'revoked'},`device-record:${input.deviceRecordId}`);return{revoked:true};}
