import crypto from 'node:crypto';
import { getCanonicalStore } from './canonicalStore.js';
import { getCanonicalPersistenceMode } from './canonicalPersistence.js';
import { normalizeProviderEntityType, type ProviderEntityType } from './providerEntity.js';

export type ProviderVerificationState='draft'|'submitted'|'review'|'verified'|'rejected'|'suspended'|'expired';
export interface ProviderVerificationRecord { providerPhone:string; entityType:ProviderEntityType; state:ProviderVerificationState; evidence:string[]; reviewerId?:string; reviewedAt?:string; expiresAt?:string; reason?:string; createdAt:string; updatedAt:string; }
async function ensureSchema(){const s=await getCanonicalStore();const pg=getCanonicalPersistenceMode()==='postgres';await s.run(`CREATE TABLE IF NOT EXISTS provider_verification(provider_phone TEXT PRIMARY KEY,entity_type TEXT NOT NULL DEFAULT 'human',state TEXT NOT NULL DEFAULT 'draft',evidence_json TEXT NOT NULL DEFAULT '[]',reviewer_id TEXT,reviewed_at ${pg?'TIMESTAMPTZ':'TEXT'},expires_at ${pg?'TIMESTAMPTZ':'TEXT'},reason TEXT,created_at ${pg?'TIMESTAMPTZ':'TEXT'} DEFAULT CURRENT_TIMESTAMP,updated_at ${pg?'TIMESTAMPTZ':'TEXT'} DEFAULT CURRENT_TIMESTAMP)`);await s.run('CREATE INDEX IF NOT EXISTS idx_provider_verification_state ON provider_verification(state,updated_at DESC)');return s;}
function parseEvidence(value:unknown):string[]{try{const parsed=JSON.parse(String(value||'[]'));return Array.isArray(parsed)?parsed.map(String).slice(0,50):[];}catch{return[];}}
function fromRow(row:any):ProviderVerificationRecord{return{providerPhone:String(row.provider_phone),entityType:normalizeProviderEntityType(row.entity_type),state:String(row.state) as ProviderVerificationState,evidence:parseEvidence(row.evidence_json),reviewerId:row.reviewer_id?String(row.reviewer_id):undefined,reviewedAt:row.reviewed_at?String(row.reviewed_at):undefined,expiresAt:row.expires_at?String(row.expires_at):undefined,reason:row.reason?String(row.reason):undefined,createdAt:String(row.created_at||''),updatedAt:String(row.updated_at||'')};}
export async function ensureProviderVerification(providerPhone:string,entityType:unknown='human'):Promise<ProviderVerificationRecord>{const phone=String(providerPhone||'').trim();if(!phone)throw new Error('provider phone is required');const s=await ensureSchema(),normalizedType=normalizeProviderEntityType(entityType);await s.run(`INSERT INTO provider_verification(provider_phone,entity_type,state) VALUES(?,?,'draft') ON CONFLICT(provider_phone) DO NOTHING`,[phone,normalizedType]);await s.run(`UPDATE provider_verification SET entity_type=?,updated_at=CURRENT_TIMESTAMP WHERE provider_phone=?`,[normalizedType,phone]);const row=await s.one<any>('SELECT * FROM provider_verification WHERE provider_phone=? LIMIT 1',[phone]);if(!row)throw new Error('Provider verification could not be loaded');return fromRow(row);}
export async function submitProviderVerification(input:{providerPhone:string;entityType?:unknown;evidence:string[]}):Promise<ProviderVerificationRecord>{const current=await ensureProviderVerification(input.providerPhone,input.entityType);if(['verified','suspended'].includes(current.state))return current;const evidence=Array.from(new Set((input.evidence||[]).map(String).map(v=>v.trim()).filter(Boolean))).slice(0,50),s=await ensureSchema();await s.run(`UPDATE provider_verification SET state=?,evidence_json=?,reason=NULL,updated_at=CURRENT_TIMESTAMP WHERE provider_phone=?`,[evidence.length?'submitted':'draft',JSON.stringify(evidence),current.providerPhone]);return(await getProviderVerification(current.providerPhone))!;}
export async function reviewProviderVerification(input:{providerPhone:string;reviewerId:string;decision:'verified'|'rejected'|'suspended';reason?:string;expiresAt?:string}):Promise<ProviderVerificationRecord>{const current=await ensureProviderVerification(input.providerPhone),reviewerId=String(input.reviewerId||'').trim();if(!reviewerId)throw new Error('reviewer identity is required');if(!['submitted','review','verified','rejected','suspended'].includes(current.state))throw new Error(`provider verification cannot be reviewed from ${current.state}`);const expiresAt=input.decision==='verified'?(input.expiresAt||new Date(Date.now()+365*24*60*60*1000).toISOString()):null,s=await ensureSchema();await s.transaction(async tx=>{await tx.run(`UPDATE provider_verification SET state=?,reviewer_id=?,reviewed_at=CURRENT_TIMESTAMP,expires_at=?,reason=?,updated_at=CURRENT_TIMESTAMP WHERE provider_phone=?`,[input.decision,reviewerId,expiresAt,input.reason?String(input.reason).slice(0,500):null,current.providerPhone]);if(input.decision==='verified')await tx.run(`UPDATE memory_profiles SET verified_provider=1,updated_at=CURRENT_TIMESTAMP WHERE phone=?`,[current.providerPhone]);else if(input.decision==='suspended'||input.decision==='rejected')await tx.run(`UPDATE memory_profiles SET verified_provider=0,updated_at=CURRENT_TIMESTAMP WHERE phone=?`,[current.providerPhone]);});return(await getProviderVerification(current.providerPhone))!;}
export async function getProviderVerification(providerPhone:string):Promise<ProviderVerificationRecord|null>{const s=await ensureSchema(),row=await s.one<any>('SELECT * FROM provider_verification WHERE provider_phone=? LIMIT 1',[String(providerPhone)]);return row?fromRow(row):null;}
export async function listProviderVerifications(state?:ProviderVerificationState,limit=50):Promise<ProviderVerificationRecord[]>{const s=await ensureSchema(),safeLimit=Math.max(1,Math.min(200,Math.floor(Number(limit)||50))),rows=state?await s.all<any>('SELECT * FROM provider_verification WHERE state=? ORDER BY updated_at DESC LIMIT ?',[state,safeLimit]):await s.all<any>('SELECT * FROM provider_verification ORDER BY updated_at DESC LIMIT ?',[safeLimit]);return rows.map(fromRow);}
export async function expireProviderVerifications(now=new Date()):Promise<number>{const s=await ensureSchema(),result=await s.run(`UPDATE provider_verification SET state='expired',updated_at=CURRENT_TIMESTAMP WHERE state='verified' AND expires_at IS NOT NULL AND expires_at <= ?`,[now.toISOString()]);if(result.rowCount)await s.run(`UPDATE memory_profiles SET verified_provider=0,updated_at=CURRENT_TIMESTAMP WHERE phone IN (SELECT provider_phone FROM provider_verification WHERE state='expired')`);return result.rowCount;}
export function createProviderVerificationEvidenceToken(providerPhone:string):string{return crypto.createHash('sha256').update(`${providerPhone}:${process.env.KURUKOO_DATASET_VERSION||'kurukoo-core-v1'}`).digest('hex').slice(0,32);}
