import crypto from 'node:crypto';
import { getCanonicalStore } from './canonicalStore.js';
import { getCanonicalPersistenceMode } from './canonicalPersistence.js';
import { getDiscoveryEntity } from './discoveryNetwork.js';
import { sendFcmPush } from './pushNotifications.js';
export const RELATIONSHIP_TARGET_TYPES=['person','provider','contributor','topic','opportunity','agent','discovery'] as const;
export type RelationshipTargetType=typeof RELATIONSHIP_TARGET_TYPES[number];
export const RELATIONSHIP_TYPES=['follow','subscribe','contact','participant','provider_relationship','safety'] as const;
export type RelationshipType=typeof RELATIONSHIP_TYPES[number];
export type RelationshipStatus='active'|'revoked'|'suppressed';
export type NotificationPreference='all'|'muted';
export type RelationshipVisibility='private'|'contextual';
export interface Relationship{id:string;actorPhone:string;targetType:string;targetId:string;relationshipType:RelationshipType;status:RelationshipStatus;notificationPreference:NotificationPreference;visibility:RelationshipVisibility;context:Record<string,unknown>;createdAt:string;updatedAt:string;revokedAt:string|null;}
export interface RelationshipInput{targetType:unknown;targetId:unknown;relationshipType?:unknown;notificationPreference?:unknown;visibility?:unknown;context?:unknown;}
function parseJsonObject(value:unknown):Record<string,unknown>{if(!value||typeof value!=='string')return{};try{const parsed=JSON.parse(value);return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed as Record<string,unknown>:{};}catch{return{};}}
function cleanTargetType(value:unknown):RelationshipTargetType{const type=typeof value==='string'?value.trim().toLowerCase():'';if(!(RELATIONSHIP_TARGET_TYPES as readonly string[]).includes(type))throw new Error('Unsupported relationship target type');return type as RelationshipTargetType;}
function cleanTargetId(value:unknown):string{const id=typeof value==='string'||typeof value==='number'?String(value).trim():'';if(!id||id.length>180||/[\u0000-\u001f\u007f]/.test(id))throw new Error('A valid relationship target is required');return id;}
function cleanRelationshipType(value:unknown):RelationshipType{const type=typeof value==='string'&&value.trim()?value.trim().toLowerCase():'follow';if(!(RELATIONSHIP_TYPES as readonly string[]).includes(type))throw new Error('Unsupported relationship type');if(type!=='follow'&&type!=='subscribe')throw new Error('This relationship type remains owned by its canonical service');return type as RelationshipType;}
function cleanNotificationPreference(value:unknown):NotificationPreference{const preference=value==null||value===''?'all':String(value).trim().toLowerCase();if(preference!=='all'&&preference!=='muted')throw new Error('notificationPreference must be all or muted');return preference;}
function cleanVisibility(value:unknown):RelationshipVisibility{const visibility=value==null||value===''?'private':String(value).trim().toLowerCase();if(visibility!=='private'&&visibility!=='contextual')throw new Error('visibility must be private or contextual');return visibility;}
function cleanContext(value:unknown):Record<string,unknown>{if(value==null)return{};if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('context must be an object');if(JSON.stringify(value).length>4000)throw new Error('context is too large');return value as Record<string,unknown>;}
function rowToRelationship(row:any):Relationship{return{id:String(row.id),actorPhone:String(row.actor_phone),targetType:String(row.target_type),targetId:String(row.target_id),relationshipType:String(row.relationship_type) as RelationshipType,status:String(row.status) as RelationshipStatus,notificationPreference:String(row.notification_preference||'all') as NotificationPreference,visibility:String(row.visibility||'private') as RelationshipVisibility,context:parseJsonObject(row.context_json),createdAt:String(row.created_at),updatedAt:String(row.updated_at),revokedAt:row.revoked_at==null?null:String(row.revoked_at)};}
export async function ensureRelationshipSchema():Promise<void>{const s=await getCanonicalStore(),pg=getCanonicalPersistenceMode()==='postgres';await s.run(`CREATE TABLE IF NOT EXISTS relationships(id TEXT PRIMARY KEY,actor_phone TEXT NOT NULL,target_type TEXT NOT NULL,target_id TEXT NOT NULL,relationship_type TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',notification_preference TEXT NOT NULL DEFAULT 'all',visibility TEXT NOT NULL DEFAULT 'private',context_json TEXT NOT NULL DEFAULT '{}',created_at ${pg?'TIMESTAMPTZ':'TEXT'} NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at ${pg?'TIMESTAMPTZ':'TEXT'} NOT NULL DEFAULT CURRENT_TIMESTAMP,revoked_at ${pg?'TIMESTAMPTZ':'TEXT'},UNIQUE(actor_phone,target_type,target_id,relationship_type))`);await s.run(`CREATE INDEX IF NOT EXISTS idx_relationships_actor_status ON relationships(actor_phone,status,updated_at DESC)`);await s.run(`CREATE INDEX IF NOT EXISTS idx_relationships_target_status ON relationships(target_type,target_id,status,relationship_type)`);await s.run(`CREATE INDEX IF NOT EXISTS idx_relationships_type_status ON relationships(relationship_type,status,updated_at DESC)`);await s.run(`CREATE TABLE IF NOT EXISTS relationship_blocks(blocker_phone TEXT NOT NULL,blocked_phone TEXT NOT NULL,created_at ${pg?'TIMESTAMPTZ':'TEXT'} NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(blocker_phone,blocked_phone))`);await s.run(`CREATE INDEX IF NOT EXISTS idx_relationship_blocks_blocked ON relationship_blocks(blocked_phone,blocker_phone)`);try{await s.run(`ALTER TABLE memory_profiles ADD COLUMN relationship_visibility TEXT NOT NULL DEFAULT 'private'`);}catch{}if(!pg){try{const legacy=await s.one<any>(`SELECT name FROM sqlite_master WHERE type='table' AND name='discover_interests'`);if(legacy){await s.run(`INSERT INTO relationships(id,actor_phone,target_type,target_id,relationship_type,status,notification_preference,visibility,context_json,created_at,updated_at) SELECT 'legacy-discover-follow:' || id,phone,item_type,item_id,'follow','active','all','private','{}',created_at,updated_at FROM discover_interests WHERE action='follow' ON CONFLICT DO NOTHING`);await s.run(`DELETE FROM discover_interests WHERE action='follow'`);}}catch{}}}
async function resolveTarget(targetType:RelationshipTargetType,targetId:string,actorPhone:string):Promise<void>{const s=await getCanonicalStore();if(targetType==='topic'){if(!await s.one('SELECT id FROM topics WHERE id=? AND status=\'public\' LIMIT 1',[targetId]))throw new Error('Relationship target is not publicly available');return;}if(targetType==='provider'){if(!await s.one(`SELECT p.phone FROM memory_profiles p WHERE p.phone=? AND (p.verified_provider=1 OR EXISTS (SELECT 1 FROM skills s WHERE s.phone=p.phone)) LIMIT 1`,[targetId]))throw new Error('Relationship target is not a public provider');return;}if(targetType==='contributor'){if(!await s.one(`SELECT phone FROM memory_profiles WHERE phone=? AND is_contributor=1 AND COALESCE(relationship_visibility,'private')='public' LIMIT 1`,[targetId]))throw new Error('Relationship target is not a public contributor');return;}if(targetType==='person'){if(targetId===actorPhone)throw new Error('A user cannot follow themself');if(!await s.one(`SELECT phone FROM memory_profiles WHERE phone=? AND COALESCE(relationship_visibility,'private')='public' LIMIT 1`,[targetId]))throw new Error('Relationship target is private or unavailable');return;}if(targetType==='agent'){if(!await s.one(`SELECT id FROM ai_agents WHERE id=? AND status='active' LIMIT 1`,[targetId]))throw new Error('Relationship target is not an eligible agent');return;}if(targetType==='opportunity'){if(!await s.one(`SELECT id FROM proactive_opportunities WHERE id=? AND phone=? AND status!='dismissed' LIMIT 1`,[targetId,actorPhone]))throw new Error('Relationship target is private or unavailable');return;}if(!(await getDiscoveryEntity(targetId)))throw new Error('Relationship target was not found');}
async function assertNotBlocked(actorPhone:string,targetId:string,targetType:RelationshipTargetType):Promise<void>{if(!['person','provider','contributor'].includes(targetType))return;const s=await getCanonicalStore();if(await s.one(`SELECT 1 FROM relationship_blocks WHERE (blocker_phone=? AND blocked_phone=?) OR (blocker_phone=? AND blocked_phone=?) LIMIT 1`,[targetId,actorPhone,actorPhone,targetId]))throw new Error('This relationship is blocked by a privacy boundary');}
async function activeRelationshipFor(actorPhone:string,targetType:string,targetId:string,relationshipType:string):Promise<Relationship|null>{const s=await getCanonicalStore(),row=await s.one<any>('SELECT * FROM relationships WHERE actor_phone=? AND target_type=? AND target_id=? AND relationship_type=? LIMIT 1',[actorPhone,targetType,targetId,relationshipType]);return row?rowToRelationship(row):null;}
export async function createRelationship(actorPhone:string,input:RelationshipInput):Promise<{relationship:Relationship;idempotent:boolean;reactivated:boolean}>{if(!actorPhone||actorPhone.startsWith('anon_'))throw new Error('Authenticated user is required');await ensureRelationshipSchema();const targetType=cleanTargetType(input.targetType),targetId=cleanTargetId(input.targetId),relationshipType=cleanRelationshipType(input.relationshipType),notificationPreference=cleanNotificationPreference(input.notificationPreference),visibility=cleanVisibility(input.visibility),context=cleanContext(input.context);await resolveTarget(targetType,targetId,actorPhone);await assertNotBlocked(actorPhone,targetId,targetType);const s=await getCanonicalStore(),prior=await activeRelationshipFor(actorPhone,targetType,targetId,relationshipType);if(prior?.status==='active')return{relationship:prior,idempotent:true,reactivated:false};if(prior){await s.run(`UPDATE relationships SET status='active',notification_preference=?,visibility=?,context_json=?,revoked_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?`,[notificationPreference,visibility,JSON.stringify(context),prior.id]);const relationship=await activeRelationshipFor(actorPhone,targetType,targetId,relationshipType);if(!relationship)throw new Error('Unable to reactivate relationship');return{relationship,idempotent:false,reactivated:true};}const id=crypto.randomUUID();await s.run(`INSERT INTO relationships(id,actor_phone,target_type,target_id,relationship_type,status,notification_preference,visibility,context_json) VALUES(?,?,?,?,?,'active',?,?,?)`,[id,actorPhone,targetType,targetId,relationshipType,notificationPreference,visibility,JSON.stringify(context)]);const relationship=await activeRelationshipFor(actorPhone,targetType,targetId,relationshipType);if(!relationship)throw new Error('Unable to create relationship');return{relationship,idempotent:false,reactivated:false};}
async function suppressQueuedRelationshipNotifications(relationshipId:string,reason:string):Promise<number>{const s=await getCanonicalStore();return(await s.run(`UPDATE internal_notifications SET delivery_state='suppressed',failure_reason=? WHERE object_type='relationship' AND object_id=? AND delivery_state IN ('queued','accepted','sent','failed')`,[reason,relationshipId])).rowCount;}
export async function revokeRelationship(actorPhone:string,targetTypeValue:unknown,targetIdValue:unknown,relationshipTypeValue:unknown='follow'):Promise<{revoked:boolean;suppressedNotifications:number}>{if(!actorPhone||actorPhone.startsWith('anon_'))throw new Error('Authenticated user is required');await ensureRelationshipSchema();const targetType=cleanTargetType(targetTypeValue),targetId=cleanTargetId(targetIdValue),relationshipType=cleanRelationshipType(relationshipTypeValue),relationship=await activeRelationshipFor(actorPhone,targetType,targetId,relationshipType);if(!relationship||relationship.status!=='active')return{revoked:false,suppressedNotifications:0};const s=await getCanonicalStore(),result=await s.run(`UPDATE relationships SET status='revoked',revoked_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND actor_phone=? AND status='active'`,[relationship.id,actorPhone]);if(!result.rowCount)return{revoked:false,suppressedNotifications:0};return{revoked:true,suppressedNotifications:await suppressQueuedRelationshipNotifications(relationship.id,'relationship_revoked')};}
export async function setRelationshipNotificationPreference(actorPhone:string,targetTypeValue:unknown,targetIdValue:unknown,relationshipTypeValue:unknown,notificationPreferenceValue:unknown):Promise<Relationship|null>{if(!actorPhone||actorPhone.startsWith('anon_'))throw new Error('Authenticated user is required');await ensureRelationshipSchema();const targetType=cleanTargetType(targetTypeValue),targetId=cleanTargetId(targetIdValue),relationshipType=cleanRelationshipType(relationshipTypeValue),notificationPreference=cleanNotificationPreference(notificationPreferenceValue),relationship=await activeRelationshipFor(actorPhone,targetType,targetId,relationshipType);if(!relationship||relationship.status!=='active')return null;const s=await getCanonicalStore(),result=await s.run(`UPDATE relationships SET notification_preference=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND actor_phone=? AND status='active'`,[notificationPreference,relationship.id,actorPhone]);if(!result.rowCount)return null;return activeRelationshipFor(actorPhone,targetType,targetId,relationshipType);}
export async function getRelationshipForActor(actorPhone:string,targetTypeValue:unknown,targetIdValue:unknown,relationshipTypeValue:unknown='follow'):Promise<Relationship|null>{if(!actorPhone||actorPhone.startsWith('anon_'))throw new Error('Authenticated user is required');await ensureRelationshipSchema();return activeRelationshipFor(actorPhone,cleanTargetType(targetTypeValue),cleanTargetId(targetIdValue),cleanRelationshipType(relationshipTypeValue));}
export async function listRelationshipsForActor(actorPhone:string,options:{status?:RelationshipStatus;relationshipType?:RelationshipType;limit?:number}={}):Promise<Relationship[]>{if(!actorPhone||actorPhone.startsWith('anon_'))throw new Error('Authenticated user is required');await ensureRelationshipSchema();const status=options.status||'active',type=options.relationshipType,limit=Math.max(1,Math.min(100,Math.floor(Number(options.limit)||50))),s=await getCanonicalStore(),sql=`SELECT * FROM relationships WHERE actor_phone=? AND status=?${type?' AND relationship_type=?':''} ORDER BY updated_at DESC LIMIT ?`,rows=await s.all<any>(sql,type?[actorPhone,status,type,limit]:[actorPhone,status,limit]);return rows.map(rowToRelationship);}
export async function blockRelationshipActor(blockerPhone:string,blockedPhoneValue:unknown):Promise<boolean>{if(!blockerPhone||blockerPhone.startsWith('anon_'))throw new Error('Authenticated user is required');const blockedPhone=cleanTargetId(blockedPhoneValue);if(blockedPhone===blockerPhone)throw new Error('A user cannot block themself');await ensureRelationshipSchema();const s=await getCanonicalStore();return(await s.run(`INSERT INTO relationship_blocks(blocker_phone,blocked_phone) VALUES(?,?) ON CONFLICT(blocker_phone,blocked_phone) DO NOTHING`,[blockerPhone,blockedPhone])).rowCount>0;}
export async function revokeRelationshipsForTarget(targetTypeValue:unknown,targetIdValue:unknown,reason='target_removed'):Promise<{revoked:number;suppressedNotifications:number}>{await ensureRelationshipSchema();const targetType=cleanTargetType(targetTypeValue),targetId=cleanTargetId(targetIdValue),s=await getCanonicalStore(),ids=(await s.all<any>(`SELECT id FROM relationships WHERE target_type=? AND target_id=? AND status='active'`,[targetType,targetId])).map(row=>String(row.id));if(!ids.length)return{revoked:0,suppressedNotifications:0};await s.run(`UPDATE relationships SET status='suppressed',revoked_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE target_type=? AND target_id=? AND status='active'`,[targetType,targetId]);let suppressedNotifications=0;for(const id of ids)suppressedNotifications+=await suppressQueuedRelationshipNotifications(id,reason);return{revoked:ids.length,suppressedNotifications};}
async function isTargetStillNotifiable(targetType:string,targetId:string):Promise<boolean>{const s=await getCanonicalStore();if(targetType==='topic')return Boolean(await s.one(`SELECT 1 FROM topics WHERE id=? AND status='public' LIMIT 1`,[targetId]));if(targetType==='provider')return Boolean(await s.one(`SELECT 1 FROM memory_profiles p WHERE p.phone=? AND (p.verified_provider=1 OR EXISTS (SELECT 1 FROM skills s WHERE s.phone=p.phone)) LIMIT 1`,[targetId]));if(targetType==='contributor')return Boolean(await s.one(`SELECT 1 FROM memory_profiles WHERE phone=? AND is_contributor=1 AND COALESCE(relationship_visibility,'private')='public' LIMIT 1`,[targetId]));if(targetType==='agent')return Boolean(await s.one(`SELECT 1 FROM ai_agents WHERE id=? AND status='active' LIMIT 1`,[targetId]));if(targetType==='opportunity')return Boolean(await s.one(`SELECT 1 FROM proactive_opportunities WHERE id=? AND status!='dismissed' LIMIT 1`,[targetId]));if(targetType==='discovery')return Boolean(await getDiscoveryEntity(targetId));return false;}
export async function notifyRelationshipTargetUpdate(targetTypeValue:unknown,targetIdValue:unknown,update:{title:string;body:string;link?:string;signature:string}):Promise<{considered:number;queued:number}>{await ensureRelationshipSchema();const targetType=cleanTargetType(targetTypeValue),targetId=cleanTargetId(targetIdValue);if(!(await isTargetStillNotifiable(targetType,targetId)))return{considered:0,queued:0};const s=await getCanonicalStore(),relationships=(await s.all<any>(`SELECT * FROM relationships WHERE target_type=? AND target_id=? AND relationship_type IN ('follow','subscribe') AND status='active' AND notification_preference='all' ORDER BY created_at ASC`,[targetType,targetId])).map(rowToRelationship);for(const relationship of relationships)await sendFcmPush(relationship.actorPhone,update.title.slice(0,160),update.body.slice(0,800),update.link,{objectType:'relationship',objectId:relationship.id,ownerScope:relationship.actorPhone,canonicalAction:'relationship_target_update',idempotencyKey:`relationship:${relationship.id}:${update.signature}`.slice(0,240),surface:'notification'});return{considered:relationships.length,queued:relationships.length};}
export async function recordDiscoverFollow(phone:string,itemType:string,itemId:string):Promise<{relationship:Relationship;idempotent:boolean;reactivated:boolean}>{const targetType=itemType==='topic'?'topic':itemType==='discovery'?'discovery':null;if(!targetType)throw new Error('This Discover item does not support a reusable follow relationship');return createRelationship(phone,{targetType,targetId:itemId,relationshipType:'follow'});}
export async function removeDiscoverFollow(phone:string,itemType:string,itemId:string):Promise<{revoked:boolean;suppressedNotifications:number}>{const targetType=itemType==='topic'?'topic':itemType==='discovery'?'discovery':null;if(!targetType)throw new Error('This Discover item does not support a reusable follow relationship');return revokeRelationship(phone,targetType,itemId,'follow');}
