import crypto from 'node:crypto';
import { getCanonicalStore } from './canonicalStore.js';
import { persistCoordinatorEvent } from './coordinatorStore.js';
export interface SafetyContact{id:string;owner_phone:string;name:string;phone:string;relationship:string|null;status:'active'|'pending'|'revoked';created_at:string}
export interface CheckIn{id:string;owner_phone:string;contact_id:string;check_in_at:string;expires_at:string;status:'active'|'completed'|'escalation_pending'|'cancelled';route_note:string|null}
async function ensureSafetySchema(){const store=await getCanonicalStore();if(process.env.KURUKOO_DATABASE_MODE==='postgres'){await store.run(`CREATE TABLE IF NOT EXISTS user_safety_contacts(id TEXT PRIMARY KEY,owner_phone TEXT NOT NULL,name TEXT NOT NULL,phone TEXT NOT NULL,relationship TEXT,status TEXT NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,UNIQUE(owner_phone,phone))`);await store.run(`CREATE TABLE IF NOT EXISTS safety_checkins(id TEXT PRIMARY KEY,owner_phone TEXT NOT NULL,contact_id TEXT NOT NULL,check_in_at TIMESTAMPTZ NOT NULL,expires_at TIMESTAMPTZ NOT NULL,status TEXT NOT NULL DEFAULT 'active',route_note TEXT)`);}else{await store.run(`CREATE TABLE IF NOT EXISTS user_safety_contacts(id TEXT PRIMARY KEY,owner_phone TEXT NOT NULL,name TEXT NOT NULL,phone TEXT NOT NULL,relationship TEXT,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(owner_phone,phone))`);await store.run(`CREATE TABLE IF NOT EXISTS safety_checkins(id TEXT PRIMARY KEY,owner_phone TEXT NOT NULL,contact_id TEXT NOT NULL,check_in_at TEXT NOT NULL,expires_at TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',route_note TEXT)`);}await store.run('CREATE INDEX IF NOT EXISTS idx_safety_contacts_owner ON user_safety_contacts(owner_phone,status)');await store.run('CREATE INDEX IF NOT EXISTS idx_safety_checkins_due ON safety_checkins(expires_at,status)');return store}
async function emitCheckInEvent(c:CheckIn,status:CheckIn['status'],payload:Record<string,unknown>={}){await persistCoordinatorEvent({id:`safety-checkin:${c.id}:state:${status}:${Date.now()}`,type:'safety.checkin.state_changed',occurredAt:new Date().toISOString(),producer:'safetyService',correlationId:`safety_checkin:${c.id}`,ownerPhone:c.owner_phone.startsWith('anon_')?undefined:c.owner_phone,payload:{checkInId:c.id,status,contactId:c.contact_id,expiresAt:c.expires_at,hasRouteNote:Boolean(c.route_note),...payload},sensitivity:c.owner_phone.startsWith('anon_')?'public':'personal',provenance:{source:'canonical_service',sourceId:c.id,evidenceLevel:'persisted_state'},policy:{autonomousAllowed:false,confirmationRequired:'none'},schemaVersion:1})}
export async function addSafetyContact(ownerPhone:string,input:{name:string;phone:string;relationship?:string;activate?:boolean}){const s=await ensureSafetySchema();if(!input.name.trim()||!input.phone.trim())throw new Error('Contact name and phone are required');const id=crypto.randomUUID();await s.run(`INSERT INTO user_safety_contacts(id,owner_phone,name,phone,relationship,status) VALUES(?,?,?,?,?,?) ON CONFLICT(owner_phone,phone) DO UPDATE SET name=excluded.name,relationship=excluded.relationship,status=excluded.status`,[id,ownerPhone,input.name.trim(),input.phone.trim(),input.relationship?.trim()||null,input.activate?'active':'pending']);const c=await s.one<SafetyContact>('SELECT * FROM user_safety_contacts WHERE owner_phone=? AND phone=?',[ownerPhone,input.phone.trim()]);if(!c)throw new Error('Unable to save safety contact');return c}
export async function listSafetyContacts(ownerPhone:string){return(await ensureSafetySchema()).all<SafetyContact>(`SELECT * FROM user_safety_contacts WHERE owner_phone=? AND status!='revoked' ORDER BY created_at ASC`,[ownerPhone])}
export async function revokeSafetyContact(ownerPhone:string,contactId:string){return(await ensureSafetySchema()).run(`UPDATE user_safety_contacts SET status='revoked' WHERE id=? AND owner_phone=?`,[contactId,ownerPhone]).then(r=>r.rowCount>0)}
export async function activateSafetyContact(ownerPhone:string,contactId:string,consentConfirmed:boolean):Promise<SafetyContact|null>{if(!consentConfirmed)throw new Error('Explicit owner consent is required to activate a safety contact');const s=await ensureSafetySchema();await s.run(`UPDATE user_safety_contacts SET status='active' WHERE id=? AND owner_phone=? AND status='pending'`,[contactId,ownerPhone]);return(await s.one<SafetyContact>(`SELECT * FROM user_safety_contacts WHERE id=? AND owner_phone=? AND status='active'`,[contactId,ownerPhone]))||null}
export async function startCheckIn(ownerPhone:string,input:{contactId:string;durationMinutes:number;routeNote?:string}){const s=await ensureSafetySchema(),duration=Math.max(5,Math.min(1440,Math.floor(Number(input.durationMinutes)))),contact=await s.one('SELECT id FROM user_safety_contacts WHERE id=? AND owner_phone=? AND status=\'active\'',[input.contactId,ownerPhone]);if(!contact)throw new Error('Active safety contact not found');const id=crypto.randomUUID(),start=new Date(),expires=new Date(start.getTime()+duration*60000),c:CheckIn={id,owner_phone:ownerPhone,contact_id:input.contactId,check_in_at:start.toISOString(),expires_at:expires.toISOString(),status:'active',route_note:input.routeNote?.trim()||null};await s.run(`INSERT INTO safety_checkins(id,owner_phone,contact_id,check_in_at,expires_at,status,route_note) VALUES(?,?,?,?,?,'active',?)`,[id,ownerPhone,input.contactId,start.toISOString(),expires.toISOString(),c.route_note]);await emitCheckInEvent(c,'active',{action:'started'});return c}
export async function completeCheckIn(ownerPhone:string,id:string){const s=await ensureSafetySchema(),r=await s.run(`UPDATE safety_checkins SET status='completed' WHERE id=? AND owner_phone=? AND status='active'`,[id,ownerPhone]);if(!r.rowCount)return false;const c=await s.one<CheckIn>('SELECT * FROM safety_checkins WHERE id=? AND owner_phone=?',[id,ownerPhone]);if(c)await emitCheckInEvent(c,'completed',{action:'completed'});return true}
export async function listCheckIns(ownerPhone:string){return(await ensureSafetySchema()).all<CheckIn>('SELECT * FROM safety_checkins WHERE owner_phone=? ORDER BY check_in_at DESC',[ownerPhone])}
export async function handleSafetyContactInput(phone:string,text:string){const s=await getCanonicalStore(),row=await s.one<any>('SELECT preferences FROM memory_profiles WHERE phone=?',[phone]);let prefs:any={};try{prefs=row?.preferences?JSON.parse(String(row.preferences)):{};}catch{}const state=prefs.safety_capture_state,data=prefs.safety_capture_data||{};if(state==='awaiting_phone'){const n=text.trim().replace(/\D/g,'');if(n.length<10)return{reply:"That doesn't look like a valid phone number. Please enter the full phone number for your contact."};const full=n.startsWith('0')?`+234${n.slice(1)}`:n.startsWith('+')?n:`+234${n}`;try{await addSafetyContact(phone,{name:data.name,phone:full});delete prefs.safety_capture_state;delete prefs.safety_capture_data;await s.run('UPDATE memory_profiles SET preferences=?,updated_at=CURRENT_TIMESTAMP WHERE phone=?',[JSON.stringify(prefs),phone]);return{reply:`Saved. **${data.name}** (${full}) has been added as a pending safety contact. They need to confirm consent before you can start check-ins with them.`,success:true,cardData:{type:'safety_contact_added',name:data.name}}}catch(e:any){return{reply:`I couldn't save that contact: ${e.message}. Please try again.`}}}return{reply:"I'm not sure how to help with that safety step."}}
export async function setSafetyCaptureState(phone:string,state:string,data:any={}){const s=await getCanonicalStore(),row=await s.one<any>('SELECT preferences FROM memory_profiles WHERE phone=?',[phone]);let prefs:any={};try{prefs=row?.preferences?JSON.parse(String(row.preferences)):{};}catch{}prefs.safety_capture_state=state;prefs.safety_capture_data=data;await s.run('UPDATE memory_profiles SET preferences=?,updated_at=CURRENT_TIMESTAMP WHERE phone=?',[JSON.stringify(prefs),phone])}
export async function processExpiredCheckIns(){const s=await ensureSafetySchema(),now=new Date().toISOString(),rows=await s.all<CheckIn>(`SELECT * FROM safety_checkins WHERE status='active' AND expires_at<=?`,[now]);for(const r of rows){await s.run(`UPDATE safety_checkins SET status='escalation_pending' WHERE id=?`,[r.id]);r.status='escalation_pending';await emitCheckInEvent(r,'escalation_pending',{action:'expired',externalEscalation:'not_claimed'})}return rows.length}
