import crypto from 'node:crypto';
import { persistCoordinatorEvent } from './coordinatorStore.js';
import { getCanonicalStore } from './canonicalStore.js';
import { getCanonicalPersistenceMode } from './canonicalPersistence.js';
import { getProfile, updateProfile } from './memoryProfile.js';

export interface SafetyContact{id:string;owner_phone:string;name:string;phone:string;relationship:string|null;status:'active'|'pending'|'revoked';created_at:string;}
export interface CheckIn{id:string;owner_phone:string;contact_id:string;check_in_at:string;expires_at:string;status:'active'|'completed'|'escalation_pending'|'cancelled';route_note:string|null;}
async function emitCheckInEvent(checkIn:CheckIn,status:CheckIn['status'],payload:Record<string,unknown>={}){await persistCoordinatorEvent({id:`safety-checkin:${checkIn.id}:state:${status}:${Date.now()}`,type:'safety.checkin.state_changed',occurredAt:new Date().toISOString(),producer:'safetyService',correlationId:`safety_checkin:${checkIn.id}`,ownerPhone:checkIn.owner_phone.startsWith('anon_')?undefined:checkIn.owner_phone,payload:{checkInId:checkIn.id,status,contactId:checkIn.contact_id,expiresAt:checkIn.expires_at,hasRouteNote:Boolean(checkIn.route_note),...payload},sensitivity:checkIn.owner_phone.startsWith('anon_')?'public':'personal',provenance:{source:'canonical_service',sourceId:checkIn.id,evidenceLevel:'persisted_state'},policy:{autonomousAllowed:false,confirmationRequired:'none'},schemaVersion:1});}
async function ensureSafetySchema(){const s=await getCanonicalStore();if(getCanonicalPersistenceMode()==='postgres'){await s.run(`CREATE TABLE IF NOT EXISTS user_safety_contacts(id TEXT PRIMARY KEY,owner_phone TEXT NOT NULL,name TEXT NOT NULL,phone TEXT NOT NULL,relationship TEXT,status TEXT NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,UNIQUE(owner_phone,phone))`);await s.run(`CREATE TABLE IF NOT EXISTS safety_checkins(id TEXT PRIMARY KEY,owner_phone TEXT NOT NULL,contact_id TEXT NOT NULL,check_in_at TIMESTAMPTZ NOT NULL,expires_at TIMESTAMPTZ NOT NULL,status TEXT NOT NULL DEFAULT 'active',route_note TEXT)`);}else{await s.run(`CREATE TABLE IF NOT EXISTS user_safety_contacts(id TEXT PRIMARY KEY,owner_phone TEXT NOT NULL,name TEXT NOT NULL,phone TEXT NOT NULL,relationship TEXT,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(owner_phone,phone))`);await s.run(`CREATE TABLE IF NOT EXISTS safety_checkins(id TEXT PRIMARY KEY,owner_phone TEXT NOT NULL,contact_id TEXT NOT NULL,check_in_at TEXT NOT NULL,expires_at TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',route_note TEXT)`);}await s.run('CREATE INDEX IF NOT EXISTS idx_safety_contacts_owner ON user_safety_contacts(owner_phone,status)');await s.run('CREATE INDEX IF NOT EXISTS idx_safety_checkins_due ON safety_checkins(expires_at,status)');return s;}
export async function addSafetyContact(ownerPhone:string,input:{name:string;phone:string;relationship?:string;activate?:boolean}):Promise<SafetyContact>{if(!input.name.trim()||!input.phone.trim())throw new Error('Contact name and phone are required');const s=await ensureSafetySchema();const id=crypto.randomUUID();await s.run(`INSERT INTO user_safety_contacts(id,owner_phone,name,phone,relationship,status) VALUES(?,?,?,?,?,?) ON CONFLICT(owner_phone,phone) DO UPDATE SET name=excluded.name,relationship=excluded.relationship,status=excluded.status`,[id,ownerPhone,input.name.trim(),input.phone.trim(),input.relationship?.trim()||null,input.activate?'active':'pending']);const row=await s.one<any>('SELECT * FROM user_safety_contacts WHERE owner_phone=? AND phone=?',[ownerPhone,input.phone.trim()]);if(!row)throw new Error('Unable to save safety contact');return row as SafetyContact;}
export async function listSafetyContacts(ownerPhone:string){const s=await ensureSafetySchema();return s.all<SafetyContact>(`SELECT * FROM user_safety_contacts WHERE owner_phone=? AND status!='revoked' ORDER BY created_at ASC`,[ownerPhone]);}
export async function revokeSafetyContact(ownerPhone:string,contactId:string){const s=await ensureSafetySchema();return (await s.run("UPDATE user_safety_contacts SET status='revoked' WHERE id=? AND owner_phone=?",[contactId,ownerPhone])).rowCount>0;}
export async function activateSafetyContact(ownerPhone:string,contactId:string,consentConfirmed:boolean){if(!consentConfirmed)throw new Error('Explicit owner consent is required to activate a safety contact');const s=await ensureSafetySchema();await s.run("UPDATE user_safety_contacts SET status='active' WHERE id=? AND owner_phone=? AND status='pending'",[contactId,ownerPhone]);return (await s.one<SafetyContact>("SELECT * FROM user_safety_contacts WHERE id=? AND owner_phone=? AND status='active'",[contactId,ownerPhone]))||null;}
export async function startCheckIn(ownerPhone:string,input:{contactId:string;durationMinutes:number;routeNote?:string}):Promise<CheckIn>{const s=await ensureSafetySchema();const duration=Math.max(5,Math.min(1440,Math.floor(Number(input.durationMinutes))));if(!await s.one('SELECT id FROM user_safety_contacts WHERE id=? AND owner_phone=? AND status=\'active\'',[input.contactId,ownerPhone]))throw new Error('Active safety contact not found');const id=crypto.randomUUID(),start=new Date(),expires=new Date(start.getTime()+duration*60000),routeNote=input.routeNote?.trim()||null;await s.run(`INSERT INTO safety_checkins(id,owner_phone,contact_id,check_in_at,expires_at,status,route_note) VALUES(?,?,?,?,?,'active',?)`,[id,ownerPhone,input.contactId,start.toISOString(),expires.toISOString(),routeNote]);const checkIn={id,owner_phone:ownerPhone,contact_id:input.contactId,check_in_at:start.toISOString(),expires_at:expires.toISOString(),status:'active' as const,route_note:routeNote};await emitCheckInEvent(checkIn,'active',{action:'started'});return checkIn;}
export async function completeCheckIn(ownerPhone:string,id:string){const s=await ensureSafetySchema();const result=await s.run("UPDATE safety_checkins SET status='completed' WHERE id=? AND owner_phone=? AND status='active'",[id,ownerPhone]);if(result.rowCount===0)return false;const row=await s.one<any>("SELECT * FROM safety_checkins WHERE id=? AND owner_phone=? AND status='completed'",[id,ownerPhone]);if(!row)return false;await emitCheckInEvent(row as CheckIn,'completed',{action:'completed'});return true;}
export async function listCheckIns(ownerPhone:string){const s=await ensureSafetySchema();return s.all<CheckIn>('SELECT * FROM safety_checkins WHERE owner_phone=? ORDER BY check_in_at DESC',[ownerPhone]);}
export async function handleSafetyContactInput(phone:string,text:string){const profile=await getProfile(phone,'safety_contact_capture');const prefs={...(profile?.preferences||{})};const state=prefs.safety_capture_state||'none';const data=prefs.safety_capture_data||{};if(state==='awaiting_phone'){const digits=text.trim().replace(/\D/g,'');if(digits.length<10)return{reply:"That doesn't look like a valid phone number. Please enter the full phone number for your contact."};const fullPhone=digits.startsWith('0')?'+234'+digits.slice(1):digits.startsWith('+')?digits:'+234'+digits;try{await addSafetyContact(phone,{name:String(data.name||'Contact'),phone:fullPhone});delete prefs.safety_capture_state;delete prefs.safety_capture_data;await updateProfile(phone,'safety_contact_capture',{preferences:prefs});return{reply:`Saved. **${data.name}** (${fullPhone}) has been added as a pending safety contact. They need to confirm consent before you can start check-ins with them.`,success:true,cardData:{type:'safety_contact_added',name:data.name}};}catch(error){return{reply:`I couldn't save that contact: ${error instanceof Error?error.message:'Unable to save contact'}. Please try again.`};}}return{reply:"I'm not sure how to help with that safety step."};}
export async function setSafetyCaptureState(phone:string,state:string,data:any={}):Promise<void>{const profile=await getProfile(phone,'safety_capture_state');const preferences={...(profile?.preferences||{}),safety_capture_state:state,safety_capture_data:data};await updateProfile(phone,'safety_capture_state',{preferences});}
export async function processExpiredCheckIns(){const s=await ensureSafetySchema();const rows=await s.all<any>("SELECT * FROM safety_checkins WHERE status='active' AND expires_at <= ?",[new Date().toISOString()]);for(const row of rows){await s.run("UPDATE safety_checkins SET status='escalation_pending' WHERE id=?",[row.id]);await emitCheckInEvent(row as CheckIn,'escalation_pending',{action:'expired',externalDelivery:'not_claimed'});}return rows.length;}
