import { getCanonicalStore } from './canonicalStore.js';
import { addPoints as addCredits } from './pointsEngine.js';

export interface SurveyPrompt { question:string; options:string[]; image?:string; }
export function getSurveyPrompt(topic:string):SurveyPrompt{return{question:`Would you ever buy ${topic} if we negotiated a bulk discount near you?`,options:['Yes, definitely','No']};}
let surveyInterval:NodeJS.Timeout|null=null;
export function startSurveyScheduler():void{if(surveyInterval)return;console.log('Survey Engine Hourly Scheduler has started successfully.');surveyInterval=setInterval(async()=>{try{await dispatchSurveySweep();}catch(err){console.error('Error running hourly survey sweep:',err);}},60*60*1000);}
export async function dispatchSurveySweep():Promise<void>{const db=await getCanonicalStore();const users=await db.all<any>('SELECT phone,preferences FROM memory_profiles WHERE is_available=1 LIMIT 5');const itemRows=await db.all<any>('SELECT item FROM survey_inventory LIMIT 3');const items=itemRows.map(r=>String(r.item||'')).filter(Boolean);if(items.length===0)items.push('50kg Bag of Rice','Cooking Palm Oil','Tubers of Yam');for(const user of users){const item=items[Math.floor(Math.random()*items.length)],prompt=getSurveyPrompt(item),card=JSON.stringify({type:'survey',question:prompt.question,options:prompt.options});await db.run('INSERT INTO sent_questions(phone,question) VALUES(?,?)',[String(user.phone),prompt.question]);await db.run(`INSERT INTO messages(phone,sender,content,channel,card_data) VALUES(?,'assistant',?,'pwa',?)`,[String(user.phone),`Survey: ${prompt.question}`,card]);}}
export async function submitSurveyResponse(phone:string,question:string,answer:string):Promise<{success:boolean;reward:number}>{const db=await getCanonicalStore();const row=await db.one<any>('SELECT preferences FROM memory_profiles WHERE phone=?',[phone]);let preferences:any={};if(row?.preferences){try{preferences=JSON.parse(String(row.preferences));}catch{preferences={};}}preferences.survey_answers=preferences.survey_answers||{};preferences.survey_answers[question]=answer;await db.run('UPDATE memory_profiles SET preferences=?,updated_at=CURRENT_TIMESTAMP WHERE phone=?',[JSON.stringify(preferences),phone]);await addCredits(phone,1,`Earned +1 Credit for responding to survey: "${question}"`);return{success:true,reward:1};}
