import { randomUUID } from 'crypto';
import { getCanonicalStore } from './canonicalStore.js';
import { ECONOMIC_CATEGORIES, getEconomicCategory, getKnownSkills } from './skillFlows.js';
import { addRedirect } from './seoService.js';
import { notifyRelationshipTargetUpdate, revokeRelationshipsForTarget } from './relationshipService.js';
export const TOPIC_TYPES=['question','opinion','guide','review','local_report','price_report','recommendation','meme','poll','event','alert','opportunity','experience'] as const;
export type TopicType=typeof TOPIC_TYPES[number]; export type TopicStatus='draft'|'submitted'|'public'|'restricted'|'removed'; export type ReplyStatus='submitted'|'public'|'restricted'|'removed';
export interface TopicInput{title:unknown;body:unknown;type?:unknown;category?:unknown;skills?:unknown;city?:unknown;lga?:unknown;idempotencyKey?:unknown;} export interface TopicReplyInput{body:unknown;} export interface TopicModerationInput{decision:unknown;note?:unknown;}
const TOPIC_SELECT=`SELECT t.id,t.slug,t.author_phone,t.title,t.body,t.type,t.category,t.skills_json,t.city,t.lga,t.status,t.moderation_note,t.created_at,t.updated_at,t.published_at,(SELECT COUNT(*) FROM topic_replies r WHERE r.topic_id=t.id AND r.status='public') AS public_reply_count FROM topics t`;
function cleanText(value:unknown,field:string,min:number,max:number):string{if(typeof value!=='string')throw new Error(`${field} is required`);const clean=value.replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim();if(clean.length<min||clean.length>max)throw new Error(`${field} must be between ${min} and ${max} characters`);return clean;}
function optionalBroadLocality(value:unknown,field:string):string|null{if(value==null||value==='')return null;const clean=cleanText(value,field,2,80);if(/\d{3,}|\b(latitude|longitude|coordinates?|address|street|road|house|flat|apartment)\b/i.test(clean))throw new Error(`${field} must be broad city or LGA context, not a precise address or coordinate`);return clean;}
function normalizeSkills(value:unknown):string[]{if(value==null)return[];if(!Array.isArray(value))throw new Error('skills must be an array');if(value.length>3)throw new Error('A Topic may reference at most three existing skills');const valid=new Set(getKnownSkills()),normalized=[...new Set(value.map(skill=>String(skill||'').trim().toLowerCase()).filter(Boolean))];if(normalized.length!==value.length||normalized.some(skill=>!valid.has(skill)))throw new Error('Each skill must be an existing Kurukoo skill');return normalized;}
function normalizeInput(input:TopicInput){const title=cleanText(input.title,'title',12,160),body=cleanText(input.body,'body',30,8000),type=String(input.type||'question').trim().toLowerCase() as TopicType;if(!TOPIC_TYPES.includes(type))throw new Error('type must be a supported Topic type');const category=input.category==null||input.category===''?null:String(input.category).trim().toLowerCase();if(category&&!(ECONOMIC_CATEGORIES as readonly string[]).includes(category))throw new Error('category must be an existing Kurukoo category');const skills=normalizeSkills(input.skills);if(category&&skills.some(skill=>getEconomicCategory(skill)!==category))throw new Error('Each selected skill must belong to the selected category');return{title,body,type,category,skills,city:optionalBroadLocality(input.city,'city'),lga:optionalBroadLocality(input.lga,'lga')};}
function toSlug(title:string):string{const candidate=title.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,72);return candidate||'topic';}
async function uniqueSlug(title:string,excludeId?:string):Promise<string>{const s=await getCanonicalStore(),stem=toSlug(title);let slug=stem;for(let attempt=2;attempt<10000;attempt++){const exists=await s.one(excludeId?'SELECT 1 FROM topics WHERE slug=? AND id<>? LIMIT 1':'SELECT 1 FROM topics WHERE slug=? LIMIT 1',excludeId?[slug,excludeId]:[slug]);if(!exists)return slug;slug=`${stem}-${attempt}`;}throw new Error('Unable to allocate a Topic URL');}
function parseTopic(row:any,includeOwner=false){const publicTopic={id:String(row.id),slug:String(row.slug),title:String(row.title),body:String(row.body),type:String(row.type) as TopicType,category:row.category?String(row.category):null,skills:JSON.parse(String(row.skills_json||'[]')) as string[],city:row.city?String(row.city):null,lga:row.lga?String(row.lga):null,status:String(row.status) as TopicStatus,createdAt:String(row.created_at),updatedAt:String(row.updated_at),publishedAt:row.published_at?String(row.published_at):null,replyCount:Number(row.public_reply_count||0),authorLabel:'Community member'};return includeOwner?{...publicTopic,authorPhone:String(row.author_phone),moderationNote:row.moderation_note?String(row.moderation_note):null}:publicTopic;}
function parseReply(row:any,includeOwner=false){const reply={id:String(row.id),topicId:String(row.topic_id),body:String(row.body),status:String(row.status) as ReplyStatus,createdAt:String(row.created_at),updatedAt:String(row.updated_at),authorLabel:'Community member'};return includeOwner?{...reply,authorPhone:String(row.author_phone),moderationNote:row.moderation_note?String(row.moderation_note):null}:reply;}
async function existingTopicById(id:string){return(await getCanonicalStore()).one<any>(`${TOPIC_SELECT} WHERE t.id=? LIMIT 1`,[id]);}
function validIdempotencyKey(value:unknown):string|null{if(typeof value!=='string')return null;const key=value.trim();return/^[A-Za-z0-9_-]{16,160}$/.test(key)?key:null;}
function isUniqueConstraint(error:unknown){return/unique|constraint/i.test(error instanceof Error?error.message:String(error||''));}
async function existingTopicBySlug(slug:string){return(await getCanonicalStore()).one<any>(`${TOPIC_SELECT} WHERE t.slug=? LIMIT 1`,[slug]);}
export async function createTopic(authorPhone:string,input:TopicInput,suppliedIdempotencyKey?:unknown){const clean=normalizeInput(input),idempotencyKey=validIdempotencyKey(suppliedIdempotencyKey??input.idempotencyKey),s=await getCanonicalStore();if(idempotencyKey){const row=await s.one<any>('SELECT topic_id FROM topic_idempotency_keys WHERE author_phone=? AND idempotency_key=? LIMIT 1',[authorPhone,idempotencyKey]);if(row?.topic_id){const prior=await getTopicForOwner(String(row.topic_id),authorPhone);if(prior)return{...prior,idempotent:true};}}const id=randomUUID();let created=false,lastError:unknown=null;for(let attempt=0;attempt<5&&!created;attempt++){const slug=await uniqueSlug(clean.title);try{await s.run(`INSERT INTO topics(id,slug,author_phone,title,body,type,category,skills_json,city,lga,status) VALUES(?,?,?,?,?,?,?,?,?,?,'submitted')`,[id,slug,authorPhone,clean.title,clean.body,clean.type,clean.category,JSON.stringify(clean.skills),clean.city,clean.lga]);created=true;}catch(error){lastError=error;if(!isUniqueConstraint(error))throw error;}}if(!created)throw new Error(lastError instanceof Error?lastError.message:'Unable to create Topic');if(idempotencyKey){try{await s.run('INSERT INTO topic_idempotency_keys(author_phone,idempotency_key,topic_id) VALUES(?,?,?)',[authorPhone,idempotencyKey,id]);}catch(error){if(!isUniqueConstraint(error))throw error;const row=await s.one<any>('SELECT topic_id FROM topic_idempotency_keys WHERE author_phone=? AND idempotency_key=? LIMIT 1',[authorPhone,idempotencyKey]);if(row?.topic_id&&String(row.topic_id)!==id){await s.run('DELETE FROM topics WHERE id=?',[id]);const prior=await getTopicForOwner(String(row.topic_id),authorPhone);if(prior)return{...prior,idempotent:true};}}}const topic=await getTopicForOwner(id,authorPhone);return topic?{...topic,idempotent:false}:topic;}
export async function createTopicDraft(authorPhone:string,input:TopicInput){const clean=normalizeInput(input),s=await getCanonicalStore(),id=randomUUID();for(let attempt=0;attempt<5;attempt++){try{const slug=await uniqueSlug(clean.title);await s.run(`INSERT INTO topics(id,slug,author_phone,title,body,type,category,skills_json,city,lga,status) VALUES(?,?,?,?,?,?,?,?,?,?,'draft')`,[id,slug,authorPhone,clean.title,clean.body,clean.type,clean.category,JSON.stringify(clean.skills),clean.city,clean.lga]);return getTopicForOwner(id,authorPhone);}catch(error){if(!isUniqueConstraint(error))throw error;}}throw new Error('Unable to save Topic draft');}
export async function updateTopic(authorPhone:string,id:string,input:TopicInput){const clean=normalizeInput(input),s=await getCanonicalStore(),current=await existingTopicById(id);if(!current)throw new Error('Topic not found');if(String(current.author_phone)!==authorPhone)throw new Error('Topic ownership is required');if(!['draft','submitted','restricted'].includes(String(current.status)))throw new Error('Only non-public Topics may be edited; create a new Topic to correct published context');const priorSlug=String(current.slug),nextSlug=clean.title===String(current.title)?priorSlug:await uniqueSlug(clean.title,id);await s.run(`UPDATE topics SET title=?,body=?,type=?,category=?,skills_json=?,city=?,lga=?,slug=?,status='submitted',moderation_note=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?`,[clean.title,clean.body,clean.type,clean.category,JSON.stringify(clean.skills),clean.city,clean.lga,nextSlug,id]);if(nextSlug!==priorSlug)await addRedirect(`/topics/${priorSlug}`,`/topics/${nextSlug}`);return getTopicForOwner(id,authorPhone);}
export async function removeTopic(authorPhone:string,id:string){const current=await existingTopicById(id);if(!current)throw new Error('Topic not found');if(String(current.author_phone)!==authorPhone)throw new Error('Topic ownership is required');await(await getCanonicalStore()).run(`UPDATE topics SET status='removed',updated_at=CURRENT_TIMESTAMP WHERE id=?`,[id]);await revokeRelationshipsForTarget('topic',id,'topic_removed');return{id,removed:true};}
export async function getTopicForOwner(id:string,authorPhone:string){const row=await existingTopicById(id);if(!row||String(row.author_phone)!==authorPhone)return null;return parseTopic(row,true);}
export async function listTopicsForOwner(authorPhone:string,limit=50){const s=await getCanonicalStore(),rows=await s.all<any>(`${TOPIC_SELECT} WHERE t.author_phone=? ORDER BY t.updated_at DESC LIMIT ?`,[authorPhone,Math.max(1,Math.min(100,Math.floor(limit)))]);return rows.map(r=>parseTopic(r,true));}
async function linkedResources(topicId:string){const s=await getCanonicalStore(),rows=await s.all<any>(`SELECT c.slug,c.title,c.type FROM topic_resource_links l JOIN content c ON c.slug=l.resource_slug WHERE l.topic_id=? ORDER BY l.created_at ASC LIMIT 6`,[topicId]);return rows.map(row=>({slug:String(row.slug),title:String(row.title),type:String(row.type)}));}
export async function linkTopicResource(topicId:string,resourceSlug:unknown,adminIdentity:string){const slug=typeof resourceSlug==='string'?resourceSlug.trim().toLowerCase():'';if(!/^[a-z0-9][a-z0-9-]{0,119}$/.test(slug))throw new Error('A valid existing resource slug is required');const s=await getCanonicalStore(),topic=await existingTopicById(topicId);if(!topic||String(topic.status)!=='public')throw new Error('Only public Topics can be linked to editorial resources');const row=await s.one<any>('SELECT slug,title,type FROM content WHERE slug=? LIMIT 1',[slug]);if(!row)throw new Error('Editorial resource not found');await s.run('INSERT INTO topic_resource_links(topic_id,resource_slug,created_by) VALUES(?,?,?) ON CONFLICT DO NOTHING',[topicId,slug,adminIdentity.slice(0,128)]);return{slug:String(row.slug),title:String(row.title),type:String(row.type)};}
export async function getTopicChatContext(slug:string){const topic=await getPublicTopic(slug);if(!topic)return null;return{id:topic.id,slug:topic.slug,title:topic.title,type:topic.type,category:topic.category,skills:topic.skills,city:topic.city,lga:topic.lga,body:topic.body.slice(0,1200),provenance:'community_statement' as const};}
export async function getPublicTopic(slug:string){const row=await existingTopicBySlug(slug);if(!row||String(row.status)!=='public')return null;const s=await getCanonicalStore(),replies=(await s.all<any>(`SELECT id,topic_id,author_phone,body,status,moderation_note,created_at,updated_at FROM topic_replies WHERE topic_id=? AND status='public' ORDER BY created_at ASC LIMIT 100`,[String(row.id)])).map(r=>parseReply(r));return{...parseTopic(row),replies,relatedResources:await linkedResources(String(row.id))};}
export async function listPublicTopics(filters:{category?:unknown;skill?:unknown;type?:unknown;city?:unknown;limit?:unknown}={}){const conditions=["t.status='public'"],params:unknown[]=[],category=typeof filters.category==='string'?filters.category.trim().toLowerCase():'',skill=typeof filters.skill==='string'?filters.skill.trim().toLowerCase():'',type=typeof filters.type==='string'?filters.type.trim().toLowerCase():'',city=typeof filters.city==='string'?filters.city.trim():'';if(category){conditions.push('t.category=?');params.push(category);}if(skill){conditions.push('t.skills_json LIKE ?');params.push(`%\"${skill.replace(/[%_]/g,'')}\"%`);}if(type&&TOPIC_TYPES.includes(type as TopicType)){conditions.push('t.type=?');params.push(type);}if(city){conditions.push('lower(t.city)=lower(?)');params.push(city.slice(0,80));}const limit=Math.max(1,Math.min(50,Number.isFinite(Number(filters.limit))?Math.floor(Number(filters.limit)):20)),rows=await(await getCanonicalStore()).all<any>(`${TOPIC_SELECT} WHERE ${conditions.join(' AND ')} ORDER BY t.published_at DESC,t.updated_at DESC LIMIT ?`,[...params,limit]);return rows.map(r=>parseTopic(r));}
export async function findTopicDuplicateCandidates(input:Pick<TopicInput,'title'|'category'>){const title=typeof input.title==='string'?cleanText(input.title,'title',12,160):'',category=typeof input.category==='string'?input.category.trim().toLowerCase():'',terms=[...new Set(title.toLowerCase().match(/[a-z0-9]{4,}/g)||[])].slice(0,3);if(!terms.length)return[];const conditions=["t.status='public'",`(${terms.map(()=> 'lower(t.title) LIKE ?').join(' OR ')})`],params:unknown[]=terms.map(term=>`%${term.replace(/[%_]/g,'')}%`);if(category&&(ECONOMIC_CATEGORIES as readonly string[]).includes(category)){conditions.push('t.category=?');params.push(category);}const rows=await(await getCanonicalStore()).all<any>(`${TOPIC_SELECT} WHERE ${conditions.join(' AND ')} ORDER BY t.published_at DESC LIMIT 5`,params);return rows.map(r=>parseTopic(r));}
export async function createReply(authorPhone:string,topicId:string,input:TopicReplyInput){const body=cleanText(input.body,'reply body',2,4000),s=await getCanonicalStore(),topic=await existingTopicById(topicId);if(!topic||String(topic.status)!=='public')throw new Error('Replies are available only on public Topics');const id=randomUUID();await s.run(`INSERT INTO topic_replies(id,topic_id,author_phone,body,status) VALUES(?,?,?,?, 'submitted')`,[id,topicId,authorPhone,body]);return getReplyForOwner(id,authorPhone);}
export async function getReplyForOwner(id:string,authorPhone:string){const row=await(await getCanonicalStore()).one<any>(`SELECT id,topic_id,author_phone,body,status,moderation_note,created_at,updated_at FROM topic_replies WHERE id=? AND author_phone=? LIMIT 1`,[id,authorPhone]);return row?parseReply(row,true):null;}
export async function createTopicReport(reporterPhone:string,targetType:unknown,targetId:unknown,reason:unknown,detail?:unknown){const type=targetType==='reply'?'reply':targetType==='topic'?'topic':null,id=typeof targetId==='string'?targetId.trim():'';if(!type||!id)throw new Error('A valid Topic or reply report target is required');const cleanReason=cleanText(reason,'report reason',3,80),cleanDetail=detail==null||detail===''?null:cleanText(detail,'report detail',3,1000),s=await getCanonicalStore(),exists=await s.one(type==='topic'?'SELECT 1 FROM topics WHERE id=? LIMIT 1':'SELECT 1 FROM topic_replies WHERE id=? LIMIT 1',[id]);if(!exists)throw new Error('Report target not found');const open=await s.one<any>(`SELECT id FROM topic_reports WHERE reporter_phone=? AND target_type=? AND target_id=? AND status='open' LIMIT 1`,[reporterPhone,type,id]);if(open?.id)return{id:String(open.id),status:'open',idempotent:true};const reportId=randomUUID();try{await s.run(`INSERT INTO topic_reports(id,target_type,target_id,reporter_phone,reason,detail) VALUES(?,?,?,?,?,?)`,[reportId,type,id,reporterPhone,cleanReason,cleanDetail]);return{id:reportId,status:'open',idempotent:false};}catch(error){if(!isUniqueConstraint(error))throw error;const duplicate=await s.one<any>(`SELECT id FROM topic_reports WHERE reporter_phone=? AND target_type=? AND target_id=? AND status='open' LIMIT 1`,[reporterPhone,type,id]);if(duplicate?.id)return{id:String(duplicate.id),status:'open',idempotent:true};throw error;}}
export async function listSubmittedTopics(limit=100){const rows=await(await getCanonicalStore()).all<any>(`${TOPIC_SELECT} WHERE t.status IN ('submitted','restricted') ORDER BY t.updated_at ASC LIMIT ?`,[Math.max(1,Math.min(200,Math.floor(limit)))]);return rows.map(r=>parseTopic(r,true));}
export async function moderateTopic(id:string,input:TopicModerationInput){const decision=input.decision==='public'||input.decision==='restricted'||input.decision==='removed'?input.decision:null;if(!decision)throw new Error('Moderation decision must be public, restricted, or removed');const note=input.note==null||input.note===''?null:cleanText(input.note,'moderation note',3,1000),s=await getCanonicalStore(),current=await existingTopicById(id);if(!current)throw new Error('Topic not found');await s.run(`UPDATE topics SET status=?,moderation_note=?,published_at=CASE WHEN ?='public' THEN COALESCE(published_at,CURRENT_TIMESTAMP) ELSE published_at END,updated_at=CURRENT_TIMESTAMP WHERE id=?`,[decision,note,decision,id]);const updated=await existingTopicById(id);if(decision==='public'&&updated)await notifyRelationshipTargetUpdate('topic',id,{title:'A Topic you follow changed',body:'A Topic you follow is available with a new status or moderated update.',link:`/topics/${encodeURIComponent(String(updated.slug))}`,signature:`topic:${id}:${String(updated.updated_at)}`});else if(decision!=='public')await revokeRelationshipsForTarget('topic',id,'topic_no_longer_public');return updated?parseTopic(updated,true):null;}
export async function listSubmittedReplies(limit=100){const rows=await(await getCanonicalStore()).all<any>(`SELECT id,topic_id,author_phone,body,status,moderation_note,created_at,updated_at FROM topic_replies WHERE status IN ('submitted','restricted') ORDER BY updated_at ASC LIMIT ?`,[Math.max(1,Math.min(200,Math.floor(limit)))]);return rows.map(r=>parseReply(r,true));}
export async function moderateReply(id:string,input:TopicModerationInput){const decision=input.decision==='public'||input.decision==='restricted'||input.decision==='removed'?input.decision:null;if(!decision)throw new Error('Moderation decision must be public, restricted, or removed');const note=input.note==null||input.note===''?null:cleanText(input.note,'moderation note',3,1000),s=await getCanonicalStore();const result=await s.run(`UPDATE topic_replies SET status=?,moderation_note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`,[decision,note,id]);if(result.rowCount!==1)throw new Error('Reply not found');const row=await s.one<any>(`SELECT id,topic_id,author_phone,body,status,moderation_note,created_at,updated_at FROM topic_replies WHERE id=? LIMIT 1`,[id]);if(row&&decision==='public')await notifyRelationshipTargetUpdate('topic',String(row.topic_id),{title:'A Topic you follow changed',body:'There is new moderated activity on a Topic you follow.',link:`/chat?prompt=${encodeURIComponent('Review the new moderated activity on a Topic I follow')}`,signature:`topic-reply:${String(row.topic_id)}:${String(row.updated_at)}`});return row?parseReply(row,true):null;}
export async function listTopicReports(limit=100){const rows=await(await getCanonicalStore()).all<any>(`SELECT id,target_type,target_id,reporter_phone,reason,detail,status,moderation_note,created_at,reviewed_at FROM topic_reports WHERE status='open' ORDER BY created_at ASC LIMIT ?`,[Math.max(1,Math.min(200,Math.floor(limit)))]);return rows.map(row=>({id:String(row.id),targetType:String(row.target_type),targetId:String(row.target_id),reporterPhone:String(row.reporter_phone),reason:String(row.reason),detail:row.detail?String(row.detail):null,status:String(row.status),createdAt:String(row.created_at)}));}
export async function closeTopicReport(id:string,note?:unknown){const cleanNote=note==null||note===''?null:cleanText(note,'moderation note',3,1000),result=await(await getCanonicalStore()).run(`UPDATE topic_reports SET status='closed',moderation_note=?,reviewed_at=CURRENT_TIMESTAMP WHERE id=? AND status='open'`,[cleanNote,id]);if(result.rowCount!==1)throw new Error('Open Topic report not found');return{id,status:'closed'};}
export function getTopicTaxonomy(){const skillsByCategory:Record<string,string[]>={};for(const skill of getKnownSkills()){const category=getEconomicCategory(skill);if(!category)continue;(skillsByCategory[category]||=[]).push(skill);}for(const skills of Object.values(skillsByCategory))skills.sort();return{types:[...TOPIC_TYPES],categories:[...ECONOMIC_CATEGORIES],skillsByCategory};}
export async function getTopicStats(){const rows=await(await getCanonicalStore()).all<any>('SELECT status,COUNT(*) AS count FROM topics GROUP BY status'),counts:Record<string,number>={};for(const row of rows)counts[String(row.status)]=Number(row.count||0);return{public:counts.public||0,submitted:counts.submitted||0,restricted:counts.restricted||0,removed:counts.removed||0};}
