import { getCanonicalStore } from './canonicalStore.js';
export interface TrustScoreBreakdown{phone:string;avgRating:number;completedJobs:number;verifiedProvider:boolean;disputesLost:number;accountAgeDays:number;score:number;}
const clamp=(v:number,min:number,max:number)=>Math.min(max,Math.max(min,v));
export function calculateTrustScoreValue(input:Omit<TrustScoreBreakdown,'phone'|'score'>):number{const avgRating=Number.isFinite(input.avgRating)&&input.avgRating>0?clamp(input.avgRating,1,5):3;const completedJobs=Math.max(0,Number(input.completedJobs)||0),disputesLost=Math.max(0,Number(input.disputesLost)||0),accountAgeDays=Math.max(0,Number(input.accountAgeDays)||0);return Number(clamp(5+((avgRating-3)*.5)+Math.min(completedJobs/100,1)+(input.verifiedProvider?.5:0)-(disputesLost*.2)+Math.min(accountAgeDays/365,.5),0,8).toFixed(2));}
const age=(x:unknown)=>{const t=new Date(String(x||'')).getTime();return Number.isFinite(t)?Math.max(0,(Date.now()-t)/86400000):0;};
export async function ensureTrustScoreSchema(){const s=await getCanonicalStore();await s.run(`CREATE TABLE IF NOT EXISTS trust_score_ledger(id INTEGER PRIMARY KEY,phone TEXT NOT NULL,score REAL NOT NULL,breakdown_json TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);await s.run('CREATE INDEX IF NOT EXISTS idx_trust_score_ledger_phone ON trust_score_ledger(phone,created_at DESC)');}
async function calculate(phone:string){await ensureTrustScoreSchema();const s=await getCanonicalStore();const p=await s.one<any>('SELECT created_at,verified_provider FROM memory_profiles WHERE phone=? LIMIT 1',[phone]);if(!p)return null;const stats=await s.one<any>('SELECT COALESCE(AVG(rating),0) avg_rating,COALESCE(SUM(jobs_completed),0) completed_jobs FROM skills WHERE phone=?',[phone]);const disputes=await s.one<any>("SELECT COUNT(*) count FROM disputes WHERE status='resolved' AND fault_phone=?",[phone]);const b:any={phone,avgRating:Number(stats?.avg_rating)>0?clamp(Number(stats.avg_rating),1,5):3,completedJobs:Math.max(0,Number(stats?.completed_jobs)||0),verifiedProvider:Number(p.verified_provider)===1,disputesLost:Math.max(0,Number(disputes?.count)||0),accountAgeDays:age(p.created_at),score:5};b.score=calculateTrustScoreValue(b);return b;}
export async function recalculateTrustScore(phone:string,reason='scheduled_recalculation'){const b=await calculate(String(phone||'').trim());if(!b)return null;const s=await getCanonicalStore();await s.transaction(async tx=>{await tx.run('UPDATE memory_profiles SET trust_score=?,updated_at=CURRENT_TIMESTAMP WHERE phone=?',[b.score,b.phone]);await tx.run('INSERT INTO trust_score_ledger(phone,score,breakdown_json,reason) VALUES(?,?,?,?)',[b.phone,b.score,JSON.stringify({avgRating:b.avgRating,completedJobs:b.completedJobs,verifiedProvider:b.verifiedProvider,disputesLost:b.disputesLost,accountAgeDays:Number(b.accountAgeDays.toFixed(2))}),String(reason||'scheduled_recalculation').slice(0,120)]);return undefined;});return b;}
export async function listTrustScoreLedger(phone:string,limit=25){await ensureTrustScoreSchema();const rows=await(await getCanonicalStore()).all<any>('SELECT score,breakdown_json,reason,created_at FROM trust_score_ledger WHERE phone=? ORDER BY id DESC LIMIT ?',[String(phone||'').trim(),Math.max(1,Math.min(100,Number(limit)||25))]);return rows.flatMap(r=>{try{return[{score:Number(r.score),reason:String(r.reason),createdAt:String(r.created_at||''),breakdown:JSON.parse(String(r.breakdown_json||'{}'))}];}catch{return[];}});}
export async function recalculateAllTrustScores(){const rows=await(await getCanonicalStore()).all<any>("SELECT phone FROM memory_profiles WHERE phone IS NOT NULL AND phone != ''");let updated=0;for(const r of rows)if(await recalculateTrustScore(String(r.phone)))updated++;return updated;}
export async function getTrustScoreBreakdown(phone:string){return calculate(String(phone||'').trim());}
export async function recordDisputeFault(disputeId:number,faultParty:'buyer'|'provider',faultPhone:string){const p=String(faultPhone||'').trim();if(!p)throw new Error('A reviewed fault owner is required');await ensureTrustScoreSchema();const s=await getCanonicalStore();await s.run('UPDATE disputes SET fault_party=?,fault_phone=? WHERE id=?',[faultParty,p,disputeId]);await recalculateTrustScore(p,'reviewed_dispute_fault');}
