import crypto from 'node:crypto';
import { getCanonicalStore } from './canonicalStore.js';
import { getCanonicalPersistenceMode } from './canonicalPersistence.js';
import { sendSmsText } from '../channels/sms.js';
import { sendEmail } from './emailService.js';
import { activateSafetyContact, revokeSafetyContact } from './safetyService.js';
export type TrustedContactConsentStatus='pending'|'accepted'|'declined'|'expired'|'revoked';
export type TrustedContactDeliveryState='not_configured'|'accepted'|'failed';
export interface TrustedContactReadiness{smsConfigured:boolean;emailConfigured:boolean;providerAvailable:boolean;externalActivationRequired:true;reason:string;}
export interface TrustedContactConsentRequest{id:string;owner_phone:string;contact_id:string;channel:'sms'|'email';status:TrustedContactConsentStatus;delivery_state:TrustedContactDeliveryState;provider:string|null;expires_at:string;created_at:string;responded_at:string|null;consent_url?:string;}
function required(name:string):string|undefined{const value=String(process.env[name]||'').trim();return value&&value.toLowerCase()!=='stub'?value:undefined;}
function hashToken(token:string):string{return crypto.createHash('sha256').update(token).digest('hex');}
function consentBaseUrl():string{return required('PUBLIC_BASE_URL')||'http://localhost:3000';}
function exposeDevelopmentLink():boolean{return process.env.NODE_ENV!=='production'&&process.env.KURUKOO_CONTACT_CONSENT_EXPOSE_DEV_LINK==='true';}
export function getTrustedContactReadiness(env:NodeJS.ProcessEnv=process.env):TrustedContactReadiness{const smsConfigured=Boolean(env.AFRICASTALKING_API_KEY&&env.AFRICASTALKING_USERNAME&&env.AFRICASTALKING_API_KEY.toLowerCase()!=='stub'&&env.AFRICASTALKING_USERNAME.toLowerCase()!=='stub'),emailConfigured=Boolean((env.RESEND_API_KEY&&env.EMAIL_FROM)||env.EMAIL_WEBHOOK_URL);return{smsConfigured,emailConfigured,providerAvailable:smsConfigured||emailConfigured,externalActivationRequired:true,reason:smsConfigured||emailConfigured?'trusted_contact_delivery_boundary_configured_for_provider_validation':'no_sms_or_email_provider_configured; consent remains pending and no delivery is claimed'};}
async function ensureTrustedContactSchema(){const s=await getCanonicalStore(),pg=getCanonicalPersistenceMode()==='postgres';await s.run(`CREATE TABLE IF NOT EXISTS trusted_contact_consent_requests(id TEXT PRIMARY KEY,owner_phone TEXT NOT NULL,contact_id TEXT NOT NULL,channel TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,status TEXT NOT NULL DEFAULT 'pending',delivery_state TEXT NOT NULL DEFAULT 'not_configured',provider TEXT,provider_id TEXT,expires_at ${pg?'TIMESTAMPTZ':'TEXT'} NOT NULL,created_at ${pg?'TIMESTAMPTZ':'TEXT'} DEFAULT CURRENT_TIMESTAMP,responded_at ${pg?'TIMESTAMPTZ':'TEXT'})`);await s.run('CREATE INDEX IF NOT EXISTS idx_trusted_contact_consent_owner ON trusted_contact_consent_requests(owner_phone,status)');await s.run('CREATE INDEX IF NOT EXISTS idx_trusted_contact_consent_expiry ON trusted_contact_consent_requests(expires_at,status)');return s;}
function readRequest(row:any,rawToken?:string):TrustedContactConsentRequest{const request={id:String(row.id),owner_phone:String(row.owner_phone),contact_id:String(row.contact_id),channel:String(row.channel) as 'sms'|'email',status:String(row.status) as TrustedContactConsentStatus,delivery_state:String(row.delivery_state) as TrustedContactDeliveryState,provider:row.provider?String(row.provider):null,expires_at:String(row.expires_at),created_at:String(row.created_at),responded_at:row.responded_at?String(row.responded_at):null};if(rawToken&&exposeDevelopmentLink())(request as any).consent_url=`${consentBaseUrl()}/consent/trusted-contact?token=${encodeURIComponent(rawToken)}`;return request;}
export async function createTrustedContactConsentRequest(ownerPhone:string,contactId:string,channel:'sms'|'email',recipientEmail?:string):Promise<TrustedContactConsentRequest>{const s=await ensureTrustedContactSchema();if(!ownerPhone||!contactId)throw new Error('Owner and contact are required');if(!['sms','email'].includes(channel))throw new Error('Unsupported consent channel');const contact=await s.one<any>("SELECT id,name,phone,status FROM user_safety_contacts WHERE id=? AND owner_phone=? AND status='pending'",[contactId,ownerPhone]);if(!contact)throw new Error('Pending safety contact not found');if(channel==='email'&&!String(recipientEmail||'').trim())throw new Error('An email recipient is required for email consent');const token=crypto.randomBytes(32).toString('base64url'),id=crypto.randomUUID(),expiresAt=new Date(Date.now()+48*60*60*1000).toISOString(),consentUrl=`${consentBaseUrl()}/consent/trusted-contact?token=${encodeURIComponent(token)}`,body=`Kurukoo is asking you to become ${String(contact.name)}'s trusted safety contact. Review and consent here: ${consentUrl}`;let deliveryState:TrustedContactDeliveryState='not_configured',provider:string|null=null,providerId:string|null=null;if(channel==='sms'){const result=await sendSmsText(String(contact.phone),body);deliveryState=result.ok?'accepted':result.reason==='sms_provider_not_configured'?'not_configured':'failed';provider=result.provider;}else{const result=await sendEmail(String(recipientEmail).trim(),'Kurukoo trusted-contact consent',body,{idempotencyKey:`trusted-contact-consent:${id}`,sensitive:true});deliveryState=result.ok?'accepted':result.provider==='disabled'?'not_configured':'failed';provider=result.provider;providerId=result.id||null;}await s.run(`INSERT INTO trusted_contact_consent_requests(id,owner_phone,contact_id,channel,token_hash,status,delivery_state,provider,provider_id,expires_at) VALUES(?,?,?,?,?,'pending',?,?,?,?)`,[id,ownerPhone,contactId,channel,hashToken(token),deliveryState,provider,providerId,expiresAt]);const row=await s.one<any>('SELECT * FROM trusted_contact_consent_requests WHERE id=?',[id]);if(!row)throw new Error('Unable to persist consent request');return readRequest(row,token);}
export async function listTrustedContactConsentRequests(ownerPhone:string,contactId?:string):Promise<TrustedContactConsentRequest[]>{const s=await ensureTrustedContactSchema(),rows=contactId?await s.all<any>('SELECT * FROM trusted_contact_consent_requests WHERE owner_phone=? AND contact_id=? ORDER BY created_at DESC',[ownerPhone,contactId]):await s.all<any>('SELECT * FROM trusted_contact_consent_requests WHERE owner_phone=? ORDER BY created_at DESC',[ownerPhone]);return rows.map(row=>readRequest(row));}
export async function respondToTrustedContactConsent(token:string,decision:'accept'|'decline'):Promise<{status:TrustedContactConsentStatus;contactId:string}|null>{const s=await ensureTrustedContactSchema(),cleanToken=String(token||'').trim();if(!cleanToken||!['accept','decline'].includes(decision))return null;const request=await s.one<any>(`SELECT * FROM trusted_contact_consent_requests WHERE token_hash=? AND status='pending' LIMIT 1`,[hashToken(cleanToken)]);if(!request)return null;if(new Date(String(request.expires_at)).getTime()<=Date.now()){await s.run("UPDATE trusted_contact_consent_requests SET status='expired',responded_at=CURRENT_TIMESTAMP WHERE id=?",[String(request.id)]);return{status:'expired',contactId:String(request.contact_id)};}const status:TrustedContactConsentStatus=decision==='accept'?'accepted':'declined';await s.run('UPDATE trusted_contact_consent_requests SET status=?,responded_at=CURRENT_TIMESTAMP WHERE id=?',[status,String(request.id)]);if(status==='accepted')await activateSafetyContact(String(request.owner_phone),String(request.contact_id),true);if(status==='declined')await revokeSafetyContact(String(request.owner_phone),String(request.contact_id));return{status,contactId:String(request.contact_id)};}
export async function revokeTrustedContactConsentRequest(ownerPhone:string,requestId:string):Promise<boolean>{const s=await ensureTrustedContactSchema();return(await s.run("UPDATE trusted_contact_consent_requests SET status='revoked',responded_at=CURRENT_TIMESTAMP WHERE id=? AND owner_phone=? AND status='pending'",[requestId,ownerPhone])).rowCount>0;}
