import assert from 'node:assert/strict';
import os from 'node:os';
import path from 'node:path';
process.env.NODE_ENV='production';
process.env.KURUKOO_PAY_PROVIDER='sandbox';
process.env.CREDIT_ECONOMY_ENABLED='true';
process.env.FF_WEBRTC='false';
process.env.DB_PATH=path.join(os.tmpdir(),`kurukoo-quick-ride-${process.pid}-${Date.now()}.sqlite`);
const { getDb } = await import('../src/database.js');
const { requestRide } = await import('../src/services/quickRideDispatchService.js');
const db=await getDb();
const customer='+2347000010001';
const driver='+2347000010002';
db.run('INSERT INTO memory_profiles (phone,name,country,verified_provider,points_balance,grace_leads) VALUES (?,?,?,0,0,0)',[customer,'Quick Ride Customer','ng']);
db.run('INSERT INTO memory_profiles (phone,name,country,verified_provider,points_balance,grace_leads) VALUES (?,?,?,1,100,0)',[driver,'Quick Ride Driver','ng']);
db.run("INSERT INTO skills (phone,skill,is_available,hourly_rate,rating,jobs_completed,operation_mode) VALUES (?,?,1,100,4.9,10,'mobile')",[driver,'okada_rider']);
const ride=await requestRide({ownerPhone:customer,originLatitude:6.5244,originLongitude:3.3792,originLabel:'Ikeja City Mall',destinationLabel:'Yaba',vehicleType:'bike',maxProviders:3});
assert.ok(ride.requestId);
assert.equal(ride.origin.latitude,6.5244);
assert.equal(ride.origin.longitude,3.3792);
assert.equal(ride.destination.label,'Yaba');
assert.equal(ride.vehicleType,'bike');
assert.ok(ride.offers.some((offer)=>offer.providerPhone===driver));
console.log(JSON.stringify({passed:true,requestId:ride.requestId,vehicleType:ride.vehicleType,offers:ride.offers.length,state:ride.state},null,2));
